/* AI TRADE — Alert Notification Center 1.0 */
(()=>{
const CFG=window.AITRADE_CLOUD_CONFIG||{};let cache=[];
async function token(){if(!window.supabase||!CFG.url||!CFG.anonKey)return null;const sb=window.supabase.createClient(CFG.url,CFG.anonKey,{auth:{persistSession:true,autoRefreshToken:true}});const {data}=await sb.auth.getSession();return data.session?.access_token||null}
async function call(action,payload={}){const t=await token();if(!t)throw new Error('请先登录AI TRADE云同步');const r=await fetch(`${CFG.url}/functions/v1/alert-notification-runner`,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${t}`,'apikey':CFG.anonKey},body:JSON.stringify({action,...payload})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.detail||d.error||'请求失败');return d}
function css(){if(document.getElementById('ancStyle'))return;let s=document.createElement('style');s.id='ancStyle';s.textContent=`#ancBtn{position:fixed;right:14px;bottom:110px;z-index:9998;border:0;border-radius:999px;padding:10px 14px;background:#7c3aed;color:#fff;font:700 12px Arial;box-shadow:0 8px 24px #0003}#ancBadge{margin-left:6px;background:#ef4444;color:#fff;border-radius:999px;padding:1px 6px;font-size:10px}#ancModal{position:fixed;inset:0;z-index:10040;background:#0f172a80;display:none;align-items:center;justify-content:center;padding:14px}#ancModal .box{width:min(920px,96vw);max-height:90vh;overflow:auto;background:#f8fafc;border-radius:18px;padding:16px}.ancGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.ancCard{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:12px}.ancList{background:#fff;border-radius:12px;border:1px solid #e5e7eb;overflow:hidden}.ancItem{padding:12px;border-bottom:1px solid #eef2f7}.ancItem:last-child{border-bottom:0}.ancMeta{font-size:11px;color:#64748b}.ancTitle{font-weight:800;margin-bottom:4px}.ancBtn{border:0;border-radius:8px;padding:8px 10px;background:#2563eb;color:#fff;cursor:pointer}.ancBtn.gray{background:#eef2ff;color:#3730a3}.ancUrgent{border-left:4px solid #ef4444}.ancHigh{border-left:4px solid #f59e0b}@media(max-width:700px){.ancGrid{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
function esc(s){return String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function render(items,settings){cache=items||[];const unread=cache.filter(x=>['pending','sent'].includes(x.status)&&x.channel==='in_app').length;document.getElementById('ancBadge').textContent=unread;document.getElementById('ancBadge').style.display=unread?'inline-block':'none';const b=document.getElementById('ancBody');if(!b)return;const urgent=cache.filter(x=>x.severity==='urgent'||x.severity==='critical').length,high=cache.filter(x=>x.severity==='high').length,pending=cache.filter(x=>x.status==='pending').length,sent=cache.filter(x=>x.status==='sent').length;b.innerHTML=`<div style="display:flex;justify-content:space-between;gap:8px;align-items:center"><div><h2 style="margin:0">Alert Notification Center</h2><div class="ancMeta">RFQ、Gmail OAuth、Dead Letter、Worker异常和高优先级客户回复的主动告警中心。</div></div><button class="ancBtn gray" onclick="AI_ALERTS.close()">关闭</button></div><div class="ancGrid" style="margin-top:12px"><div class="ancCard"><div class="ancMeta">Urgent</div><div style="font-size:24px;font-weight:800">${urgent}</div></div><div class="ancCard"><div class="ancMeta">High</div><div style="font-size:24px;font-weight:800">${high}</div></div><div class="ancCard"><div class="ancMeta">Pending</div><div style="font-size:24px;font-weight:800">${pending}</div></div><div class="ancCard"><div class="ancMeta">Sent</div><div style="font-size:24px;font-weight:800">${sent}</div></div></div><h3>通知设置</h3><div class="ancCard"><label><input id="anIn" type="checkbox" ${settings?.in_app_enabled!==false?'checked':''}> 系统内通知</label>　<label><input id="anEmail" type="checkbox" ${settings?.email_enabled!==false?'checked':''}> Gmail邮件提醒</label>　<label><input id="anCrit" type="checkbox" ${settings?.critical_only?'checked':''}> 仅关键告警</label><br><br><label><input id="anRfq" type="checkbox" ${settings?.notify_rfq!==false?'checked':''}> RFQ</label>　<label><input id="anOauth" type="checkbox" ${settings?.notify_oauth!==false?'checked':''}> Gmail OAuth</label>　<label><input id="anDead" type="checkbox" ${settings?.notify_dead_letter!==false?'checked':''}> Dead Letter</label>　<label><input id="anWorker" type="checkbox" ${settings?.notify_worker_failure!==false?'checked':''}> Worker失败</label>　<button class="ancBtn" onclick="AI_ALERTS.save()">保存</button></div><h3>最近通知</h3><div class="ancList">${cache.filter(x=>x.channel==='in_app').slice(0,50).map(x=>`<div class="ancItem ${x.severity==='urgent'||x.severity==='critical'?'ancUrgent':x.severity==='high'?'ancHigh':''}"><div class="ancTitle">${esc(x.title)}</div><div>${esc(x.message||'')}</div><div class="ancMeta">${esc(x.severity)} · ${esc(x.source)} · ${esc(x.created_at||'')}</div>${x.status!=='read'?`<div style="margin-top:8px"><button class="ancBtn gray" onclick="AI_ALERTS.read(${x.id})">标记已读</button></div>`:''}</div>`).join('')||'<div class="ancItem">暂无通知</div>'}</div>`}
async function refresh(){try{const [s,n]=await Promise.all([call('settings_get'),call('status')]);render(n.notifications||[],s.settings||{})}catch(e){console.warn(e)}}
async function save(){try{await call('settings_save',{in_app_enabled:anIn.checked,email_enabled:anEmail.checked,critical_only:anCrit.checked,notify_rfq:anRfq.checked,notify_oauth:anOauth.checked,notify_dead_letter:anDead.checked,notify_worker_failure:anWorker.checked});await refresh()}catch(e){alert(e.message)}}
async function read(id){try{await call('mark_read',{id});await refresh()}catch(e){alert(e.message)}}
function open(){document.getElementById('ancModal').style.display='flex';refresh()}function close(){document.getElementById('ancModal').style.display='none'}
function boot(){css();if(!document.getElementById('ancBtn')){let b=document.createElement('button');b.id='ancBtn';b.innerHTML='🔔 Alerts <span id="ancBadge" style="display:none"></span>';b.onclick=open;document.body.appendChild(b)}if(!document.getElementById('ancModal')){let m=document.createElement('div');m.id='ancModal';m.innerHTML='<div class="box" id="ancBody"></div>';m.onclick=e=>{if(e.target===m)close()};document.body.appendChild(m)}setTimeout(refresh,2500);setInterval(refresh,60000)}
window.AI_ALERTS={open,close,refresh,save,read};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();