/* AI TRADE — Autonomous Lead Acquisition 2.0 */
(()=>{
const DBK='aitrade_full59_v1', GK='aitrade_goal_gap_v1', KEY='aitrade_autonomous_leads_v2';
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')||d}catch{return d}};
const put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const cfg=()=>get(KEY,{enabled:true,market:'Mexico',minIcp:60,dailyCap:50,lastRunDate:null,lastResult:null,autoRun:true});
const save=x=>{put(KEY,x);window.AITRADE_CLOUD?.push?.()};
async function ensureSupabase(){if(window.supabase)return window.supabase;await new Promise((res,rej)=>{let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=res;s.onerror=rej;document.head.appendChild(s)});return window.supabase}
function mergeCandidates(rows){let db=get(DBK,{customers:[],leads:[],signals:[],quotes:[],orders:[]}),added=0,promoted=0;db.leads=db.leads||[];db.customers=db.customers||[];for(const r of rows||[]){if(!r?.url)continue;let exists=db.leads.some(x=>x.url===r.url||x.domain&&r.domain&&x.domain===r.domain)||db.customers.some(x=>x.website===r.url||x.domain&&r.domain&&x.domain===r.domain);if(exists)continue;let lead={id:'WEB-'+Date.now()+Math.random().toString(36).slice(2,6),company:r.company_name||r.title||r.domain,domain:r.domain,url:r.url,website:r.url,market:r.market||'Mexico',source:r.source||'public_web',icp:r.icp_score||0,status:'candidate',evidence:r.evidence||{},snippet:r.snippet||'',createdAt:new Date().toISOString()};db.leads.push(lead);added++;if((r.icp_score||0)>=70){db.customers.push({id:'CUS-'+Date.now()+Math.random().toString(36).slice(2,6),company:lead.company,country:lead.market,website:lead.website,domain:lead.domain,icp:r.icp_score,stage:'prospect',source:lead.source,notes:`[Autonomous Lead Acquisition 2.0] Public web verified candidate. ${lead.snippet}`.trim(),createdAt:new Date().toISOString()});promoted++;}}
put(DBK,db);window.FeedbackBrain2?.learn?.();window.AutomationOrchestrator?.run?.();window.AITRADE_CLOUD?.push?.();return{added,promoted};}
async function run(opts={}){let c=cfg(),gap=get(GK,{}),target=Math.min(Number(opts.target_count||gap.gaps?.leads||20),c.dailyCap);if(!target)return{ok:true,skipped:'no_gap'};let cfgCloud=window.AITRADE_CLOUD_CONFIG||{};if(!cfgCloud.url||!cfgCloud.anonKey)return{ok:false,error:'cloud_not_configured'};await ensureSupabase();let sb=window.supabase.createClient(cfgCloud.url,cfgCloud.anonKey,{auth:{persistSession:true,autoRefreshToken:true}});let {data:{session}}=await sb.auth.getSession();if(!session)return{ok:false,error:'not_logged_in'};let market=opts.market||c.market,query=opts.query||`headphones earphones consumer electronics distributor importer wholesale ${market}`;let r=await fetch(`${cfgCloud.url}/functions/v1/lead-acquisition-runner`,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${session.access_token}`},body:JSON.stringify({market,target_count:target,query})});let out=await r.json();if(!r.ok||!out.ok){c.lastResult=out;c.lastRunDate=new Date().toISOString().slice(0,10);save(c);return out}let merged=mergeCandidates(out.candidates||[]);c.lastRunDate=new Date().toISOString().slice(0,10);c.lastResult={...out,...merged};save(c);return c.lastResult}
async function auto(){let c=cfg(),d=new Date().toISOString().slice(0,10),gap=get(GK,{});if(!c.enabled||!c.autoRun||c.lastRunDate===d||!(gap.gaps?.leads>0))return;try{await run()}catch(e){c.lastResult={ok:false,error:String(e?.message||e)};c.lastRunDate=d;save(c)}}
window.AutonomousLeadAcquisition2={run,auto,cfg,mergeCandidates};setTimeout(auto,5500);
})();