/* AI TRADE — Autonomous Sales Loop 1.0 + RFQ-to-Order */
(()=>{
const CFG=()=>window.AITRADE_CLOUD_CONFIG||{};
async function client(){if(!window.supabase){await new Promise((res,rej)=>{let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=res;s.onerror=rej;document.head.appendChild(s)})}let c=CFG();return window.supabase.createClient(c.url,c.anonKey,{auth:{persistSession:true,autoRefreshToken:true}})}
async function session(){let sb=await client(),{data:{session}}=await sb.auth.getSession();if(!session)throw new Error('请先登录 AI TRADE 云同步');return {sb,session}}
async function run(){let {session}=await session(),c=CFG(),r=await fetch(`${c.url}/functions/v1/autonomous-sales-loop-runner`,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${session.access_token}`,'apikey':c.anonKey},body:JSON.stringify({mode:'manual'})});let x=await r.json();if(!r.ok||!x.ok)throw new Error(x.detail||x.error||'运行失败');return x}
async function load(){let {sb}=await session();let [a,r,m,l,d]=await Promise.all([
 sb.from('autonomous_sales_actions').select('*').order('created_at',{ascending:false}).limit(80),
 sb.from('rfq_cases').select('*').order('created_at',{ascending:false}).limit(50),
 sb.from('mail_execution_jobs').select('id,recipient_email,subject,status,approval_status,created_at').eq('campaign_id','autonomous_sales_loop_1').order('created_at',{ascending:false}).limit(50),
 sb.from('sales_loop_runs').select('*').order('created_at',{ascending:false}).limit(20),
 sb.from('decision_maker_candidates').select('id,company,person_name,role,email,confidence,authority_score').not('email','is',null).order('confidence',{ascending:false}).limit(30)
 ]);for(const q of [a,r,m,l,d])if(q.error)throw q.error;return {actions:a.data||[],rfqs:r.data||[],mails:m.data||[],runs:l.data||[],people:d.data||[]}}
function esc(x){return String(x??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function css(){if(document.getElementById('aslStyle'))return;let s=document.createElement('style');s.id='aslStyle';s.textContent=`#aslBtn{position:fixed;right:112px;bottom:64px;z-index:9996;border:0;border-radius:999px;padding:10px 14px;background:#2563eb;color:#fff;font:800 12px Arial;box-shadow:0 8px 25px #0002}#aslModal{position:fixed;inset:0;z-index:10070;background:#0f172a80;display:none;align-items:center;justify-content:center;padding:14px}#aslModal .box{width:min(1100px,97vw);max-height:92vh;overflow:auto;background:#f8fafc;border-radius:18px;padding:16px}.aslTop{display:flex;justify-content:space-between;gap:10px;align-items:center}.aslGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.aslCard{background:#fff;border:1px solid #e5e7eb;border-radius:13px;padding:12px}.aslBig{font-size:24px;font-weight:900;margin-top:4px}.aslFlow{display:grid;grid-template-columns:repeat(8,1fr);gap:6px;margin:12px 0}.aslStep{background:#fff;border:1px solid #dbe4f0;border-radius:12px;padding:10px 7px;text-align:center;font-size:10px;line-height:1.35}.aslStep b{display:block;font-size:17px;color:#2563eb;margin-bottom:3px}.aslTable{width:100%;border-collapse:collapse;background:#fff;border-radius:12px;overflow:hidden;font-size:11px}.aslTable th,.aslTable td{padding:9px;border-bottom:1px solid #edf2f7;text-align:left;vertical-align:top}.aslTag{display:inline-block;border-radius:999px;padding:3px 7px;background:#eef2ff;color:#3730a3;font-size:9px}.aslHigh{background:#fff7ed;color:#b45309}.aslUrgent{background:#fff1f2;color:#be123c}.aslBtn{border:0;border-radius:9px;padding:9px 11px;background:#2563eb;color:#fff;font-weight:800}.aslGhost{background:#eef2ff;color:#3730a3}.aslNote{font-size:10px;color:#64748b;line-height:1.5}@media(max-width:720px){#aslBtn{display:none!important}.aslGrid{grid-template-columns:1fr 1fr}.aslFlow{grid-template-columns:repeat(2,1fr)}.aslTable{font-size:10px}.aslTop{align-items:flex-start}}`;document.head.appendChild(s)}
function flow(){return ['自动找客','ICP筛选','找决策人','AI开发信','Human Approval','发送/跟进','RFQ→报价','订单/复购'].map((x,i)=>`<div class="aslStep"><b>${i+1}</b>${x}</div>`).join('')}
async function render(){let b=document.getElementById('aslBody');if(!b)return;b.innerHTML='<div style="padding:30px;text-align:center">正在读取 Autonomous Sales Loop…</div>';try{let x=await load(),open=x.actions.filter(a=>a.status==='open').length,approval=x.actions.filter(a=>a.requires_approval&&a.status==='open').length,rfqNew=x.rfqs.filter(r=>r.status==='new').length,drafts=x.mails.filter(m=>m.approval_status==='pending').length;b.innerHTML=`<div class="aslTop"><div><h2 style="margin:0">Autonomous Sales Loop 1.0</h2><div class="aslNote">自动找客 → 决策人 → SDR草稿 → 人工审批 → Gmail → 回复识别 → RFQ → 报价 → 成交。后台每15分钟运行一次；任何外发邮件和RFQ报价仍保留 Human Approval。</div></div><div><button class="aslBtn" onclick="AI_SALES_LOOP.execute()">立即运行</button> <button class="aslBtn aslGhost" onclick="AI_SALES_LOOP.close()">关闭</button></div></div><div class="aslFlow">${flow()}</div><div class="aslGrid"><div class="aslCard"><div class="aslNote">待处理自动动作</div><div class="aslBig">${open}</div></div><div class="aslCard"><div class="aslNote">待人工审批</div><div class="aslBig">${approval}</div></div><div class="aslCard"><div class="aslNote">新RFQ</div><div class="aslBig">${rfqNew}</div></div><div class="aslCard"><div class="aslNote">SDR待审批草稿</div><div class="aslBig">${drafts}</div></div></div><h3>RFQ → Quote → Order</h3><table class="aslTable"><thead><tr><th>客户</th><th>主题/型号</th><th>数量</th><th>目标价</th><th>状态</th><th>下一步</th></tr></thead><tbody>${x.rfqs.slice(0,20).map(r=>`<tr><td>${esc(r.from_email||r.customer_id||'-')}</td><td><b>${esc(r.subject||'-')}</b><br>${esc(r.product_model||'待识别')}</td><td>${esc(r.quantity||'-')}</td><td>${r.target_price?esc((r.currency||'')+' '+r.target_price):'-'}</td><td><span class="aslTag ${r.status==='new'?'aslHigh':''}">${esc(r.status)}</span></td><td>${esc(r.next_action||'-')}</td></tr>`).join('')||'<tr><td colspan="6">暂无真实RFQ；只有 Gmail History 中识别到 RFQ 后才会出现。</td></tr>'}</tbody></table><h3>自动销售动作</h3><table class="aslTable"><thead><tr><th>优先级</th><th>动作</th><th>实体</th><th>审批</th><th>状态</th></tr></thead><tbody>${x.actions.slice(0,30).map(a=>`<tr><td><span class="aslTag ${a.priority==='urgent'?'aslUrgent':a.priority==='high'?'aslHigh':''}">${esc(a.priority)}</span></td><td><b>${esc(a.title)}</b></td><td>${esc(a.entity_type||'')} #${esc(a.entity_id||'')}</td><td>${a.requires_approval?'需要':'自动'}</td><td>${esc(a.status)}</td></tr>`).join('')||'<tr><td colspan="5">暂无动作。</td></tr>'}</tbody></table><h3>最近运行</h3><table class="aslTable"><thead><tr><th>时间</th><th>模式</th><th>状态</th><th>结果</th></tr></thead><tbody>${x.runs.slice(0,12).map(r=>`<tr><td>${esc(r.created_at||'')}</td><td>${esc(r.mode)}</td><td>${esc(r.status)}</td><td>${esc(JSON.stringify(r.summary||{}))}</td></tr>`).join('')||'<tr><td colspan="4">尚无运行记录。</td></tr>'}</tbody></table>`}catch(e){b.innerHTML=`<div style="padding:20px;color:#b42318"><b>无法读取</b><br><br>${esc(e.message)}<br><br><button class="aslBtn aslGhost" onclick="AI_SALES_LOOP.close()">关闭</button></div>`}}
async function execute(){let b=document.getElementById('aslBody');if(b)b.innerHTML='<div style="padding:30px;text-align:center">正在执行销售闭环扫描…</div>';try{await run();await render()}catch(e){b.innerHTML=`<div style="padding:20px;color:#b42318">${esc(e.message)}<br><br><button class="aslBtn aslGhost" onclick="AI_SALES_LOOP.close()">关闭</button></div>`}}
function open(){document.getElementById('aslModal').style.display='flex';render()}function close(){document.getElementById('aslModal').style.display='none'}
function boot(){css();if(!document.getElementById('aslBtn')){let b=document.createElement('button');b.id='aslBtn';b.textContent='↻ Sales Loop';b.onclick=open;document.body.appendChild(b)}if(!document.getElementById('aslModal')){let m=document.createElement('div');m.id='aslModal';m.innerHTML='<div class="box" id="aslBody"></div>';m.onclick=e=>{if(e.target===m)close()};document.body.appendChild(m)}}
window.AI_SALES_LOOP={open,close,render,execute,run};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();