/* AI TRADE — CEO Daily Brief 1.0 */
(()=>{
const CFG=()=>window.AITRADE_CLOUD_CONFIG||{};
async function client(){if(!window.supabase){await new Promise((res,rej)=>{let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=res;s.onerror=rej;document.head.appendChild(s)})}let c=CFG();return window.supabase.createClient(c.url,c.anonKey,{auth:{persistSession:true,autoRefreshToken:true}})}
async function run(){let sb=await client(),{data:{session}}=await sb.auth.getSession();if(!session)throw new Error('请先登录 AI TRADE 云同步');let c=CFG(),r=await fetch(`${c.url}/functions/v1/ceo-daily-brief-runner`,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${session.access_token}`,'apikey':c.anonKey},body:'{}'});let x=await r.json();if(!r.ok||!x.ok)throw new Error(x.detail||x.error||'日报生成失败');return x}
function esc(x){return String(x??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function css(){if(document.getElementById('cdbStyle'))return;let s=document.createElement('style');s.id='cdbStyle';s.textContent=`#cdbBtn{position:fixed;right:112px;bottom:110px;z-index:9996;border:0;border-radius:999px;padding:10px 14px;background:#0f172a;color:#fff;font:800 12px Arial;box-shadow:0 8px 25px #0002}#cdbModal{position:fixed;inset:0;z-index:10080;background:#0f172a80;display:none;align-items:center;justify-content:center;padding:14px}#cdbModal .box{width:min(1000px,97vw);max-height:92vh;overflow:auto;background:#f8fafc;border-radius:18px;padding:16px}.cdbTop{display:flex;justify-content:space-between;gap:10px;align-items:center}.cdbHero{background:linear-gradient(135deg,#0f172a,#334155);color:#fff;border-radius:16px;padding:16px;margin:12px 0}.cdbGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.cdbCard{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:11px}.cdbBig{font-size:22px;font-weight:900;margin-top:4px}.cdbList{background:#fff;border:1px solid #e5e7eb;border-radius:12px;overflow:hidden}.cdbItem{padding:11px;border-bottom:1px solid #eef2f7}.cdbItem:last-child{border-bottom:0}.cdbMeta{font-size:10px;color:#64748b}.cdbBtn{border:0;border-radius:9px;padding:9px 11px;background:#0f172a;color:#fff;font-weight:800}.cdbGhost{background:#eef2ff;color:#3730a3}@media(max-width:720px){#cdbBtn{display:none!important}.cdbGrid{grid-template-columns:1fr 1fr}.cdbTop{align-items:flex-start}}`;document.head.appendChild(s)}
function render(x){let b=document.getElementById('cdbBody');if(!b)return;let d=x.brief||{},m=d.metrics||{},acc=x.acceptance||{};b.innerHTML=`<div class="cdbTop"><div><h2 style="margin:0">CEO Daily Brief 1.0</h2><div class="cdbMeta">把今天的销售数据、优先动作、风险和机会压缩成一页。</div></div><div><button class="cdbBtn" onclick="AI_CEO_BRIEF.execute()">刷新</button> <button class="cdbBtn cdbGhost" onclick="AI_CEO_BRIEF.close()">关闭</button></div></div><div class="cdbHero"><div style="font-size:11px;opacity:.75">今日结论</div><div style="font-size:20px;font-weight:900;margin-top:5px">${esc(d.headline||'暂无结论')}</div><div style="font-size:11px;margin-top:8px;opacity:.8">Production Acceptance：${esc(acc.overall_status||'未运行')}</div></div><div class="cdbGrid"><div class="cdbCard"><div class="cdbMeta">新增 Leads</div><div class="cdbBig">${m.new_leads||0}</div></div><div class="cdbCard"><div class="cdbMeta">高ICP Leads</div><div class="cdbBig">${m.high_icp_leads||0}</div></div><div class="cdbCard"><div class="cdbMeta">新决策人</div><div class="cdbBig">${m.new_decision_makers||0}</div></div><div class="cdbCard"><div class="cdbMeta">已验证联系人</div><div class="cdbBig">${m.verified_contacts||0}</div></div><div class="cdbCard"><div class="cdbMeta">客户回复</div><div class="cdbBig">${m.replies||0}</div></div><div class="cdbCard"><div class="cdbMeta">新RFQ</div><div class="cdbBig">${m.rfq_total||0}</div></div><div class="cdbCard"><div class="cdbMeta">待审批草稿</div><div class="cdbBig">${m.mail_drafts||0}</div></div><div class="cdbCard"><div class="cdbMeta">需人工审批动作</div><div class="cdbBig">${m.approval_needed||0}</div></div></div><h3>今天最重要的动作</h3><div class="cdbList">${(d.priorities||[]).map((p,i)=>`<div class="cdbItem"><b>${i+1}. ${esc(p.title)}</b><div class="cdbMeta">${esc(p.priority||'normal')} · ${p.approval?'需要 Human Approval':'可自动执行'} · ${esc(p.type||'')}</div></div>`).join('')||'<div class="cdbItem">暂无待处理动作。</div>'}</div><h3>机会</h3><div class="cdbList">${(d.opportunities||[]).map(o=>`<div class="cdbItem"><b>${esc(o.from||'客户')}</b> · ${esc(o.subject||'RFQ')}<div class="cdbMeta">型号 ${esc(o.model||'待识别')} · 数量 ${esc(o.quantity||'-')} · 目标价 ${esc(o.currency||'')} ${esc(o.target_price||'-')}</div></div>`).join('')||'<div class="cdbItem">今天暂无新RFQ机会。</div>'}</div><h3>风险</h3><div class="cdbList">${(d.risks||[]).map(r=>`<div class="cdbItem"><b>${esc(r.title)}</b><div class="cdbMeta">${esc(r.severity||'warning')} · ${esc(r.detail||'')}</div></div>`).join('')||'<div class="cdbItem">当前没有开放系统风险。</div>'}</div>`}
async function execute(){let b=document.getElementById('cdbBody');if(b)b.innerHTML='<div style="padding:30px;text-align:center">正在生成今日经营简报…</div>';try{render(await run())}catch(e){b.innerHTML=`<div style="padding:20px;color:#b42318">${esc(e.message)}<br><br><button class="cdbBtn cdbGhost" onclick="AI_CEO_BRIEF.close()">关闭</button></div>`}}
function open(){document.getElementById('cdbModal').style.display='flex';execute()}function close(){document.getElementById('cdbModal').style.display='none'}
function boot(){css();if(!document.getElementById('cdbBtn')){let b=document.createElement('button');b.id='cdbBtn';b.textContent='☀ 今日简报';b.onclick=open;document.body.appendChild(b)}if(!document.getElementById('cdbModal')){let m=document.createElement('div');m.id='cdbModal';m.innerHTML='<div class="box" id="cdbBody"></div>';m.onclick=e=>{if(e.target===m)close()};document.body.appendChild(m)}}
window.AI_CEO_BRIEF={open,close,execute,run};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();