/* AI TRADE Command Center 2.0 */
(()=>{
const DBK='aitrade_full59_v1', SDK='aitrade_sdr2_v1', DMK='aitrade_decision_makers_v1', PBK='ai_trade_pricing_brain_v2', QBK='ai_trade_quotes_v2', FUK='aitrade_followup_v2';
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')||d}catch{return d}};
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
function data(){return {db:get(DBK,{customers:[],signals:[],quotes:[],orders:[],leads:[]}),sdr:get(SDK,{campaigns:[],queue:[]}),dm:get(DMK,{people:[]}),quotes:get(QBK,[]),follow:get(FUK,{tasks:[],reorders:[]}),pricing:get(PBK,{})}}
function cprob(c,signals){let s=(signals||[]).filter(x=>x.customerId===c.id).reduce((a,x)=>a+(+x.points||0),0);return Math.max(5,Math.min(95,Math.round((+c.icp||60)*.45+s*.55)))}
function actions(){let {db,sdr,quotes,follow}=data(), out=[];
 for(const c of db.customers||[]){let p=cprob(c,db.signals||[]), stage=c.stage||'prospect';if(stage==='rfq')out.push({priority:100,type:'RFQ',company:c.company,customerId:c.id,action:'生成报价并提交审批',why:'客户已进入RFQ阶段'});else if(stage==='sample')out.push({priority:88,type:'样品',company:c.company,customerId:c.id,action:'跟进样品测试反馈',why:'样品阶段需要主动推进'});else if(stage==='negotiation')out.push({priority:92,type:'谈判',company:c.company,customerId:c.id,action:'确认价格/交期/付款条件',why:'已进入商务谈判'});else if(p>=80)out.push({priority:84,type:'高意向',company:c.company,customerId:c.id,action:'人工优先介入',why:`成交概率 ${p}%`});}
 for(const q of quotes||[]){if(q.humanApproval==='required' && q.status!=='approved')out.push({priority:96,type:'审批',company:q.customer||'-',action:'审核报价风险项',why:(q.flags||[]).join(' / ')||'Human Approval required'});}
 for(const q of sdr.queue||[]){if(q.status==='等待发送'||q.status==='待发送')out.push({priority:72,type:'开发',company:q.company||'-',action:'审核并发送开发邮件',why:q.step||'AI SDR队列'});}
 for(const t of follow.tasks||[]){if(t.status!=='done')out.push({priority:70,type:'跟进',company:t.company||'-',action:t.action||t.title||'执行跟进',why:t.reason||'Follow-up Agent'});}
 return out.sort((a,b)=>b.priority-a.priority);
}
function stats(){let {db,sdr,quotes,follow}=data(), hot=(db.customers||[]).filter(c=>cprob(c,db.signals||[])>=80).length, rfq=(db.customers||[]).filter(c=>c.stage==='rfq').length, appr=(quotes||[]).filter(q=>q.humanApproval==='required'&&q.status!=='approved').length, wait=(sdr.queue||[]).filter(q=>q.status==='等待发送'||q.status==='待发送').length, reorder=(follow.reorders||[]).filter(x=>x.status!=='done').length, pipeline=(db.quotes||[]).reduce((a,q)=>a+(+q.total||0),0);return {hot,rfq,appr,wait,reorder,pipeline};}
function desktop(){let nav=document.getElementById('nav'),main=document.querySelector('main');if(!nav||!main||document.getElementById('command'))return;
 let btn=document.createElement('button');btn.dataset.p='command';btn.innerHTML='⌘ <span>Command Center 2.0</span>';nav.insertBefore(btn,nav.firstChild.nextSibling);
 let sec=document.createElement('section');sec.id='command';sec.className='page';main.insertBefore(sec,main.firstChild.nextSibling);
 btn.onclick=()=>{document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('on'));btn.classList.add('on');document.querySelectorAll('.page').forEach(x=>x.classList.remove('on'));sec.classList.add('on');renderDesktop()};renderDesktop();}
function renderDesktop(){let sec=document.getElementById('command');if(!sec)return;let s=stats(),a=actions(),{db}=data();sec.innerHTML=`<div class="top"><div><h1>Command Center 2.0</h1><div class="sub">每天只看这一页：高意向、RFQ、报价审批、待发送、复购和今日下一步动作。</div></div><div class="badge">● AI Action Hub</div></div><div class="grid4">${[['高意向客户',s.hot],['RFQ',s.rfq],['待审批报价',s.appr],['待发送',s.wait]].map(x=>`<div class="card kpi"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}</div><div class="two" style="margin-top:10px"><div class="card"><b>今日行动队列</b>${a.slice(0,12).map(x=>`<div class="item"><div style="display:flex;justify-content:space-between;gap:8px"><b>${esc(x.company)}</b><span class="tag ${x.priority>=90?'hot':x.priority>=80?'warn':'ok'}">${esc(x.type)}</span></div><div>${esc(x.action)}</div><small>${esc(x.why)}</small></div>`).join('')||'<div class="item">暂无待办</div>'}</div><div class="card"><b>销售健康度</b><div class="item">复购待办：<b>${s.reorder}</b></div><div class="item">报价管道金额：<b>${s.pipeline.toFixed(0)}</b></div><div class="item">客户总数：<b>${(db.customers||[]).length}</b></div><div class="item">Lead候选：<b>${(db.leads||[]).length}</b></div></div></div>`;}
function mobile(){if(!document.getElementById('home'))return;let old=window.M&&window.M.renderHome;const inject=()=>{let home=document.getElementById('home');if(!home)return;let s=stats(),a=actions();let block=document.createElement('div');block.id='mobileCommandCenter';block.innerHTML=`<div class="hero"><h1>Command Center 2.0</h1><p>今天只处理最重要的客户动作。</p></div><div class="grid"><div class="kpi"><small>高意向</small><b>${s.hot}</b></div><div class="kpi"><small>RFQ</small><b>${s.rfq}</b></div><div class="kpi"><small>待审批</small><b>${s.appr}</b></div><div class="kpi"><small>待发送</small><b>${s.wait}</b></div></div><h3 class="sectionTitle">今日行动</h3>${a.slice(0,8).map(x=>`<div class="item"><div class="row"><b>${esc(x.company)}</b><span class="tag ${x.priority>=90?'hot':x.priority>=80?'warn':'ok'}">${esc(x.type)}</span></div><div>${esc(x.action)}</div><div class="muted">${esc(x.why)}</div></div>`).join('')||'<div class="item">暂无待办</div>'}`;home.prepend(block)};setTimeout(inject,250);}
function boot(){desktop();mobile();}
window.AITRADE_COMMAND={stats,actions,renderDesktop};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();