(()=>{
const CORE='aitrade_full59_v1', KEY='aitrade_crm_followup_v2';
const STAGES=['prospect','contacted','replied','qualified','rfq','sample','negotiation','won','reorder','lost'];
const LABEL={prospect:'潜客',contacted:'已开发',replied:'已回复',qualified:'已确认需求',rfq:'询价',sample:'样品',negotiation:'谈判',won:'成交',reorder:'复购',lost:'流失'};
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
function core(){try{return JSON.parse(localStorage.getItem(CORE)||'null')||{customers:[],signals:[],quotes:[],orders:[]}}catch{return{customers:[],signals:[],quotes:[],orders:[]}}}
function state(){try{return JSON.parse(localStorage.getItem(KEY)||'null')||{tasks:[],history:[],settings:{staleDays:14,reorderDays:45},updatedAt:null}}catch{return{tasks:[],history:[],settings:{staleDays:14,reorderDays:45},updatedAt:null}}}
let st=state();
function save(){st.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(st));window.AITRADE_CLOUD?.push?.()}
function customerSignals(db,c){return (db.signals||[]).filter(x=>x.customerId===c.id)}
function inferStage(db,c){let cur=c.stage||'prospect', sigs=customerSignals(db,c), txt=sigs.map(x=>(x.type||'')+' '+(x.note||'')).join(' ').toLowerCase();let q=(db.quotes||[]).filter(x=>x.customerId===c.id||x.company===c.company), o=(db.orders||[]).filter(x=>x.customerId===c.id||x.company===c.company||x.customer===c.company);
 if(o.length){let recent=o.sort((a,b)=>new Date(b.createdAt||b.date||0)-new Date(a.createdAt||a.date||0))[0];let d=(Date.now()-new Date(recent.createdAt||recent.date||0).getTime())/864e5;return d>=st.settings.reorderDays?'reorder':'won'}
 if(q.some(x=>['approved','sent','已批准','已发送'].includes(x.status))) return 'negotiation';
 if(/sample|muestra/.test(txt)) return 'sample';
 if(/rfq|quote|price|precio|cotiz/.test(txt)) return 'rfq';
 if(/meeting|qualified|需求确认|规格确认/.test(txt)) return 'qualified';
 if(/reply|回复/.test(txt)) return 'replied';
 return cur;
}
function autoAdvance(){let db=core(),n=0;for(const c of db.customers||[]){let next=inferStage(db,c);if(next!==c.stage&&STAGES.indexOf(next)>STAGES.indexOf(c.stage||'prospect')){st.history.push({customerId:c.id,company:c.company,from:c.stage||'prospect',to:next,at:new Date().toISOString(),reason:'Auto rule'});c.stage=next;n++}}if(n)localStorage.setItem(CORE,JSON.stringify(db));generateTasks(db);save();return n}
function lastActivity(db,c){let dates=[];(db.signals||[]).filter(x=>x.customerId===c.id).forEach(x=>dates.push(x.createdAt));(db.quotes||[]).filter(x=>x.customerId===c.id||x.company===c.company).forEach(x=>dates.push(x.createdAt));(db.orders||[]).filter(x=>x.customerId===c.id||x.company===c.company||x.customer===c.company).forEach(x=>dates.push(x.createdAt||x.date));return dates.filter(Boolean).sort().pop()||c.updatedAt||c.createdAt||new Date(0).toISOString()}
function recommendation(db,c){let stage=c.stage||'prospect',days=(Date.now()-new Date(lastActivity(db,c)).getTime())/864e5;if(stage==='prospect')return{action:'发送首封开发',due:0,priority:'normal'};if(stage==='contacted')return{action:days>=3?'D3 跟进':'等待客户回复',due:Math.max(0,3-days),priority:'normal'};if(stage==='replied')return{action:'24小时内确认需求 + 推荐Top 3产品',due:0,priority:'high'};if(stage==='qualified')return{action:'生成报价或样品方案',due:0,priority:'high'};if(stage==='rfq')return{action:'生成AI报价并提交审批',due:0,priority:'urgent'};if(stage==='sample')return{action:days>=5?'跟进样品反馈':'等待样品测试',due:Math.max(0,5-days),priority:'high'};if(stage==='negotiation')return{action:days>=3?'谈判跟进：价格/交期/付款条件':'等待客户反馈',due:Math.max(0,3-days),priority:'urgent'};if(stage==='won')return{action:'等待复购窗口',due:Math.max(0,st.settings.reorderDays-days),priority:'normal'};if(stage==='reorder')return{action:'启动复购开发：库存/新品/补单',due:0,priority:'high'};return{action:'人工复盘',due:0,priority:'normal'}}
function generateTasks(db=core()){let open=new Map((st.tasks||[]).filter(t=>t.status!=='done').map(t=>[t.customerId+'|'+t.action,t]));for(const c of db.customers||[]){if(c.stage==='lost')continue;let r=recommendation(db,c),key=c.id+'|'+r.action;if(!open.has(key)){st.tasks.push({id:'T'+Date.now()+Math.random().toString(36).slice(2,6),customerId:c.id,company:c.company,stage:c.stage||'prospect',action:r.action,priority:r.priority,dueAt:new Date(Date.now()+r.due*864e5).toISOString(),status:'open',createdAt:new Date().toISOString()})}}}
function done(id){let t=st.tasks.find(x=>x.id===id);if(t){t.status='done';t.doneAt=new Date().toISOString();save();renderDesktop()}}
function stats(db){let groups={};STAGES.forEach(s=>groups[s]=0);(db.customers||[]).forEach(c=>groups[c.stage||'prospect']=(groups[c.stage||'prospect']||0)+1);return groups}
function renderDesktop(){let db=core();generateTasks(db);let crm=document.getElementById('crm');if(crm){let g=stats(db),active=(st.tasks||[]).filter(x=>x.status==='open').sort((a,b)=>new Date(a.dueAt)-new Date(b.dueAt));crm.innerHTML=`<div class="top"><div><h1>CRM 2.0 / 销售状态机</h1><div class="sub">Lead → Contacted → Replied → Qualified → RFQ → Sample → Negotiation → Order → Reorder。购买信号、报价和订单会自动推进阶段。</div></div><button class="btn" onclick="AITRADE_CRM.autoAdvance()">运行自动推进</button></div><div class="grid4">${[['客户总数',(db.customers||[]).length],['RFQ',g.rfq||0],['谈判中',g.negotiation||0],['成交/复购',(g.won||0)+(g.reorder||0)]].map(x=>`<div class="card kpi"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}</div><div class="pipeline" style="margin-top:12px;grid-template-columns:repeat(5,1fr)">${STAGES.filter(s=>s!=='lost').map(s=>`<div class="col"><b>${LABEL[s]}</b><small> ${g[s]||0}</small>${(db.customers||[]).filter(c=>(c.stage||'prospect')===s).map(c=>`<div class="deal"><b>${esc(c.company)}</b><br><small>${esc(c.contact||'')} · ICP ${c.icp||'-'}</small></div>`).join('')}</div>`).join('')}</div><div class="card" style="margin-top:12px"><b>自动化规则</b><div class="item">客户回复 → Replied；确认需求/会议 → Qualified；询价/价格 → RFQ；样品 → Sample；已批准/已发送报价 → Negotiation；订单 → Won；到复购窗口 → Reorder。</div></div>`}
 let follow=document.getElementById('follow');if(follow){let tasks=(st.tasks||[]).filter(x=>x.status==='open').sort((a,b)=>new Date(a.dueAt)-new Date(b.dueAt));let reorders=(db.customers||[]).filter(c=>c.stage==='reorder');follow.innerHTML=`<div class="top"><div><h1>Follow-up Agent 2.0</h1><div class="sub">不再固定只看 D1/D3/D7/D14；根据客户阶段、最近活动、RFQ、样品、谈判和订单动态生成下一步动作。</div></div><button class="btn" onclick="AITRADE_CRM.regenerate()">重新计算任务</button></div><div class="grid4">${[['待办',tasks.length],['紧急',tasks.filter(x=>x.priority==='urgent').length],['高优先',tasks.filter(x=>x.priority==='high').length],['复购客户',reorders.length]].map(x=>`<div class="card kpi"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}</div><div class="two" style="margin-top:10px"><div class="card"><b>动态跟进任务</b>${tasks.slice(0,40).map(t=>`<div class="item"><div><b>${esc(t.company)}</b> · ${LABEL[t.stage]||t.stage}</div><div>${esc(t.action)}</div><small>${new Date(t.dueAt).toLocaleString()} · ${t.priority}</small><div style="margin-top:6px"><button class="btn g" onclick="AITRADE_CRM.done('${t.id}')">完成</button></div></div>`).join('')||'<div class="item">暂无任务</div>'}</div><div class="card"><b>Reorder Brain</b>${reorders.map(c=>`<div class="item"><b>${esc(c.company)}</b><br><small>已进入复购窗口</small><div>建议：库存补单 / 新品推荐 / 价格更新</div></div>`).join('')||'<div class="item">暂无复购客户</div>'}</div></div>`}}
function showMobile(title,html){let box=document.getElementById('sheetContent'),sheet=document.getElementById('sheet');if(box&&sheet){box.innerHTML=`<div class="row"><b style="font-size:19px">${title}</b><button class="btn secondary" onclick="M.closeSheet()">关闭</button></div>`+html;sheet.classList.add('on')}}
function mobileCRM(){let db=core(),g=stats(db);showMobile('CRM 2.0',`<div class="grid" style="margin-top:12px">${[['客户',(db.customers||[]).length],['RFQ',g.rfq||0],['谈判',g.negotiation||0],['成交/复购',(g.won||0)+(g.reorder||0)]].map(x=>`<div class="kpi"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}</div><h3 class="sectionTitle">销售阶段</h3>${STAGES.filter(s=>s!=='lost').map(s=>`<div class="item"><div class="row"><b>${LABEL[s]}</b><span class="tag">${g[s]||0}</span></div>${(db.customers||[]).filter(c=>(c.stage||'prospect')===s).slice(0,8).map(c=>`<div class="muted" style="margin-top:6px">${esc(c.company)}</div>`).join('')}</div>`).join('')}`)}
function mobileFollow(){let db=core();generateTasks(db);save();let tasks=st.tasks.filter(x=>x.status==='open').sort((a,b)=>new Date(a.dueAt)-new Date(b.dueAt));showMobile('Follow-up Agent 2.0',`<div class="grid" style="margin-top:12px"><div class="kpi"><small>待办</small><b>${tasks.length}</b></div><div class="kpi"><small>紧急</small><b>${tasks.filter(x=>x.priority==='urgent').length}</b></div></div><h3 class="sectionTitle">动态任务</h3>${tasks.slice(0,30).map(t=>`<div class="item"><div class="row"><b>${esc(t.company)}</b><span class="tag ${t.priority==='urgent'?'hot':t.priority==='high'?'warn':''}">${t.priority}</span></div><div>${esc(t.action)}</div><div class="muted">${LABEL[t.stage]||t.stage} · ${new Date(t.dueAt).toLocaleString()}</div></div>`).join('')||'<div class="item">暂无任务</div>'}`)}
function init(){autoAdvance();renderDesktop();if(window.M){window.M.showCRM=mobileCRM;window.M.showReorder=mobileFollow}setTimeout(()=>{if(window.M){window.M.showCRM=mobileCRM;window.M.showReorder=mobileFollow}},600)}
window.AITRADE_CRM={autoAdvance:()=>{let n=autoAdvance();renderDesktop();alert('自动推进 '+n+' 个客户阶段')},regenerate:()=>{st.tasks=(st.tasks||[]).filter(x=>x.status==='done');generateTasks(core());save();renderDesktop()},done,mobileCRM,mobileFollow,state:()=>st};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();