(()=>{
const STORE='aitrade_decision_makers_v2';
const VERIFIED=[
 {company:'Select Sound',name:'Alberto Mizrahi',role:'Co-Founder',confidence:99,status:'RocketReach + LinkedIn 双重验证',linkedin:'https://www.linkedin.com/in/alberto-mizrahi-373b5975',source:'RocketReach确认现任 Co-Founder；公开LinkedIn亦一致。工作邮箱已验证 Grade A，但不写入公开GitHub前端。',priority:'A+',contactStatus:'工作邮箱已验证(A)'},
 {company:'Viastara',name:'Eduardo Escalante',role:'CEO / Partner / Board Member',confidence:99,status:'RocketReach 已验证',linkedin:'https://www.linkedin.com/in/eduardo-escalante-a82a857',source:'RocketReach确认 Viastara CEO、Partner、Board Member；公司为墨西哥/拉美专业消费电子分销商。Viastara 域名邮箱存在有效记录，但首选邮箱需人工确认。',priority:'A+',contactStatus:'工作邮箱存在有效记录'},
 {company:'Stuffactory / STF',name:'Carlos González',role:'CEO / Founder',confidence:97,status:'公开媒体已验证',linkedin:'',source:'Milenio、Fast Company Mexico 公开采访均确认 Carlos González 为 STF/Stuffactory CEO 与创始人。',priority:'A+',contactStatus:'待联系人补全'},
 {company:'Stuffactory / STF',name:'Manuel Aurelio Gonzalez Diaz',role:'Gerente de Producto / Product Manager',confidence:85,status:'公开人员目录候选',linkedin:'',source:'公开企业人员目录显示其为 Stuffactory 产品经理；适合产品/OEM切入，但邮箱尚未验证。',priority:'A',contactStatus:'待邮箱验证'},
 {company:'Grupo Recse Internacional',name:'Humberto C Recobos R',role:'CEO',confidence:97,status:'LinkedIn公开资料已验证',linkedin:'https://mx.linkedin.com/in/humberto-c-recobos-r-4894b0259',source:'LinkedIn简介明确写明 CEO in Grupo Recse；公司公开页定位消费电子进口、出口、批发。',priority:'A+',contactStatus:'待邮箱验证'},
 {company:'Electromart',name:'Dr. Alfredo Ismael Román Masso',role:'Director General Electromart / Samurai',confidence:99,status:'官网直接验证',linkedin:'',source:'Electromart官网“Nosotros”直接署名 Director General，并公开批发/集装箱销售渠道。',priority:'A+',contactStatus:'官网有直接销售入口'},
 {company:'Electromart',name:'Ventas por Contenedor',role:'Container / Wholesale Sales',confidence:96,status:'官网直接销售渠道',linkedin:'',source:'Electromart官网公开“Ventas por Contenedor”及多名 mayoreo 销售人员，是无需付费数据源即可直接触达的采购/渠道入口。',priority:'A',contactStatus:'官网公开电话'},
 {company:'Mitzu / Kaiser',name:'Arturo Carreño Masso',role:'Director General',confidence:99,status:'Forbes Mexico 已验证',linkedin:'',source:'Forbes Mexico 2025专访明确确认 Arturo Carreño Masso 为 Mitzu 与 Kaiser Director General。',priority:'A+',contactStatus:'待邮箱验证'},
 {company:'Hi Tech Audio',name:'José Antonio Martínez',role:'Managing Director',confidence:96,status:'行业公开资料已验证',linkedin:'',source:'Voice-Acoustic/LinkedIn公开内容明确称 José Antonio Martínez 为 Hi Tech Audio Managing Director。',priority:'A+',contactStatus:'待邮箱验证'},
 {company:'Hi Tech Audio',name:'Galder Morán',role:'Product Manager',confidence:95,status:'行业公开资料已验证',linkedin:'',source:'Voice-Acoustic公开内容明确称 Galder Morán 为 Hi Tech Audio Product Manager，负责系统设计。',priority:'A',contactStatus:'待邮箱验证'},
 {company:'JLP TRADING',name:'Joaquín Bonavides Borobia',role:'职位待进一步确认',confidence:66,status:'确认在职',linkedin:'https://mx.linkedin.com/in/joaquinbonav',source:'LinkedIn确认任职 JLP TRADING；公司公开资料明确长期从中国、香港、台湾、韩国进口消费电子。',priority:'B',contactStatus:'先确认职位'},
 {company:'Aiwa Mexico',name:'David Iván Clemente Heredia',role:'职位待进一步确认',confidence:67,status:'确认在职',linkedin:'https://mx.linkedin.com/in/david-iv%C3%A1n-clemente-heredia-80105a69',source:'LinkedIn确认任职 Aiwa Mexico；公开页暂未显示当前职称。',priority:'B',contactStatus:'先确认职位'},
 {company:'Aiwa Mexico',name:'Fabian Friedmann',role:'职位待进一步确认',confidence:62,status:'公司员工公开名单',linkedin:'',source:'Aiwa Mexico LinkedIn公司页列为员工；当前职称需继续验证。',priority:'B',contactStatus:'先确认职位'},
 {company:'SHOP X',name:'Isidoro Sitton',role:'职位待确认',confidence:60,status:'确认在职',linkedin:'',source:'SHOP X LinkedIn公司页与公开LinkedIn目录均确认 Isidoro Sitton 就职 SHOP X；具体职称未公开。',priority:'B',contactStatus:'先确认职位'},
 {company:'Distribuciones Compupaz',name:'E-commerce Team',role:'E-commerce / Commercial Contact',confidence:78,status:'官网直接联系渠道',linkedin:'',source:'Compupaz官网公开 ecommerce@ 企业邮箱及门店/电商联系方式，但未公开采购负责人姓名。',priority:'B',contactStatus:'官网公开企业邮箱'},
 {company:'Intéligos',name:'Commercial Team',role:'Wholesale Technology Distributor Contact',confidence:78,status:'官网直接联系渠道',linkedin:'',source:'Intéligos官网明确为墨西哥技术批发分销商，并公开 contacto@ 企业邮箱和总机。',priority:'B',contactStatus:'官网公开企业邮箱'},
 {company:'Icon Case',name:'Wholesale Team',role:'Import / Wholesale Contact',confidence:82,status:'官网业务角色已验证',linkedin:'',source:'Icon Case官网明确“importadores directos / venta al mayoreo”，直接进口耳机、音箱等，公开批发询价入口但未披露负责人姓名。',priority:'A',contactStatus:'官网批发询价入口'}
];
function esc(s){return String(s??'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}
function load(){let d;try{d=JSON.parse(localStorage.getItem(STORE)||'null')}catch{};return d||{people:VERIFIED,updated:new Date().toISOString()}}
let data=load();
// merge new verified records into existing local data without deleting user edits
for(const v of VERIFIED){let i=data.people?.findIndex(p=>p.company===v.company&&p.name===v.name)??-1;if(i<0){data.people=data.people||[];data.people.push(v)}else data.people[i]={...data.people[i],...v}}
data.updated=new Date().toISOString();localStorage.setItem(STORE,JSON.stringify(data));
function syncBrain(){try{let raw=JSON.parse(localStorage.getItem('aitrade_full59_v1')||'null');if(!raw||!Array.isArray(raw.customers))return;for(const p of data.people.filter(x=>x.confidence>=90&&x.name&&!/Team|Ventas por/.test(x.name))){let c=raw.customers.find(x=>(x.company||'').toLowerCase().includes(p.company.split('/')[0].trim().toLowerCase()));if(c&&(!c.contact||/待确认|未知/.test(c.contact))){c.contact=p.name;c.role=p.role;c.linkedin=p.linkedin||c.linkedin;c.notes=(c.notes||'')+`\n[Decision Maker Engine] ${p.name} · ${p.role} · ${p.status}。`;}}localStorage.setItem('aitrade_full59_v1',JSON.stringify(raw));}catch(e){}}
function render(){let body=document.getElementById('dmRows');if(!body)return;let arr=data.people.slice().sort((a,b)=>b.confidence-a.confidence);body.innerHTML=arr.map(p=>`<tr><td><b>${esc(p.company)}</b></td><td><b>${esc(p.name)}</b><br><small>${esc(p.role)}</small></td><td><span class="tag ${p.confidence>=80?'ok':p.confidence>=60?'warn':''}">${p.confidence}%</span></td><td>${esc(p.status)}<br><small>${esc(p.contactStatus||'')}</small></td><td><span class="tag">${p.priority}</span></td><td>${p.linkedin?`<a href="${esc(p.linkedin)}" target="_blank">LinkedIn</a><br>`:''}<small>${esc(p.source)}</small></td><td>${p.confidence>=90?'<span class="tag ok">优先开发</span>':p.confidence>=80?'<span class="tag ok">可开发/补联系人</span>':'<span class="tag warn">继续验证职位</span>'}</td></tr>`).join('');let s=document.getElementById('dmStats');if(s){let a=data.people.filter(x=>x.confidence>=90).length,b=data.people.filter(x=>x.confidence>=80&&x.confidence<90).length,publicContact=data.people.filter(x=>/官网公开/.test(x.contactStatus||'')).length;s.innerHTML=[['A+高置信决策人',a],['A级可开发',b],['免费公开联系入口',publicContact],['RocketReach','1 credit；本月Lookup限额已达']].map(x=>`<div class="card kpi"><small>${x[0]}</small><b style="font-size:18px">${x[1]}</b></div>`).join('')}}
function init(){syncBrain();let nav=document.getElementById('nav'),main=document.querySelector('main');if(!nav||!main)return;let sec=document.getElementById('decisionmakers');if(!sec){let btn=document.createElement('button');btn.dataset.p='decisionmakers';btn.innerHTML='♟ <span>Decision Maker Engine</span>';let sdr=[...nav.querySelectorAll('button')].find(x=>x.dataset.p==='sdr');nav.insertBefore(btn,sdr||null);sec=document.createElement('section');sec.id='decisionmakers';sec.className='page';sec.innerHTML=`<div class="top"><div><h1>Decision Maker Engine</h1><div class="sub">Public Web 先识别公司与具体人 → 角色验证 → 高价值人选才使用付费联系人查询 → 回写 Customer Brain。</div></div><div class="badge">● Public-Web First</div></div><div class="grid4" id="dmStats"></div><div class="card" style="margin-top:10px"><div class="item"><b>执行规则：</b> ≥90 A+：优先开发；80–89 A：可开发并补联系人；60–79 B：继续验证职称；低于60不消耗额度。</div><div class="item warn"><b>隐私/安全：</b> RocketReach 验证出的非公开工作邮箱不会硬编码进公开 GitHub Pages。当前静态前端只存“已验证状态”；真正自动发信前需要迁移到私有云数据库/后端。</div></div><div class="card wrap" style="margin-top:10px"><table><thead><tr><th>公司</th><th>关键人/入口</th><th>置信度</th><th>状态</th><th>优先级</th><th>证据</th><th>Next Action</th></tr></thead><tbody id="dmRows"></tbody></table></div>`;main.insertBefore(sec,document.getElementById('sdr'));btn.onclick=()=>{document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('on'));btn.classList.add('on');document.querySelectorAll('.page').forEach(x=>x.classList.remove('on'));sec.classList.add('on');render()};}render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();