(()=>{
const STORE='aitrade_decision_makers_v1';
const VERIFIED=[
 {company:'Select Sound',name:'Alberto Mizrahi',role:'Co-Founder',confidence:95,status:'已验证决策人',linkedin:'https://mx.linkedin.com/in/alberto-mizrahi-373b5975',source:'LinkedIn公开资料：本人简介明确写明在 Select Sound 担任 Co-Fundador。',priority:'A'},
 {company:'Viastara',name:'Eduardo Escalante',role:'职位待确认',confidence:62,status:'候选关键人',linkedin:'https://www.linkedin.com/in/eduardo-escalante-a82a857',source:'LinkedIn公开资料确认现任 Viastara, LLC；公开页面未显示具体职位。',priority:'B'},
 {company:'JLP TRADING',name:'Joaquín Bonavides Borobia',role:'职位待确认',confidence:58,status:'候选关键人',linkedin:'https://mx.linkedin.com/in/joaquinbonav',source:'LinkedIn公开资料确认任职 JLP TRADING；公开页面未显示具体职位。',priority:'B'},
 {company:'Hi Tech Audio',name:'Karla Santiago',role:'物流/谈判背景，现职位待确认',confidence:66,status:'候选关键人',linkedin:'https://mx.linkedin.com/in/karlalizbethsantiagov',source:'LinkedIn公开资料确认任职 Hi Tech Audio；简介显示长期物流、谈判和规划经验。',priority:'B'},
 {company:'SHOP X',name:'Isidoro Sitton',role:'职位待确认',confidence:55,status:'候选关键人',linkedin:'https://mx.linkedin.com/pub/dir/Isidoro/%2B/mx-5955-%C3%81rea-metropolitana-de-Ciudad-de-M%C3%A9xico',source:'LinkedIn公开目录确认 Isidoro Sitton 就职 SHOP X；具体职位未公开显示。',priority:'C'},
 {company:'Distribuciones Compupaz',name:'Carlos Mary',role:'职位待确认',confidence:52,status:'候选关键人',linkedin:'https://www.linkedin.com/company/distribuciones-compupaz',source:'LinkedIn公司公开页员工列表包含 Carlos Mary；具体职位未公开显示。',priority:'C'}
];
function esc(s){return String(s??'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}
function load(){let d;try{d=JSON.parse(localStorage.getItem(STORE)||'null')}catch{};return d||{people:VERIFIED,updated:new Date().toISOString()}}
let data=load();if(!data.people?.length)data.people=VERIFIED;localStorage.setItem(STORE,JSON.stringify(data));
function syncSelectSound(){try{let raw=JSON.parse(localStorage.getItem('aitrade_full59_v1')||'null');if(!raw||!Array.isArray(raw.customers))return;let c=raw.customers.find(x=>(x.company||'').toLowerCase().includes('select sound'));if(c&&!c.contact){c.contact='Alberto Mizrahi';c.role='Co-Founder';c.linkedin='https://mx.linkedin.com/in/alberto-mizrahi-373b5975';c.notes=(c.notes||'')+'\n[Decision Maker Engine] 公开资料已验证：Alberto Mizrahi，Select Sound Co-Founder。';localStorage.setItem('aitrade_full59_v1',JSON.stringify(raw));}}catch(e){}}
function render(){let body=document.getElementById('dmRows');if(!body)return;body.innerHTML=data.people.map(p=>`<tr><td><b>${esc(p.company)}</b></td><td><b>${esc(p.name)}</b><br><small>${esc(p.role)}</small></td><td><span class="tag ${p.confidence>=80?'ok':p.confidence>=60?'warn':''}">${p.confidence}%</span></td><td>${esc(p.status)}</td><td><span class="tag">${p.priority}</span></td><td><a href="${esc(p.linkedin)}" target="_blank">LinkedIn</a><br><small>${esc(p.source)}</small></td><td>${p.confidence>=80?'<span class="tag ok">可进入人工开发</span>':'<span class="tag warn">先确认职位，再消耗联系人额度</span>'}</td></tr>`).join('');let s=document.getElementById('dmStats');if(s){let v=data.people.filter(x=>x.confidence>=80).length,b=data.people.filter(x=>x.confidence>=60&&x.confidence<80).length;s.innerHTML=[['已验证决策人',v],['B级候选',b],['联系人额度策略','仅高分后查询'],['RocketReach剩余额度','4 Email Lookup']].map(x=>`<div class="card kpi"><small>${x[0]}</small><b style="font-size:18px">${x[1]}</b></div>`).join('')}}
function init(){syncSelectSound();let nav=document.getElementById('nav'),main=document.querySelector('main');if(!nav||!main||document.getElementById('decisionmakers'))return;let btn=document.createElement('button');btn.dataset.p='decisionmakers';btn.innerHTML='♟ <span>Decision Maker Engine</span>';let sdr=[...nav.querySelectorAll('button')].find(x=>x.dataset.p==='sdr');nav.insertBefore(btn,sdr||null);let sec=document.createElement('section');sec.id='decisionmakers';sec.className='page';sec.innerHTML=`<div class="top"><div><h1>Decision Maker Engine</h1><div class="sub">只使用公开可验证信息。先找人、确认职位和相关性，再决定是否消耗 RocketReach/Lusha 额度查 Email / Phone。</div></div><div class="badge">● Public-Web First</div></div><div class="grid4" id="dmStats"></div><div class="card" style="margin-top:10px"><div class="item"><b>执行规则：</b> A级（≥80）→ 可进入人工开发/联系人补全；B级（60–79）→ 先确认职位；C级（<60）→ 暂不消耗付费额度。</div><div class="item warn"><b>RocketReach状态：</b> Person Search 仍受套餐限制；账户当前剩余 4 个 Standard Lookup，只在确认高价值具体人选后使用。</div></div><div class="card wrap" style="margin-top:10px"><table><thead><tr><th>公司</th><th>候选人</th><th>置信度</th><th>状态</th><th>优先级</th><th>公开证据</th><th>Next Action</th></tr></thead><tbody id="dmRows"></tbody></table></div>`;main.insertBefore(sec,document.getElementById('sdr'));btn.onclick=()=>{document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('on'));btn.classList.add('on');document.querySelectorAll('.page').forEach(x=>x.classList.remove('on'));sec.classList.add('on');render()};render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();