/* AI TRADE — Decision Maker Enrichment 3.0 */
(()=>{
const KEY='aitrade_decision_enrichment_v3', DBK='aitrade_full59_v1';
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')||d}catch{return d}};const put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function state(){return get(KEY,{enabled:true,lastRun:null,runs:0,enriched:0,candidates:[],errors:[]})}
function save(s){s.lastRun=new Date().toISOString();put(KEY,s);window.AITRADE_CLOUD?.push?.()}
function websiteOf(c){return c.website||c.url||c.companyWebsite||c.domain||''}
function needs(c){let role=String(c.role||c.title||'').toLowerCase(),contact=String(c.contact||'');return !contact||/待确认|未知|team|sales|commercial/i.test(contact)||!/owner|founder|ceo|director|purchas|procurement|buyer|product/i.test(role)}
async function client(){if(!window.supabase||!window.AITRADE_CLOUD_CONFIG?.url)return null;return window.supabase.createClient(window.AITRADE_CLOUD_CONFIG.url,window.AITRADE_CLOUD_CONFIG.anonKey,{auth:{persistSession:true,autoRefreshToken:true}})}
async function enrichOne(c){let sb=await client();if(!sb)throw new Error('Supabase client unavailable');let {data:{session}}=await sb.auth.getSession();if(!session)throw new Error('请先登录 AI TRADE 云同步');let website=websiteOf(c);if(!website)throw new Error('客户缺少官网，无法运行官网型决策人增强');let {data,error}=await sb.functions.invoke('decision-maker-enrichment-runner',{body:{company:c.company||c.name,website}});if(error)throw error;return data}
function merge(db,results,company){if(!Array.isArray(results))return 0;let added=0;let s=state();for(const r of results){let key=[company,r.person_name||'',r.email||'',r.source_url||''].join('|');if(!s.candidates.some(x=>x.key===key)){s.candidates.push({key,company,...r,addedAt:new Date().toISOString()});added++;}if(r.person_name&&r.confidence>=80){let c=(db.customers||[]).find(x=>String(x.company||x.name).toLowerCase()===String(company).toLowerCase());if(c&&needs(c)){c.contact=r.person_name;c.role=r.role||c.role;c.notes=(c.notes||'')+`\n[Decision Enrichment 3.0] ${r.person_name} · ${r.role||''} · confidence ${r.confidence}% · ${r.verification_status||''}`;if(r.email&&r.verification_status==='domain_mx_verified')c.email=r.email;}}}s.candidates=s.candidates.slice(-500);s.enriched+=added;save(s);put(DBK,db);return added}
async function run(limit=5){let s=state();if(!s.enabled)return s;let db=get(DBK,{customers:[]});let arr=(db.customers||[]).filter(c=>needs(c)&&websiteOf(c)).sort((a,b)=>(+b.icp||0)-(+a.icp||0)).slice(0,limit);for(const c of arr){try{s.runs++;let out=await enrichOne(c);merge(db,out?.results||[],c.company||c.name)}catch(e){s.errors.push({company:c.company||c.name,error:String(e?.message||e),at:new Date().toISOString()});s.errors=s.errors.slice(-50);save(s)}}return s}
function dashboard(){let s=state();return{enabled:s.enabled,lastRun:s.lastRun,runs:s.runs,enriched:s.enriched,verified:s.candidates.filter(x=>x.verification_status==='domain_mx_verified').length,high:s.candidates.filter(x=>(x.confidence||0)>=85).length,recent:s.candidates.slice(-20).reverse(),errors:s.errors.slice(-10).reverse()}}
window.DecisionEnrichment3={run,enrichOne,dashboard,state};setTimeout(()=>run(3),4500);
})();