/* AI TRADE v6.1 — simplified business-first navigation with working routes */
(()=>{
const D=()=>matchMedia('(min-width:901px)').matches,$=s=>document.querySelector(s);
const CORE={leads:'leads',customers:'customers',products:'products',selection:'selection',signals:'signals',memory:'memory',sdr:'sdr',aiinbox:'inbox',crm:'crm',quotes:'quotes',approval:'approval',orders:'orders',follow:'follow',feedback:'feedback',today:'today'};
const NATIVE={launch:'fplBtn',bootstrap:'rpbBtn',sales:'aslBtn',brief:'cdbBtn',google:'gpsBtn',gmail:'gmailOauthBtn',learning:'le3Btn',opportunity:'pobBtn',heal:'shBtn',acceptance:'patBtn',cloud:'cloudSyncBtn',alerts:'ancBtn',health:'hmBtn',revenue:'revIntelBtn',inboxlive:'ghuBtn',activate:'dacBtn',dispatcher:'dispatcherBtn'};
function nav(k,ic,cn,en){return `<button class="v5-nav" data-go="${k}"><span class="ic">${ic}</span>${cn}<small>${en}</small></button>`}
function toast(x){let t=$('#v6Toast');if(!t){t=document.createElement('div');t.id='v6Toast';Object.assign(t.style,{position:'fixed',left:'50%',bottom:'30px',transform:'translateX(-50%)',background:'#111827',color:'#fff',padding:'10px 15px',borderRadius:'999px',zIndex:'60000',fontSize:'12px',boxShadow:'0 10px 30px #0003'});document.body.appendChild(t)}t.textContent=x;clearTimeout(t._x);t._x=setTimeout(()=>t.remove(),2400)}
function triggerNative(k){const id=NATIVE[k],b=id&&document.getElementById(id);if(!b){toast('该功能正在加载，请刷新页面后重试');return false}b.click();return true}
function openCore(k){const p=CORE[k]||k;document.body.classList.add('v5-core-open');const legacy=$('#legacyAppV3>.app')||$('.app');if(legacy)legacy.style.display='grid';setTimeout(()=>{const b=document.querySelector(`#legacyAppV3 nav button[data-p="${p}"]`)||document.querySelector(`nav button[data-p="${p}"]`);if(b)b.click();else toast('业务页面未找到：'+p)},80)}
function closeCore(){document.body.classList.remove('v5-core-open')}
function modal(title,html){let m=$('#v6Modal');if(!m){m=document.createElement('div');m.id='v6Modal';m.style.cssText='position:fixed;inset:0;background:#0f172a73;z-index:59000;display:none;padding:5vh 5vw';m.innerHTML='<div style="max-width:1050px;margin:auto;background:#fff;border-radius:20px;padding:20px;max-height:90vh;overflow:auto;box-shadow:0 30px 80px #0004"><div style="display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #edf2f7;padding-bottom:12px"><h2 id="v6Title" style="margin:0"></h2><button id="v6Close" style="border:0;background:#eef3f8;border-radius:9px;width:36px;height:36px;font-size:20px">×</button></div><div id="v6Body"></div></div>';document.body.appendChild(m);m.querySelector('#v6Close').onclick=()=>m.style.display='none';m.onclick=e=>{if(e.target===m)m.style.display='none'}}m.querySelector('#v6Title').textContent=title;m.querySelector('#v6Body').innerHTML=html;m.style.display='block';return m}
function settings(){const items=[['google','G','Google 设置','OAuth / Pub/Sub / Gmail Watch'],['gmail','✉','Gmail','邮箱授权与发送'],['learning','🧠','学习引擎','自动学习国家、职位、产品和邮件表现'],['heal','🛠','自动修复','后台自愈与异常修复'],['health','⚙','系统健康','服务与任务运行状态'],['acceptance','✓','生产验收','Production Acceptance'],['feedback','∞','数据反哺','成交结果回写 AI'],['activate','⚡','数据激活','历史数据进入生产层'],['launch','🚦','上线中心','Production LIVE 进度']];let m=modal('系统设置',`<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:12px;padding:16px 0">${items.map(x=>`<button data-set="${x[0]}" style="text-align:left;border:1px solid #e0e9f3;background:#f8fbff;border-radius:14px;padding:16px;cursor:pointer;color:#173150"><div style="font-size:24px">${x[1]}</div><b style="display:block;margin:7px 0 4px">${x[2]}</b><small style="color:#72829a">${x[3]}</small></button>`).join('')}</div>`);m.querySelectorAll('[data-set]').forEach(b=>b.onclick=()=>{m.style.display='none';route(b.dataset.set)})}
function showMarket(){let db={};try{db=JSON.parse(localStorage.getItem('aitrade_full59_v1')||'{}')||{}}catch{}let leads=[...(db.leads||[])],customers=[...(db.customers||[])];try{let a=JSON.parse(localStorage.getItem('aitrade_autonomous_leads_v2')||'[]');if(Array.isArray(a))leads.push(...a)}catch{}const bag={};[...leads,...customers].forEach(x=>{let c=x.country||x.market||'未知';bag[c]=(bag[c]||0)+1});let rows=Object.entries(bag).sort((a,b)=>b[1]-a[1]);modal('市场分析',`<div style="padding:14px 0;color:#64748b">基于当前 Lead 与客户数据统计，不使用演示结果。</div><table style="width:100%;border-collapse:collapse"><thead><tr><th style="text-align:left;padding:10px;border-bottom:1px solid #e5e7eb">市场</th><th style="text-align:left;padding:10px;border-bottom:1px solid #e5e7eb">客户/Lead 数</th><th style="text-align:left;padding:10px;border-bottom:1px solid #e5e7eb">建议</th></tr></thead><tbody>${rows.length?rows.map(([c,n])=>`<tr><td style="padding:10px;border-bottom:1px solid #eef2f7"><b>${c}</b></td><td style="padding:10px;border-bottom:1px solid #eef2f7">${n}</td><td style="padding:10px;border-bottom:1px solid #eef2f7">${n>=5?'优先深挖':'继续补充样本'}</td></tr>`).join(''):'<tr><td colspan="3" style="padding:18px">暂无市场数据</td></tr>'}</tbody></table>`)}
function showCommunication(){let m=modal('沟通中心',`<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:12px;padding:16px 0"><button data-c="aiinbox" class="v6c">💬<b>AI收件箱</b><small>识别客户回复并回写 CRM</small></button><button data-c="sdr" class="v6c">✉<b>AI开发信</b><small>生成个性化开发内容</small></button><button data-c="gmail" class="v6c">G<b>Gmail</b><small>授权、发送与真实邮箱连接</small></button><button data-c="inboxlive" class="v6c">↩<b>Inbox Live</b><small>实时邮件监听</small></button><button data-c="follow" class="v6c">↻<b>跟进 / 复购</b><small>下一步动作与复购窗口</small></button><button data-c="crm" class="v6c">◇<b>CRM</b><small>查看客户销售阶段</small></button></div><style>.v6c{text-align:left;border:1px solid #e0e9f3;background:#f8fbff;border-radius:14px;padding:16px;cursor:pointer;font-size:23px;color:#173150}.v6c b,.v6c small{display:block;font-size:13px;margin-top:7px}.v6c small{font-size:11px;color:#72829a;font-weight:400}</style>`);m.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{m.style.display='none';route(b.dataset.c)})}
function showClose(){let m=modal('成交中心',`<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:12px;padding:16px 0">${[['quotes','💰','AI报价'],['approval','✓','人工审批'],['orders','▣','订单管理'],['follow','↻','跟进 / 复购'],['revenue','▥','收入分析'],['feedback','∞','数据反哺']].map(x=>`<button data-x="${x[0]}" style="text-align:left;border:1px solid #e0e9f3;background:#f8fbff;border-radius:14px;padding:17px;cursor:pointer;color:#173150;font-size:22px">${x[1]}<b style="display:block;font-size:13px;margin-top:7px">${x[2]}</b></button>`).join('')}</div>`);m.querySelectorAll('[data-x]').forEach(b=>b.onclick=()=>{m.style.display='none';route(b.dataset.x)})}
function route(k){if(k==='home'||k==='today'){document.body.classList.remove('v5-core-open');window.scrollTo({top:0,behavior:'smooth'});return}if(k==='settings')return settings();if(k==='market')return showMarket();if(k==='communication')return showCommunication();if(k==='close')return showClose();if(CORE[k])return openCore(k);if(NATIVE[k])return triggerNative(k);toast('功能入口未配置：'+k)}
function simplifyHome(){const flow=$('#aiTradeV5 .v5-flow');if(flow)flow.remove();const quick=$('#aiTradeV5 .v5-quick');if(quick){quick.innerHTML=`<button data-v6="leads"><span class="ico">🎯</span><b>找新客户</b></button><button data-v6="customers"><span class="ico">＋</span><b>添加客户</b></button><button data-v6="sdr"><span class="ico">✉</span><b>AI联系客户</b></button><button data-v6="quotes"><span class="ico">💰</span><b>创建报价</b></button>`;quick.style.gridTemplateColumns='repeat(4,1fr)';quick.querySelectorAll('[data-v6]').forEach(b=>b.onclick=()=>route(b.dataset.v6))}let h=$('#aiTradeV5 .v5-head h1');if(h)h.textContent='今日工作台';let p=$('#aiTradeV5 .v5-head p');if(p)p.textContent='今天只处理最重要的客户、跟进、回复和成交机会。'}
function apply(){if(!D())return;let side=$('#aiTradeV5 .v5-side');if(!side)return;const user=side.querySelector('.v5-user')?.outerHTML||'';side.innerHTML=`<div class="v5-logo"><div class="v5-mark">AI</div><div><b>AI TRADE</b><small>Your AI Export Sales Team</small></div></div>${nav('home','⌂','今日工作台','Today')}${nav('leads','🎯','找客户','Find')}${nav('customers','👥','客户','CRM')}${nav('products','📦','产品','Products')}${nav('communication','💬','沟通','Engage')}${nav('close','💰','成交','Close')}<div class="v5-section">智能分析</div>${nav('market','▥','市场分析','Market')}${nav('opportunity','◆','产品机会','Opportunity')}<div class="v5-section">系统</div>${nav('settings','⚙','系统设置','Settings')}${user}`;side.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>route(b.dataset.go));simplifyHome();let back=$('.v5-core-back');if(back)back.onclick=closeCore}
function boot(){let n=0,t=setInterval(()=>{n++;if($('#aiTradeV5 .v5-side')){clearInterval(t);apply()}else if(n>40)clearInterval(t)},250)}
window.AI_TRADE_V6={route,apply,openCore,settings};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();