(()=>{
const STORE='aitrade_gmail_bridge_v1';
const SDR='aitrade_sdr2_v1';
const CORE='aitrade_full59_v1';
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
function load(){try{return JSON.parse(localStorage.getItem(STORE)||'null')||{queue:[],replies:[],settings:{provider:'Gmail',mode:'human-approval'},updatedAt:null}}catch{return{queue:[],replies:[],settings:{provider:'Gmail',mode:'human-approval'},updatedAt:null}}}
let state=load();
function save(){state.updatedAt=new Date().toISOString();localStorage.setItem(STORE,JSON.stringify(state));render();window.AITRADE_CLOUD?.push?.()}
function syncFromSDR(){let s;try{s=JSON.parse(localStorage.getItem(SDR)||'null')}catch{};let seq=s?.sequences||s?.campaigns||[];if(!Array.isArray(seq))return 0;let n=0;for(const c of seq){let steps=c.steps||c.sequence||[];for(const st of steps){let approved=st.approved===true||st.status==='approved'||st.status==='待发送';if(!approved)continue;let key=[c.id||c.customerId||c.company,st.day||st.offset||'',st.subject||'',st.body||''].join('|');if(state.queue.some(x=>x.key===key))continue;state.queue.push({id:'G'+Date.now()+Math.random().toString(36).slice(2,6),key,customerId:c.customerId||'',company:c.company||'',contact:c.contact||'',to:c.email||st.to||'',subject:st.subject||'',body:st.body||'',day:st.day||'',status:'待创建Gmail草稿',createdAt:new Date().toISOString(),gmailDraftId:null,sentAt:null,error:null});n++}}
if(n)save();return n}
function markDraft(id,draftId){let x=state.queue.find(q=>q.id===id);if(!x)return;x.gmailDraftId=draftId||x.gmailDraftId;x.status='Gmail草稿已创建';save()}
function markSent(id){let x=state.queue.find(q=>q.id===id);if(!x)return;x.status='已发送';x.sentAt=new Date().toISOString();save()}
function markFailed(id,msg){let x=state.queue.find(q=>q.id===id);if(!x)return;x.status='失败';x.error=msg||'Unknown';save()}
function addReply(r){state.replies.push({id:'R'+Date.now(),messageId:r.messageId||'',threadId:r.threadId||'',from:r.from||'',company:r.company||'',customerId:r.customerId||'',subject:r.subject||'',body:r.body||'',intent:r.intent||'待AI识别',receivedAt:r.receivedAt||new Date().toISOString(),synced:false});save()}
function syncReplyToCore(id){let r=state.replies.find(x=>x.id===id);if(!r||r.synced)return;let db;try{db=JSON.parse(localStorage.getItem(CORE)||'null')}catch{};if(!db)return;let c=db.customers?.find(x=>x.id===r.customerId)||(r.company?db.customers?.find(x=>(x.company||'').toLowerCase()===(r.company||'').toLowerCase()):null);if(c){c.notes=(c.notes||'')+`\n[Gmail Reply ${new Date(r.receivedAt).toLocaleString()}] ${r.subject||''} ${r.body||''}`;db.signals=db.signals||[];let text=(r.subject+' '+r.body).toLowerCase(),type=/quote|price|precio|cotiz/.test(text)?'RFQ':/sample|muestra/.test(text)?'Sample':/meeting|call|reun/.test(text)?'Meeting':'Reply';let pts=type==='RFQ'?18:type==='Sample'?15:type==='Meeting'?12:8;db.signals.push({id:'S'+Date.now(),customerId:c.id,type,points:pts,note:'Gmail自动回写',createdAt:new Date().toISOString()});if(type==='RFQ')c.stage='rfq';else if(type==='Sample')c.stage='sample';else if(c.stage==='prospect')c.stage='contacted';localStorage.setItem(CORE,JSON.stringify(db));r.synced=true;save()}}
function render(){let sec=document.getElementById('gmailbridge');if(!sec)return;let q=state.queue||[],rp=state.replies||[];document.getElementById('gbStats').innerHTML=[['待处理',q.filter(x=>!['已发送','失败'].includes(x.status)).length],['Gmail草稿',q.filter(x=>x.status==='Gmail草稿已创建').length],['已发送',q.filter(x=>x.status==='已发送').length],['待回写回复',rp.filter(x=>!x.synced).length]].map(x=>`<div class="card kpi"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('');document.getElementById('gbQueue').innerHTML=q.map(x=>`<tr><td><b>${esc(x.company||'-')}</b><br><small>${esc(x.contact||'')}</small></td><td>${esc(x.to||'待补Email')}</td><td>${esc(x.day||'-')}</td><td>${esc(x.subject||'-')}</td><td><span class="tag ${x.status==='已发送'?'ok':x.status==='失败'?'hot':'warn'}">${esc(x.status)}</span></td><td>${x.gmailDraftId?`<small>${esc(x.gmailDraftId)}</small>`:'-'}</td></tr>`).join('')||'<tr><td colspan="6">暂无 Gmail 队列。先在 AI SDR 2.0 审批开发序列，再点击“同步已批准邮件”。</td></tr>';document.getElementById('gbReplies').innerHTML=rp.map(r=>`<tr><td>${esc(r.from)}</td><td>${esc(r.company||'-')}</td><td>${esc(r.subject)}</td><td>${esc(r.intent)}</td><td>${r.synced?'<span class="tag ok">已回写</span>':`<button class="btn g" onclick="AITRADE_GMAIL.syncReply('${r.id}')">回写Customer Brain</button>`}</td></tr>`).join('')||'<tr><td colspan="5">暂无已导入回复。</td></tr>'}
function init(){let nav=document.getElementById('nav'),main=document.querySelector('main');if(!nav||!main||document.getElementById('gmailbridge'))return;let btn=document.createElement('button');btn.dataset.p='gmailbridge';btn.innerHTML='✉ <span>Gmail Bridge</span>';let inbox=[...nav.querySelectorAll('button')].find(x=>x.dataset.p==='inbox');nav.insertBefore(btn,inbox||null);let sec=document.createElement('section');sec.id='gmailbridge';sec.className='page';sec.innerHTML=`<div class="top"><div><h1>Gmail Bridge</h1><div class="sub">AI SDR 审批 → Gmail草稿/发送队列 → 客户回复 → Customer Memory / Buying Signals / CRM。Gmail凭证不存放在公开网页。</div></div><div class="badge">● Human Approval Gate</div></div><div class="grid4" id="gbStats"></div><div class="toolbar"><button class="btn" onclick="AITRADE_GMAIL.syncSDR()">同步已批准邮件</button><span class="sub">真正创建 Gmail 草稿/发送由授权 Gmail 通道执行；网页只维护业务队列和状态。</span></div><div class="card wrap"><table><thead><tr><th>客户</th><th>收件人</th><th>节奏</th><th>主题</th><th>状态</th><th>Draft ID</th></tr></thead><tbody id="gbQueue"></tbody></table></div><div class="card wrap" style="margin-top:10px"><b>客户回复回写</b><table><thead><tr><th>From</th><th>公司</th><th>主题</th><th>AI意图</th><th>动作</th></tr></thead><tbody id="gbReplies"></tbody></table></div>`;main.insertBefore(sec,document.getElementById('inbox'));btn.onclick=()=>{document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('on'));btn.classList.add('on');document.querySelectorAll('.page').forEach(x=>x.classList.remove('on'));sec.classList.add('on');render()};render()}
window.AITRADE_GMAIL={syncSDR:()=>{let n=syncFromSDR();alert('已同步到 Gmail 队列：'+n+' 封');render()},markDraft,markSent,markFailed,addReply,syncReply:syncReplyToCore,state:()=>state};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();