/* AI TRADE — Gmail OAuth Production Bridge UI */
(()=>{
const FN='gmail-oauth-bridge', WORKER='mail-execution-runner';
const cfg=()=>window.AITRADE_CLOUD_CONFIG||{};
async function client(){if(!window.supabase){await new Promise((res,rej)=>{let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=res;s.onerror=rej;document.head.appendChild(s)})}let c=cfg();return window.supabase.createClient(c.url,c.anonKey,{auth:{persistSession:true,autoRefreshToken:true}})}
async function call(fn,body){let sb=await client(),{data:{session}}=await sb.auth.getSession();if(!session)throw new Error('请先登录 AI TRADE 云同步');let r=await fetch(`${cfg().url}/functions/v1/${fn}`,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${session.access_token}`},body:JSON.stringify(body)});let x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||x.detail||'request_failed');return x}
async function status(){return call(FN,{action:'status'})}
async function connect(){let redirect_after=location.href.split('#')[0];let x=await call(FN,{action:'start',redirect_after});if(x.authorization_url)location.href=x.authorization_url}
async function process(){return call(WORKER,{action:'process',limit:5})}
function style(){if(document.getElementById('gmailOauthStyle'))return;let s=document.createElement('style');s.id='gmailOauthStyle';s.textContent=`#gmailOauthBtn{position:fixed;right:14px;bottom:246px;z-index:9995;border:0;border-radius:999px;padding:10px 13px;background:#b42318;color:#fff;font:700 12px Arial;box-shadow:0 8px 25px #0002;cursor:pointer}#gmailOauthPanel{position:fixed;right:14px;bottom:292px;z-index:10002;width:min(420px,92vw);background:#fff;border:1px solid #e3e8f0;border-radius:16px;padding:14px;box-shadow:0 20px 60px #0003;display:none}#gmailOauthPanel small{color:#748096}.goa{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.goa button{border:0;border-radius:9px;padding:9px 11px;cursor:pointer}.goa .p{background:#b42318;color:#fff}.goa .g{background:#eef3fb;color:#2764dc}@media(max-width:720px){#gmailOauthBtn{bottom:210px}#gmailOauthPanel{bottom:258px;right:8px}}`;document.head.appendChild(s)}
async function render(){let box=document.getElementById('gmailOauthPanel');if(!box)return;box.innerHTML='<b>Gmail Production Bridge</b><br><small>正在读取状态…</small>';try{let x=await status(),a=x.account;box.innerHTML=`<b>Gmail Production Bridge</b><div style="margin-top:6px"><small>OAuth客户端：${x.configured?'已配置':'待配置 Google OAuth Client'}</small><br><small>账号：${a?.email_address||'未连接'}</small><br><small>状态：${a?.status||'setup_required'}</small></div><div class="goa"><button class="p" id="goConnect">${a?'重新授权 Gmail':'连接 Gmail'}</button><button class="g" id="goRun">立即执行邮件队列</button><button class="g" id="goClose">关闭</button></div><div id="goMsg" style="font-size:12px;margin-top:8px;color:#748096"></div>`;goConnect.onclick=async()=>{try{await connect()}catch(e){goMsg.textContent=e.message}};goRun.onclick=async()=>{try{goMsg.textContent='正在执行…';let r=await process();goMsg.textContent=`已处理 ${r.processed||0}，发送 ${r.sent||0}，失败 ${r.failed||0}`}catch(e){goMsg.textContent=e.message}};goClose.onclick=()=>box.style.display='none'}catch(e){box.innerHTML=`<b>Gmail Production Bridge</b><div style="margin-top:6px;color:#b42318">${e.message}</div><div class="goa"><button class="g" id="goClose">关闭</button></div>`;goClose.onclick=()=>box.style.display='none'}}
function boot(){style();if(!document.getElementById('gmailOauthBtn')){let b=document.createElement('button');b.id='gmailOauthBtn';b.textContent='✉ Gmail';b.onclick=()=>{let p=document.getElementById('gmailOauthPanel');p.style.display=p.style.display==='block'?'none':'block';if(p.style.display==='block')render()};document.body.appendChild(b)}if(!document.getElementById('gmailOauthPanel')){let p=document.createElement('div');p.id='gmailOauthPanel';document.body.appendChild(p)}}
window.GmailProductionBridge={status,connect,process};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();