/* AI TRADE — Gmail History Consumer + Reply Thread UI */
(()=>{
const CFG=window.AITRADE_CLOUD_CONFIG||{};
async function client(){if(!window.supabase)return null;return window.supabase.createClient(CFG.url,CFG.anonKey,{auth:{persistSession:true,autoRefreshToken:true}})}
async function load(){const sb=await client();if(!sb)throw new Error('Supabase未加载');const {data:{session}}=await sb.auth.getSession();if(!session)throw new Error('请先登录AI TRADE云同步');const {data,error}=await sb.from('gmail_history_messages').select('id,from_email,subject,snippet,intent,priority,customer_id,gmail_thread_id,received_at,processing_status').order('received_at',{ascending:false}).limit(50);if(error)throw error;return data||[]}
function css(){if(document.getElementById('ghuCss'))return;const s=document.createElement('style');s.id='ghuCss';s.textContent=`#ghuBtn{position:fixed;right:14px;bottom:102px;z-index:9998;border:0;border-radius:999px;padding:10px 14px;background:#0f766e;color:#fff;font:700 12px Arial;box-shadow:0 8px 24px #0003}#ghuModal{position:fixed;inset:0;z-index:10030;background:#0f172a80;display:none;align-items:center;justify-content:center;padding:14px}#ghuModal .box{width:min(980px,96vw);max-height:90vh;overflow:auto;background:#f8fafc;border-radius:18px;padding:16px}.ghuTable{width:100%;border-collapse:collapse;background:#fff;font-size:11px}.ghuTable th,.ghuTable td{padding:9px;border-bottom:1px solid #e5e7eb;text-align:left;vertical-align:top}.ghuP{font-weight:800}.ghuUrgent{color:#b91c1c}.ghuHigh{color:#b45309}.ghuBtn{border:0;border-radius:9px;padding:9px 11px;background:#0f766e;color:#fff;cursor:pointer}.ghuGhost{background:#e2e8f0;color:#334155}`;document.head.appendChild(s)}
function esc(s){return String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
async function render(){const b=document.getElementById('ghuBody');if(!b)return;b.innerHTML='<div>加载中...</div>';try{const rows=await load();b.innerHTML=`<div style="display:flex;justify-content:space-between;gap:8px;align-items:center"><div><h2 style="margin:0">Gmail History Consumer</h2><div style="font-size:12px;color:#64748b">Gmail回复线程、意图识别与Customer匹配。</div></div><div><button class="ghuBtn" onclick="AI_GMAIL_HISTORY.refresh()">刷新</button> <button class="ghuBtn ghuGhost" onclick="AI_GMAIL_HISTORY.close()">关闭</button></div></div><div style="margin:12px 0;padding:10px;background:#fff;border:1px solid #e2e8f0;border-radius:12px;font-size:12px"><b>链路：</b> Gmail Watch → Pub/Sub → Webhook → History Consumer → Thread Map → AI Inbox 3.0 → CRM</div><table class="ghuTable"><thead><tr><th>时间</th><th>发件人</th><th>主题</th><th>意图</th><th>优先级</th><th>Customer</th><th>Thread</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td>${esc(r.received_at||'')}</td><td>${esc(r.from_email||'')}</td><td><b>${esc(r.subject||'(无主题)')}</b><br><span style="color:#64748b">${esc((r.snippet||'').slice(0,150))}</span></td><td>${esc(r.intent||'reply')}</td><td class="ghuP ${r.priority==='urgent'?'ghuUrgent':r.priority==='high'?'ghuHigh':''}">${esc(r.priority||'normal')}</td><td>${esc(r.customer_id||'待匹配')}</td><td>${esc((r.gmail_thread_id||'').slice(0,18))}</td></tr>`).join(''):'<tr><td colspan="7">暂无已消费的Gmail回复。Google Pub/Sub尚未接通时这里为空是正常的。</td></tr>'}</tbody></table>`}catch(e){b.innerHTML=`<div style="padding:18px">${esc(e.message||e)}<br><button class="ghuBtn ghuGhost" onclick="AI_GMAIL_HISTORY.close()" style="margin-top:10px">关闭</button></div>`}}
function open(){document.getElementById('ghuModal').style.display='flex';render()}function close(){document.getElementById('ghuModal').style.display='none'}
function boot(){css();if(!document.getElementById('ghuBtn')){const x=document.createElement('button');x.id='ghuBtn';x.textContent='↩ Inbox Live';x.onclick=open;document.body.appendChild(x)}if(!document.getElementById('ghuModal')){const m=document.createElement('div');m.id='ghuModal';m.innerHTML='<div class="box" id="ghuBody"></div>';m.onclick=e=>{if(e.target===m)close()};document.body.appendChild(m)}}
window.AI_GMAIL_HISTORY={open,close,refresh:render};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();