/* AI TRADE — Goal Engine 1.0 */
(()=>{
const KEY='aitrade_goal_engine_v1', DBK='aitrade_full59_v1';
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')||d}catch{return d}};
const put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
function cfg(){return get(KEY,{annualTarget:30000000,currency:'CNY',avgOrderValue:300000,leadToReply:.12,replyToRFQ:.22,rfqToQuote:.80,quoteToOrder:.18,workingDaysPerMonth:22,updatedAt:null})}
function save(c){c.updatedAt=new Date().toISOString();put(KEY,c);window.AITRADE_CLOUD?.push?.();render()}
function num(v,d=0){v=Number(v);return Number.isFinite(v)?v:d}
function db(){return get(DBK,{customers:[],leads:[],signals:[],quotes:[],orders:[]})}
function actuals(){let x=db(), orders=(x.orders||[]), revenue=orders.reduce((a,o)=>a+num(o.total||o.amount),0), replies=(x.signals||[]).filter(s=>/reply|回复/i.test(s.type||'')).length, rfqs=(x.signals||[]).filter(s=>/rfq|询价|quote|price|precio|cotiz/i.test(s.type||'')).length, quotes=(x.quotes||[]).length, leads=(x.leads||[]).length, customers=(x.customers||[]).length;return{revenue,orders:orders.length,replies,rfqs,quotes,leads,customers}}
function plan(){let c=cfg(),a=actuals(),orders=Math.max(1,Math.ceil(c.annualTarget/Math.max(1,c.avgOrderValue))),quotes=Math.ceil(orders/Math.max(.01,c.quoteToOrder)),rfqs=Math.ceil(quotes/Math.max(.01,c.rfqToQuote)),replies=Math.ceil(rfqs/Math.max(.01,c.replyToRFQ)),leads=Math.ceil(replies/Math.max(.01,c.leadToReply));let monthly={revenue:c.annualTarget/12,orders:orders/12,quotes:quotes/12,rfqs:rfqs/12,replies:replies/12,leads:leads/12},weekly={revenue:c.annualTarget/52,orders:orders/52,quotes:quotes/52,rfqs:rfqs/52,replies:replies/52,leads:leads/52},daily={revenue:monthly.revenue/c.workingDaysPerMonth,orders:monthly.orders/c.workingDaysPerMonth,quotes:monthly.quotes/c.workingDaysPerMonth,rfqs:monthly.rfqs/c.workingDaysPerMonth,replies:monthly.replies/c.workingDaysPerMonth,leads:monthly.leads/c.workingDaysPerMonth};return{cfg:c,actual:a,annual:{revenue:c.annualTarget,orders,quotes,rfqs,replies,leads},monthly,weekly,daily,progress:c.annualTarget?Math.min(100,a.revenue/c.annualTarget*100):0,gap:Math.max(0,c.annualTarget-a.revenue)}}
function fmt(n){return Math.round(n).toLocaleString()}
function money(n,c){return `${c==='CNY'?'¥':c==='USD'?'$':''}${fmt(n)} ${c}`}
function style(){if(document.getElementById('goalStyle'))return;let s=document.createElement('style');s.id='goalStyle';s.textContent=`#goalBtn{position:fixed;right:14px;bottom:64px;z-index:9996;border:0;border-radius:999px;padding:10px 14px;background:#0f766e;color:#fff;box-shadow:0 8px 25px #0002;font:700 12px Arial;cursor:pointer}#goalModal{position:fixed;inset:0;z-index:10003;background:#0f172a80;display:none;align-items:center;justify-content:center;padding:14px}#goalModal .box{width:min(980px,96vw);max-height:90vh;overflow:auto;background:#f7f9fc;border-radius:18px;padding:16px}.gTop{display:flex;justify-content:space-between;gap:10px;align-items:center}.gGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.gCard{background:#fff;border:1px solid #e3e8f0;border-radius:13px;padding:12px}.gK{font-size:11px;color:#748096}.gV{font-size:22px;font-weight:800;margin-top:5px}.gBar{height:10px;background:#e8edf4;border-radius:99px;overflow:hidden}.gBar i{display:block;height:100%;background:#0f766e}.gForm{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.gForm label{font-size:10px;color:#748096}.gForm input,.gForm select{width:100%;padding:9px;border:1px solid #dfe5ef;border-radius:9px;margin-top:4px}.gTable{width:100%;border-collapse:collapse;font-size:11px;background:#fff;border-radius:12px;overflow:hidden}.gTable th,.gTable td{padding:9px;border-bottom:1px solid #edf0f5;text-align:right}.gTable th:first-child,.gTable td:first-child{text-align:left}.gBtn{border:0;border-radius:9px;padding:9px 11px;background:#0f766e;color:#fff;cursor:pointer}.gBtn.gray{background:#eef3fb;color:#2764dc}@media(max-width:720px){#goalBtn{bottom:138px}.gGrid,.gForm{grid-template-columns:1fr 1fr}}@media(max-width:430px){.gGrid,.gForm{grid-template-columns:1fr}.gV{font-size:19px}}`;document.head.appendChild(s)}
function render(){let root=document.getElementById('goalBody');if(!root)return;let p=plan(),c=p.cfg,a=p.actual;root.innerHTML=`<div class="gTop"><div><h2 style="margin:0">Goal Engine 1.0</h2><div class="gK">把年度营收目标反推成 Lead → Reply → RFQ → Quote → Order 的日/周/月目标。</div></div><button class="gBtn gray" onclick="AITRADE_GOAL.close()">关闭</button></div><div class="gGrid" style="margin-top:12px"><div class="gCard"><div class="gK">年度目标</div><div class="gV">${money(c.annualTarget,c.currency)}</div></div><div class="gCard"><div class="gK">已成交</div><div class="gV">${money(a.revenue,c.currency)}</div></div><div class="gCard"><div class="gK">目标缺口</div><div class="gV">${money(p.gap,c.currency)}</div></div><div class="gCard"><div class="gK">完成率</div><div class="gV">${p.progress.toFixed(1)}%</div><div class="gBar"><i style="width:${p.progress}%"></i></div></div></div><h3>目标参数</h3><div class="gForm"><label>年度营收目标<input id="gTarget" type="number" value="${c.annualTarget}"></label><label>币种<select id="gCurrency"><option ${c.currency==='CNY'?'selected':''}>CNY</option><option ${c.currency==='USD'?'selected':''}>USD</option></select></label><label>平均订单金额<input id="gAov" type="number" value="${c.avgOrderValue}"></label><label>每月工作日<input id="gDays" type="number" value="${c.workingDaysPerMonth}"></label><label>Lead→Reply %<input id="gLr" type="number" step="0.1" value="${(c.leadToReply*100).toFixed(1)}"></label><label>Reply→RFQ %<input id="gRr" type="number" step="0.1" value="${(c.replyToRFQ*100).toFixed(1)}"></label><label>RFQ→Quote %<input id="gRq" type="number" step="0.1" value="${(c.rfqToQuote*100).toFixed(1)}"></label><label>Quote→Order %<input id="gQo" type="number" step="0.1" value="${(c.quoteToOrder*100).toFixed(1)}"></label></div><div style="margin:10px 0"><button class="gBtn" onclick="AITRADE_GOAL.saveForm()">保存并重新计算</button></div><h3>倒推目标</h3><table class="gTable"><thead><tr><th>周期</th><th>营收</th><th>Leads</th><th>Replies</th><th>RFQs</th><th>Quotes</th><th>Orders</th></tr></thead><tbody>${[['年度',p.annual],['每月',p.monthly],['每周',p.weekly],['每天',p.daily]].map(([n,v])=>`<tr><td>${n}</td><td>${money(v.revenue,c.currency)}</td><td>${fmt(v.leads)}</td><td>${fmt(v.replies)}</td><td>${fmt(v.rfqs)}</td><td>${fmt(v.quotes)}</td><td>${fmt(v.orders)}</td></tr>`).join('')}</tbody></table><h3>当前实际</h3><div class="gGrid"><div class="gCard"><div class="gK">Lead Pool</div><div class="gV">${fmt(a.leads)}</div></div><div class="gCard"><div class="gK">Replies</div><div class="gV">${fmt(a.replies)}</div></div><div class="gCard"><div class="gK">RFQs / Quotes</div><div class="gV">${fmt(a.rfqs)} / ${fmt(a.quotes)}</div></div><div class="gCard"><div class="gK">Orders</div><div class="gV">${fmt(a.orders)}</div></div></div><div class="gCard" style="margin-top:10px"><b>说明</b><div class="gK" style="margin-top:5px">Goal Engine 只根据你设置的漏斗转化率反推目标，不把估算值冒充真实业绩。实际成交额只读取订单数据；转化率可以随 Feedback Brain 的真实结果逐步校准。</div></div>`}
function saveForm(){let c=cfg();c.annualTarget=num(document.getElementById('gTarget').value,c.annualTarget);c.currency=document.getElementById('gCurrency').value;c.avgOrderValue=num(document.getElementById('gAov').value,c.avgOrderValue);c.workingDaysPerMonth=Math.max(1,num(document.getElementById('gDays').value,c.workingDaysPerMonth));c.leadToReply=num(document.getElementById('gLr').value,12)/100;c.replyToRFQ=num(document.getElementById('gRr').value,22)/100;c.rfqToQuote=num(document.getElementById('gRq').value,80)/100;c.quoteToOrder=num(document.getElementById('gQo').value,18)/100;save(c)}
function open(){document.getElementById('goalModal').style.display='flex';render()}function close(){document.getElementById('goalModal').style.display='none'}
function boot(){style();if(!document.getElementById('goalBtn')){let b=document.createElement('button');b.id='goalBtn';b.textContent='◎ Goal';b.onclick=open;document.body.appendChild(b)}if(!document.getElementById('goalModal')){let m=document.createElement('div');m.id='goalModal';m.innerHTML='<div class="box" id="goalBody"></div>';m.onclick=e=>{if(e.target===m)close()};document.body.appendChild(m)}}
window.AITRADE_GOAL={open,close,render,saveForm,plan,cfg};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();