/* AI TRADE — Google Pub/Sub Production Connector 2.0 */
(()=>{
const FN='google-pubsub-provisioner', WATCH='gmail-watch-manager', OAUTH='gmail-oauth-bridge';
const cfg=()=>window.AITRADE_CLOUD_CONFIG||{};
async function client(){if(window.AITRADE_CLOUD?.client)return window.AITRADE_CLOUD.client;if(window.AITRADE_CLOUD?.loadClient)return await window.AITRADE_CLOUD.loadClient();throw new Error('云端客户端未初始化')}
async function call(fn,body){let sb=await client(),{data:{session}}=await sb.auth.getSession();if(!session)throw new Error('请先登录 AI TRADE 云同步');let r=await fetch(`${cfg().url}/functions/v1/${fn}`,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${session.access_token}`,'apikey':cfg().anonKey},body:JSON.stringify(body)});let x=await r.json().catch(()=>({}));if(!r.ok||x?.ok===false)throw new Error(x.detail||x.error||'request_failed');return x}
async function oauthStatus(){return call(OAUTH,{action:'status'})}
async function oauth(){let redirect_after=location.href.split('#')[0];let x=await call(OAUTH,{action:'start',redirect_after});if(x.authorization_url)location.href=x.authorization_url}
async function projects(){return call(FN,{action:'list_projects'})}
async function provision(project,topic,sub){return call(FN,{action:'provision',google_project_id:project,pubsub_topic_id:topic,pubsub_subscription_id:sub})}
async function startWatch(){return call(WATCH,{action:'start'})}
function box(){let body=document.getElementById('gpsBody');if(!body)return null;let old=document.getElementById('gpsAutoProd');if(old)return old;let el=document.createElement('div');el.id='gpsAutoProd';el.className='gpsBox';el.style.marginBottom='14px';el.innerHTML=`<div style="display:flex;justify-content:space-between;gap:12px;align-items:flex-start"><div><b>⚡ 一键生产连接 2.0</b><div style="font-size:12px;color:#64748b;margin-top:4px">Google OAuth → 自动发现 Cloud Project → 创建 Pub/Sub Topic → 授予 Gmail Publisher → 创建 Push Subscription → 启动 Gmail Watch</div></div><span id="gpsAutoState" class="gpsNo">待检查</span></div><div id="gpsAutoProjects" style="margin-top:10px"></div><div class="gpsActions"><button class="gpsP" id="gpsAutoOauth">1. 授权 Gmail + Google Cloud</button><button class="gpsG" id="gpsAutoDiscover">2. 自动发现 Project</button><button class="gpsP" id="gpsAutoProvision">3. 自动配置 Pub/Sub + Watch</button></div><div id="gpsAutoMsg" style="margin-top:9px;font-size:12px;color:#64748b"></div>`;body.prepend(el);wire(el);check(el);return el}
function msg(el,t,err=false){let n=el.querySelector('#gpsAutoMsg');if(n){n.textContent=t;n.style.color=err?'#b42318':'#64748b'}}
async function check(el){try{let s=await oauthStatus(),ok=!!s.account&&!!s.cloud_scope;el.querySelector('#gpsAutoState').textContent=ok?'OAuth 已就绪':'需要授权';el.querySelector('#gpsAutoState').className=ok?'gpsOk':'gpsNo';if(s.account)msg(el,`当前账号：${s.account.email_address||'-'} · Cloud 权限：${s.cloud_scope?'已授权':'需要重新授权'}`)}catch(e){msg(el,e.message,true)}}
function wire(el){el.querySelector('#gpsAutoOauth').onclick=async()=>{try{msg(el,'正在打开 Google 正式授权…');await oauth()}catch(e){msg(el,e.message,true)}};el.querySelector('#gpsAutoDiscover').onclick=async()=>{try{msg(el,'正在读取你有权限的 Google Cloud Projects…');let x=await projects(),arr=x.projects||[];let wrap=el.querySelector('#gpsAutoProjects');if(!arr.length){wrap.innerHTML='<div class="gpsStep"><b>未找到可用 Google Cloud Project</b><span class="gpsNo">待创建</span><div>请先在 Google Cloud 创建一个 Project，再回来点击自动发现。</div></div>';return msg(el,'未发现 Project',true)}wrap.innerHTML=`<select id="gpsAutoProjectSelect" class="gpsInput">${arr.map(p=>`<option value="${p.project_id}">${p.name} · ${p.project_id}</option>`).join('')}</select>`;let sel=wrap.querySelector('select');let inp=document.getElementById('gpsProject');if(inp&&sel){inp.value=sel.value;sel.onchange=()=>inp.value=sel.value}msg(el,`已发现 ${arr.length} 个 Project，已自动选择第一个。`)}catch(e){msg(el,e.message,true)}};el.querySelector('#gpsAutoProvision').onclick=async()=>{try{let project=document.getElementById('gpsProject')?.value?.trim()||el.querySelector('#gpsAutoProjectSelect')?.value||'',topic=document.getElementById('gpsTopic')?.value?.trim()||'ai-trade-gmail',sub=document.getElementById('gpsSub')?.value?.trim()||'ai-trade-gmail-push';if(!project)throw new Error('请先授权并点击“自动发现 Project”');msg(el,'正在创建 Pub/Sub Topic、Publisher 权限和 Push Subscription…');let p=await provision(project,topic,sub);msg(el,'Pub/Sub 已完成，正在启动 Gmail Watch…');let w=await startWatch();let exp=w.result?.expiration?new Date(w.result.expiration).toLocaleString():'-';msg(el,`✅ 生产链路已接通：${p.topic_name} → Push Webhook → Gmail Watch；到期 ${exp}`);el.querySelector('#gpsAutoState').textContent='LIVE';el.querySelector('#gpsAutoState').className='gpsOk';setTimeout(()=>window.AI_GOOGLE_SETUP?.load?.(),800)}catch(e){msg(el,e.message,true)}}}
function boot(){let n=0,t=setInterval(()=>{n++;if(document.getElementById('gpsBody')){box();clearInterval(t)}else if(n>60)clearInterval(t)},250);document.addEventListener('click',e=>{let b=e.target.closest?.('[data-go="google"],#gpsBtn');if(b)setTimeout(box,400)});let mo=new MutationObserver(()=>{if(document.getElementById('gpsBody')&&!document.getElementById('gpsAutoProd'))box()});mo.observe(document.body,{childList:true,subtree:true})}
window.AI_GOOGLE_PUBSUB_PROD={oauthStatus,projects,provision,startWatch};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();