/* AI TRADE — Worker Scheduler + Health Monitor + Dead Letter Center */
(()=>{
const CFG=window.AITRADE_CLOUD_CONFIG||{};
let last=null;
async function token(){if(!window.supabase||!CFG.url||!CFG.anonKey)return null;const sb=window.supabase.createClient(CFG.url,CFG.anonKey,{auth:{persistSession:true,autoRefreshToken:true}});const {data}=await sb.auth.getSession();return data.session?.access_token||null}
async function call(action,payload={}){const t=await token();if(!t)throw new Error('请先登录AI TRADE云同步');const r=await fetch(`${CFG.url}/functions/v1/system-health-runner`,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${t}`,'apikey':CFG.anonKey},body:JSON.stringify({action,...payload})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.detail||d.error||'请求失败');return d}
function style(){if(document.getElementById('hmStyle'))return;let s=document.createElement('style');s.id='hmStyle';s.textContent=`#hmBtn{position:fixed;right:14px;bottom:18px;z-index:9998;border:0;border-radius:999px;padding:10px 14px;background:#111827;color:#fff;font:700 12px Arial;box-shadow:0 8px 24px #0003}#hmModal{position:fixed;inset:0;z-index:10020;background:#0f172a80;display:none;align-items:center;justify-content:center;padding:14px}#hmModal .box{width:min(900px,96vw);max-height:90vh;overflow:auto;background:#f7f9fc;border-radius:18px;padding:16px}.hmGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.hmCard{background:white;border:1px solid #e3e8f0;border-radius:13px;padding:12px}.hmK{font-size:11px;color:#748096}.hmV{font-size:22px;font-weight:800;margin-top:4px}.hmBtn{border:0;border-radius:9px;padding:9px 11px;background:#2563eb;color:#fff;cursor:pointer}.hmBtn.gray{background:#eef3fb;color:#2764dc}.hmBtn.red{background:#fee2e2;color:#991b1b}.hmTable{width:100%;border-collapse:collapse;background:#fff;font-size:11px}.hmTable th,.hmTable td{padding:9px;border-bottom:1px solid #edf0f5;text-align:left}@media(max-width:720px){.hmGrid{grid-template-columns:1fr 1fr}}@media(max-width:430px){.hmGrid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function render(d){last=d;let b=document.getElementById('hmBody');if(!b)return;const s=d.summary||{},sch=s.scheduler||{};const failed=d.failed||[];const alerts=d.alerts||[];b.innerHTML=`<div style="display:flex;justify-content:space-between;gap:8px;align-items:center"><div><h2 style="margin:0">Worker Scheduler + Health Monitor</h2><div class="hmK">生产稳定性、失败重试、Dead Letter、Gmail连接与后台调度控制。</div></div><button class="hmBtn gray" onclick="AI_HEALTH.close()">关闭</button></div><div class="hmGrid" style="margin-top:12px"><div class="hmCard"><div class="hmK">Gmail</div><div class="hmV">${s.gmail?.status==='connected'?'已连接':'待配置'}</div></div><div class="hmCard"><div class="hmK">Mail Ready</div><div class="hmV">${s.mailReady||0}</div></div><div class="hmCard"><div class="hmK">Dead Letters</div><div class="hmV">${s.mailFailed||0}</div></div><div class="hmCard"><div class="hmK">Open Alerts</div><div class="hmV">${s.openAlerts||0}</div></div></div><h3>Worker Scheduler</h3><div class="hmCard"><label><input id="schEnabled" type="checkbox" ${sch.scheduler_enabled!==false?'checked':''}> 启用调度</label><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:8px"><label>邮件Worker(min)<input id="schMail" type="number" min="1" value="${sch.mail_interval_minutes||5}" style="width:80px;margin-left:4px"></label><label>联系人增强(min)<input id="schEnrich" type="number" min="15" value="${sch.enrichment_interval_minutes||60}" style="width:80px;margin-left:4px"></label><label>自动获客(min)<input id="schLead" type="number" min="15" value="${sch.lead_interval_minutes||60}" style="width:80px;margin-left:4px"></label><button class="hmBtn" onclick="AI_HEALTH.saveScheduler()">保存</button><button class="hmBtn gray" onclick="AI_HEALTH.refresh()">刷新健康状态</button></div></div><h3>Dead Letter Center</h3><table class="hmTable"><thead><tr><th>Job</th><th>错误</th><th>更新时间</th><th></th></tr></thead><tbody>${failed.length?failed.map(x=>`<tr><td>${x.id}</td><td>${String(x.last_error||'').slice(0,120)}</td><td>${x.updated_at||''}</td><td><button class="hmBtn red" onclick="AI_HEALTH.retry('${x.id}')">重试</button></td></tr>`).join(''):'<tr><td colspan="4">暂无 Dead Letter</td></tr>'}</tbody></table><h3>System Alerts</h3><table class="hmTable"><thead><tr><th>级别</th><th>来源</th><th>内容</th><th></th></tr></thead><tbody>${alerts.length?alerts.map(a=>`<tr><td>${a.severity}</td><td>${a.source}</td><td><b>${a.title}</b><br>${a.detail||''}</td><td><button class="hmBtn gray" onclick="AI_HEALTH.resolve(${a.id})">解决</button></td></tr>`).join(''):'<tr><td colspan="4">暂无未解决告警</td></tr>'}</tbody></table><div class="hmCard" style="margin-top:12px"><b>说明</b><div class="hmK" style="margin-top:5px">当前 Scheduler 参数已保存到后端。真正24/7定时触发仍需要 Supabase Cron/外部调度器调用对应 Edge Function；本页面负责配置、健康检查、失败恢复与审计入口。</div></div>`}
async function refresh(){try{render(await call('health'))}catch(e){alert(e.message)}}
async function retry(id){try{await call('retry_dead_letter',{job_id:id});await refresh()}catch(e){alert(e.message)}}
async function resolve(id){try{await call('resolve_alert',{id});await refresh()}catch(e){alert(e.message)}}
async function saveScheduler(){try{await call('scheduler_save',{scheduler_enabled:document.getElementById('schEnabled').checked,mail_interval_minutes:+document.getElementById('schMail').value,enrichment_interval_minutes:+document.getElementById('schEnrich').value,lead_interval_minutes:+document.getElementById('schLead').value});await refresh()}catch(e){alert(e.message)}}
function open(){document.getElementById('hmModal').style.display='flex';refresh()}function close(){document.getElementById('hmModal').style.display='none'}
function boot(){style();if(!document.getElementById('hmBtn')){let x=document.createElement('button');x.id='hmBtn';x.textContent='⚙ Health';x.onclick=open;document.body.appendChild(x)}if(!document.getElementById('hmModal')){let m=document.createElement('div');m.id='hmModal';m.innerHTML='<div class="box" id="hmBody"></div>';m.onclick=e=>{if(e.target===m)close()};document.body.appendChild(m)}}
window.AI_HEALTH={open,close,refresh,retry,resolve,saveScheduler};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();