(()=>{
const STORE='aitrade_inbox_listener_v2';
const CORE='aitrade_full59_v1';
const GMAIL='aitrade_gmail_bridge_v1';
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
function load(){try{return JSON.parse(localStorage.getItem(STORE)||'null')||{messages:[],lastSync:null,filters:{ignoreAutomated:true},version:'2.0'}}catch{return{messages:[],lastSync:null,filters:{ignoreAutomated:true},version:'2.0'}}}
let state=load();
function save(){state.lastSync=new Date().toISOString();localStorage.setItem(STORE,JSON.stringify(state));window.AITRADE_CLOUD?.push?.();render()}
function core(){try{return JSON.parse(localStorage.getItem(CORE)||'null')}catch{return null}}
function gmail(){try{return JSON.parse(localStorage.getItem(GMAIL)||'null')}catch{return null}}
function emailFrom(s){let m=String(s||'').match(/<([^>]+)>/);return (m?m[1]:String(s||'').split(/\s+/).pop()||'').toLowerCase().trim()}
function isAutomated(m){let x=(m.from+' '+m.subject).toLowerCase();return /noreply|no-reply|notification|notifications|security|github|google|supabase|tiktok|linkedin/.test(x)}
function classify(m){let t=((m.subject||'')+' '+(m.body||'')+' '+(m.snippet||'')).toLowerCase();let out={intent:'Reply',points:8,stage:'contacted',priority:'normal',entities:{qty:null,model:null,market:null}};
 if(/quote|quotation|price|pricing|precio|cotiz|rfq|offer/.test(t)){out={...out,intent:'RFQ',points:18,stage:'rfq',priority:'high'}}
 if(/sample|muestra|demo unit/.test(t)){out={...out,intent:'Sample',points:15,stage:'sample',priority:'high'}}
 if(/meeting|call|zoom|teams|reunión|reunion/.test(t)){out={...out,intent:'Meeting',points:12,priority:'high'}}
 if(/order|purchase order|\bpo\b|pedido|confirm order/.test(t)){out={...out,intent:'Order Intent',points:24,stage:'rfq',priority:'urgent'}}
 if(/not interested|no thanks|remove me|unsubscribe|no interesado|no nos interesa/.test(t)){out={...out,intent:'Rejected',points:-10,stage:'lost',priority:'low'}}
 if(/reorder|repeat order|reposición|reposicion|again order/.test(t)){out={...out,intent:'Reorder',points:30,stage:'won',priority:'urgent'}}
 let q=t.match(/(?:qty|quantity|pcs|pieces|unidades|cantidad)[:\s-]*(\d[\d,]*)/i)||t.match(/(\d[\d,]*)\s*(?:pcs|pieces|unidades)/i);if(q)out.entities.qty=Number(q[1].replace(/,/g,''));
 let mm=t.match(/\b(?:yyk[- ]?)?[a-z]{0,4}q?\d{2,4}(?:\s*pro)?\b/i);if(mm)out.entities.model=mm[0].toUpperCase();
 if(/mexico|méxico/.test(t))out.entities.market='Mexico';else if(/brazil|brasil/.test(t))out.entities.market='Brazil';else if(/south africa|sudáfrica|sudafrica/.test(t))out.entities.market='South Africa';else if(/united states|usa|u\.s\./.test(t))out.entities.market='USA';
 return out}
function matchCustomer(m,db){if(!db?.customers)return null;let from=emailFrom(m.from);let subject=(m.subject||'').toLowerCase();for(const c of db.customers){let blob=((c.email||'')+' '+(c.notes||'')+' '+(c.company||'')+' '+(c.contact||'')).toLowerCase();if(from&&blob.includes(from))return c}
 for(const c of db.customers){if(c.company&&subject.includes(c.company.toLowerCase()))return c}
 return null}
function ingest(input){let arr=Array.isArray(input)?input:[input],db=core(),gb=gmail();let added=0;for(const raw of arr){let m={id:String(raw.id||raw.message_id||('M'+Date.now()+Math.random().toString(36).slice(2,7))),threadId:String(raw.thread_id||raw.threadId||''),from:raw.from_||raw.from||'',to:raw.to||'',subject:raw.subject||'',snippet:raw.snippet||'',body:raw.body||'',receivedAt:raw.receivedAt||raw.timestamp||new Date().toISOString(),labels:raw.labels||[],status:'new'};if(state.messages.some(x=>x.id===m.id))continue;if(state.filters.ignoreAutomated&&isAutomated(m)){m.status='ignored-automated';m.intent='Automated';state.messages.push(m);continue}let ai=classify(m);Object.assign(m,ai);let c=matchCustomer(m,db);m.customerId=c?.id||'';m.company=c?.company||'';m.matchStatus=c?'matched':'unmatched';state.messages.push(m);added++;
 if(c){db.signals=db.signals||[];db.signals.push({id:'S'+Date.now()+Math.random().toString(36).slice(2,5),customerId:c.id,type:ai.intent,points:ai.points,note:`Inbox Listener 2.0: ${m.subject}`,createdAt:new Date().toISOString()});c.stage=ai.stage||c.stage;c.notes=(c.notes||'')+`\n[Inbox Listener 2.0] ${m.from} | ${m.subject} | Intent=${ai.intent}${ai.entities.qty?' | Qty='+ai.entities.qty:''}${ai.entities.model?' | Model='+ai.entities.model:''}`;if(ai.entities.qty)c.lastQty=ai.entities.qty;if(ai.entities.model)c.lastModel=ai.entities.model;if(ai.entities.market)c.lastMarket=ai.entities.market;
 }
 if(gb){gb.replies=gb.replies||[];if(!gb.replies.some(x=>x.messageId===m.id))gb.replies.push({id:'R'+Date.now()+Math.random().toString(36).slice(2,5),messageId:m.id,threadId:m.threadId,from:m.from,company:m.company,customerId:m.customerId,subject:m.subject,body:m.body,intent:m.intent,receivedAt:m.receivedAt,synced:!!c})}
 }
 if(db)localStorage.setItem(CORE,JSON.stringify(db));if(gb)localStorage.setItem(GMAIL,JSON.stringify(gb));save();return added}
function markReviewed(id){let m=state.messages.find(x=>x.id===id);if(m){m.status='reviewed';save()}}
function render(){let sec=document.getElementById('inboxlistener2');if(!sec)return;let msgs=state.messages||[],biz=msgs.filter(x=>!String(x.status).startsWith('ignored')),hi=biz.filter(x=>['high','urgent'].includes(x.priority)).length,unmatched=biz.filter(x=>x.matchStatus==='unmatched').length;document.getElementById('ilStats').innerHTML=[['业务回复',biz.length],['高优先级',hi],['未匹配客户',unmatched],['最后同步',state.lastSync?new Date(state.lastSync).toLocaleString():'未运行']].map(x=>`<div class="card kpi"><small>${x[0]}</small><b style="font-size:${x[0]==='最后同步'?'13px':'22px'}">${esc(x[1])}</b></div>`).join('');document.getElementById('ilRows').innerHTML=msgs.slice().reverse().map(m=>`<tr><td><b>${esc(m.from||'-')}</b><br><small>${esc(m.company||m.matchStatus||'')}</small></td><td>${esc(m.subject||'-')}</td><td><span class="tag ${m.priority==='urgent'?'hot':m.priority==='high'?'warn':m.matchStatus==='matched'?'ok':''}">${esc(m.intent||'-')}</span></td><td>${m.entities?.qty||'-'}<br><small>${esc(m.entities?.model||'')}</small></td><td>${m.matchStatus==='matched'?'<span class="tag ok">已匹配</span>':m.status==='ignored-automated'?'<span class="tag">自动邮件忽略</span>':'<span class="tag warn">待匹配</span>'}</td><td>${esc(m.status||'')}</td></tr>`).join('')||'<tr><td colspan="6">暂无 Listener 数据。Gmail 新邮件通过授权监听通道导入后会在这里自动分类。</td></tr>'}
function init(){let nav=document.getElementById('nav'),main=document.querySelector('main');if(!nav||!main||document.getElementById('inboxlistener2'))return;let btn=document.createElement('button');btn.dataset.p='inboxlistener2';btn.innerHTML='◉ <span>Inbox Listener 2.0</span>';let inbox=[...nav.querySelectorAll('button')].find(x=>x.dataset.p==='inbox');nav.insertBefore(btn,inbox||null);let sec=document.createElement('section');sec.id='inboxlistener2';sec.className='page';sec.innerHTML=`<div class="top"><div><h1>Inbox Listener 2.0</h1><div class="sub">Gmail新回复 → 自动过滤通知邮件 → 线程/邮箱匹配客户 → 意图识别 → RFQ/样品/会议/订单/拒绝/复购 → Customer Memory + Buying Signals + CRM。</div></div><div class="badge">● Gmail Connected</div></div><div class="grid4" id="ilStats"></div><div class="card" style="margin-top:10px"><div class="item"><b>识别字段：</b> Intent、数量、型号、市场、客户匹配、优先级、CRM阶段。</div><div class="item warn"><b>运行边界：</b> GitHub Pages 不直接持有 Gmail OAuth。持续监听必须由授权 Gmail 通道/后端触发，再调用本模块 <code>AITRADE_INBOX_LISTENER.ingest()</code> 写回业务系统。</div></div><div class="card wrap" style="margin-top:10px"><table><thead><tr><th>发件人</th><th>主题</th><th>AI意图</th><th>数量/型号</th><th>客户匹配</th><th>状态</th></tr></thead><tbody id="ilRows"></tbody></table></div>`;main.insertBefore(sec,document.getElementById('inbox'));btn.onclick=()=>{document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('on'));btn.classList.add('on');document.querySelectorAll('.page').forEach(x=>x.classList.remove('on'));sec.classList.add('on');render()};render()}
window.AITRADE_INBOX_LISTENER={ingest,classify,markReviewed,state:()=>state};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();