(()=>{
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let rows=[],container=null,loadVersion=0,selected=null;
const statuses={new:'新询盘',qualified:'有效采购',contacted:'已跟进',closed:'已结束',spam:'无效/垃圾'};
const url='https://mambapro0813-byte.github.io/mamba/mx/q105.html';
async function client(){await window.AITRADE_CLOUD?.loadClient();const c=window.AITRADE_CLOUD?.client;if(!c)throw new Error('云连接未就绪');const {data,error}=await c.auth.getSession();if(error)throw error;if(!data.session)throw new Error('请先登录');return c;}
function shell(){container.innerHTML='<div class="ib-toolbar"><a class="btn" href="'+url+'" target="_blank" rel="noopener">打开西语产品站</a><a class="btn g" href="en/q105.html" target="_blank" rel="noopener">English</a><button class="btn" id="ibRefresh">刷新询盘</button><button class="btn g" id="ibExport">导出当前列表</button></div><p class="ib-note">Q105 正式图片与完整参数待补；价格、样品条件和交期由人工确认。下方评分是采购匹配规则分，不代表成交概率。</p><div id="ibMetrics"></div><details class="ib-card"><summary>生成推广链接与西语文案</summary><p>来源标签用于询盘归因。生成链接不会自动发布，也不代表已经产生访问。</p><select id="ibSource"><option>facebook</option><option>instagram</option><option>linkedin</option><option>whatsapp</option><option>google</option></select><input id="ibContent" placeholder="素材标识，例如 q105-memory-wire-01" maxlength="80"><button id="ibGenerate" class="btn">生成</button><textarea id="ibLink" readonly aria-label="推广文案与链接"></textarea></details><label>筛选状态 <select id="ibFilter"><option value="">全部状态</option>'+Object.entries(statuses).map(([k,v])=>'<option value="'+k+'">'+v+'</option>').join('')+'</select></label><div id="ibRows"></div><div id="ibDetail"></div>';
container.querySelector('#ibRefresh').onclick=refresh;container.querySelector('#ibFilter').onchange=paint;
container.querySelector('#ibGenerate').onclick=()=>{const u=new URL(url);u.searchParams.set('utm_source',container.querySelector('#ibSource').value);u.searchParams.set('utm_medium','social');u.searchParams.set('utm_campaign','mx-q105');u.searchParams.set('utm_content',container.querySelector('#ibContent').value.trim());container.querySelector('#ibLink').value='¿Buscas audífonos para tu marca o distribución en México? Conoce Q105: gancho con alambre con memoria, pensado para usuarios con lentes. Consulta opciones OEM/ODM, fotografías y condiciones de muestra. Comparte tu cantidad y requisitos para recibir una propuesta.\n\n'+u.href;};
container.querySelector('#ibExport').onclick=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(rows,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='Q105-inquiries.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
}
function paint(){
const filter=container.querySelector('#ibFilter').value;
const source={};rows.forEach(r=>{const s=r.attribution?.utm_source||'direct';source[s]=(source[s]||0)+1;});
container.querySelector('#ibMetrics').innerHTML='<div class="ib-metrics">'+[['最近询盘',rows.length],['待处理',rows.filter(r=>r.status==='new').length],['有效采购',rows.filter(r=>r.status==='qualified').length]].map(([label,n])=>'<div class="ib-card"><small>'+label+'</small><h2>'+n+'</h2></div>').join('')+'</div><p class="ib-note">统计最近100条非测试询盘 · 来源：'+esc(Object.entries(source).map(([k,n])=>k+' '+n).join(' / ')||'暂无')+'。尚未接入曝光和访问量统计。</p>';
container.querySelector('#ibRows').innerHTML=rows.filter(r=>!filter||r.status===filter).map(r=>'<article class="ib-card"><div class="ib-toolbar"><b>'+esc(r.company)+'</b><span>'+statuses[r.status]+' · 匹配分 '+r.score+'</span></div><p>'+esc(r.country)+' · Q105 × '+r.quantity+' · '+esc(r.contact_name)+'</p><p class="ib-note">'+esc(r.attribution?.utm_source||'direct')+' / '+esc(r.attribution?.utm_campaign||'—')+' · '+esc(new Date(r.created_at).toLocaleString())+'</p><button class="btn" data-inquiry="'+r.id+'">客户 / 需求 / 报价审批</button></article>').join('')||'<p class="ib-card">暂无匹配询盘。公开表单提交成功后会进入这里。</p>';
container.querySelectorAll('[data-inquiry]').forEach(b=>b.onclick=()=>detail(b.dataset.inquiry));
}
async function refresh(){
const generation=++loadVersion;
try{const c=await client();const {data,error}=await c.from('ai_trade_inbound_inquiries').select('*').eq('is_test',false).order('created_at',{ascending:false}).limit(100);if(error)throw error;if(generation!==loadVersion)return;rows=data||[];shell();paint();}
catch(e){if(generation!==loadVersion)return;rows=[];container.innerHTML='<div class="ib-card"><p>'+esc(e.message)+'</p><form id="ibLogin"><label>邮箱<input name="email" type="email" required autocomplete="email"></label><label>密码<input name="password" type="password" required autocomplete="current-password"></label><button class="btn">登录</button><p id="ibLoginStatus" role="status"></p></form><button id="ibRetry" class="btn g">重试</button></div>';container.querySelector('#ibRetry').onclick=refresh;
container.querySelector('#ibLogin').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget;try{await window.AITRADE_CLOUD.loadClient();const r=await window.AITRADE_CLOUD.client.auth.signInWithPassword({email:form.elements.email.value,password:form.elements.password.value});if(r.error)throw r.error;form.reset();refresh();}catch(err){container.querySelector('#ibLoginStatus').textContent=err.message;}};}
}
async function detail(id){
const r=rows.find(x=>x.id===id);if(!r)return;selected=id;
const box=container.querySelector('#ibDetail');box.innerHTML='<p>加载云端报价…</p>';
try{const c=await client();const {data:q,error}=await c.from('ai_trade_quotes').select('id,unit_price,currency,quantity,total_amount,terms,approval_status,sent_at').eq('id',r.quote_id).single();if(error)throw error;if(selected!==id)return;
const reply=r.language==='es'?'Hola '+r.contact_name+', gracias por tu interés en Q105. Hemos recibido tu solicitud de '+r.quantity+' unidades. Revisaremos tus requisitos y confirmaremos las especificaciones, las opciones de personalización y las condiciones de muestra antes de enviarte una cotización.':'Hi '+r.contact_name+', thank you for your interest in Q105. We received your inquiry for '+r.quantity+' units. We will review the specifications, customization and sample terms before preparing a quotation.';
box.innerHTML='<article class="ib-card"><h2>'+esc(r.company)+'</h2><p>'+esc(r.contact_name)+' · '+esc(r.email)+' · '+esc(r.whatsapp||'未填 WhatsApp')+'</p><p>云端客户：'+esc(r.customer_source_id)+'<br>RFQ #'+r.rfq_id+' / 报价 #'+q.id+' / '+esc(q.approval_status)+'</p><p style="white-space:pre-wrap">'+esc(r.message)+'</p><p>定制：'+esc(r.customization)+'</p><label>处理状态<select id="ibStatus">'+Object.entries(statuses).map(([k,v])=>'<option value="'+k+'" '+(k===r.status?'selected':'')+'>'+v+'</option>').join('')+'</select></label><button class="btn" id="ibStatusSave">保存状态</button><h3>回复草稿（未发送）</h3><textarea readonly>'+esc(reply)+'</textarea><h3>报价与人工审批</h3><p class="ib-note">请核实型号参数、成本、交期及下方商务条款。批准后仍需另行发送给客户。</p><form id="ibQuote"><label>对外单价<input name="price" type="number" required min="0.0001" max="1000000" step="0.0001" value="'+esc(q.unit_price??'')+'"></label><label>币种<select name="currency">'+['USD','CNY','MXN'].map(v=>'<option '+(q.currency===v?'selected':'')+'>'+v+'</option>').join('')+'</select></label><label>商务条款（交期、付款、运费及税费范围）<textarea name="terms" required minlength="5" maxlength="3000">'+esc(q.terms?.commercial_terms||'')+'</textarea></label><div class="ib-toolbar"><button class="btn" type="submit">保存待审批报价</button><button class="btn g" type="button" id="ibApprove">确认核实并批准</button></div></form><p id="ibResult" role="status"></p></article>';
box.querySelector('#ibStatusSave').onclick=async()=>{try{const status=box.querySelector('#ibStatus').value;const {error}=await c.from('ai_trade_inbound_inquiries').update({status}).eq('id',id);if(error)throw error;r.status=status;paint();box.querySelector('#ibResult').textContent='状态已保存';}catch(e){box.querySelector('#ibResult').textContent=e.message;}};
let saving=false;
async function save(approve){const f=box.querySelector('#ibQuote');if(saving||!f.reportValidity())return;if(approve&&!confirm('确认已核实参数、单价和条款，并批准这份报价？此操作不会发送邮件。'))return;saving=true;try{const {error}=await c.rpc('ai_trade_review_inbound_quote',{p_inquiry_id:id,p_unit_price:Number(f.elements.price.value),p_currency:f.elements.currency.value,p_terms:f.elements.terms.value,p_approve:approve});if(error)throw error;await detail(id);}catch(e){box.querySelector('#ibResult').textContent=e.message;}finally{saving=false;}}
box.querySelector('#ibQuote').onsubmit=e=>{e.preventDefault();save(false);};box.querySelector('#ibApprove').onclick=()=>save(true);box.scrollIntoView({behavior:'smooth',block:'start'});
}catch(e){box.textContent=e.message;}}
function boot(){
const style=document.createElement('style');style.textContent='.ib-toolbar{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin:12px 0}.ib-card{background:#fff;border:1px solid #dce7f1;border-radius:14px;padding:18px;margin:12px 0;overflow-wrap:anywhere}.ib-note{font-size:13px;color:#60778b}.ib-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}#inboundCenter label{display:block;margin:10px 0}#inboundCenter input,#inboundCenter textarea,#inboundCenter select{font:inherit;border:1px solid #ccdbe8;border-radius:8px;padding:10px;max-width:100%}#inboundCenter textarea{display:block;width:100%;min-height:110px}#inboundCenter .btn{display:inline-block;border:0;background:#287bdc;color:white;border-radius:8px;padding:10px 14px;text-decoration:none;cursor:pointer}#inboundCenter .btn.g{background:#eaf2fa;color:#2561a0}@media(max-width:500px){.ib-metrics{gap:6px}.ib-metrics .ib-card{padding:10px}}';document.head.appendChild(style);
const standalone=document.querySelector('#inboundStandalone');
const section=document.createElement('section');section.id='inboundCenter';section.className=standalone?'':'page';container=section;
if(standalone){standalone.appendChild(section);refresh();}else{const main=document.querySelector('body>.app main');if(main)main.appendChild(section);
const b=document.createElement('button');b.id='inboundBtn';b.hidden=true;b.onclick=()=>{if(window.AI_UNIFIED_SHELL&&matchMedia('(min-width:901px)').matches){window.AI_UNIFIED_SHELL.showPage('inbound');refresh();}else location.href='inbound.html';};document.body.appendChild(b);
let tries=0;const timer=setInterval(()=>{const sidebar=document.querySelector('#primaryDashboard .pd-side');if(sidebar&&!document.querySelector('#ibNav')){const nav=document.createElement('button');nav.id='ibNav';nav.className='pd-nav';nav.dataset.go='inbound';nav.innerHTML='<span class="pd-ic">↙</span>主动询盘<small>Inbound</small>';nav.addEventListener('click',refresh);sidebar.insertBefore(nav,sidebar.querySelector('.pd-user'));clearInterval(timer);}else if(++tries>60)clearInterval(timer);},250);
document.addEventListener('click',e=>{if(e.target.closest('[data-go="inbound"]'))refresh();},true);}
window.addEventListener('aitrade:inbound-auth',()=>{selected=null;refresh();});
window.addEventListener('aitrade:cloud-ready',()=>{if(standalone)refresh();});
}
window.AI_INBOUND={refresh};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();