/* AI TRADE — Learning Engine 3.0 */
(()=>{
const CFG=()=>window.AITRADE_CLOUD_CONFIG||{};
let latest=null;
async function sb(){if(!window.supabase){await new Promise((res,rej)=>{let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=res;s.onerror=rej;document.head.appendChild(s)})}let c=CFG();return window.supabase.createClient(c.url,c.anonKey,{auth:{persistSession:true,autoRefreshToken:true}})}
async function session(){let c=await sb(),{data:{session}}=await c.auth.getSession();if(!session)throw new Error('请先登录 AI TRADE 云同步');return {c,session}}
async function run(){let {session}=await session(),c=CFG();let r=await fetch(`${c.url}/functions/v1/learning-engine-runner`,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${session.access_token}`,'apikey':c.anonKey},body:JSON.stringify({window_days:90})});let x=await r.json();if(!r.ok||!x.ok)throw new Error(x.detail||x.error||'Learning Engine运行失败');latest=x.snapshot;return latest}
async function load(){let {c}=await session();let {data,error}=await c.from('learning_engine_snapshots').select('*').order('created_at',{ascending:false}).limit(1).maybeSingle();if(error)throw error;latest=data||null;return latest}
const esc=x=>String(x??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
function css(){if(document.getElementById('le3Css'))return;let s=document.createElement('style');s.id='le3Css';s.textContent=`#le3Btn{position:fixed;right:14px;bottom:338px;z-index:9994;border:0;border-radius:999px;padding:10px 13px;background:#4338ca;color:#fff;font:800 12px Arial;box-shadow:0 8px 24px #0002}#le3Modal{position:fixed;inset:0;z-index:10070;background:#0f172a80;display:none;align-items:center;justify-content:center;padding:14px}#le3Modal .box{width:min(1050px,96vw);max-height:90vh;overflow:auto;background:#f8fafc;border-radius:20px;padding:16px}.leTop{display:flex;justify-content:space-between;gap:10px;align-items:center}.leGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.leCard{background:#fff;border:1px solid #e5e7eb;border-radius:13px;padding:12px}.leBig{font-size:22px;font-weight:900;margin-top:4px}.leMuted{font-size:11px;color:#64748b}.leSec{margin-top:14px}.leTable{width:100%;border-collapse:collapse;background:#fff;font-size:11px;border-radius:12px;overflow:hidden}.leTable th,.leTable td{padding:9px;border-bottom:1px solid #edf2f7;text-align:left}.leRec{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:11px;margin:7px 0}.leTag{display:inline-block;padding:3px 7px;border-radius:999px;background:#eef2ff;color:#4338ca;font-size:9px;font-weight:800}.leBtn{border:0;border-radius:10px;padding:9px 11px;background:#4338ca;color:#fff;font-weight:800}.leGhost{background:#eef2ff;color:#3730a3}@media(max-width:720px){#le3Btn{display:none!important}.leGrid{grid-template-columns:1fr 1fr}.leTop{align-items:flex-start}.leTable{font-size:10px}}`;document.head.appendChild(s)}
function table(title,headers,rows,renderer){return `<div class="leSec"><h3 style="margin:0 0 8px">${title}</h3><table class="leTable"><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows?.length?rows.map(renderer).join(''):`<tr><td colspan="${headers.length}">暂无足够样本</td></tr>`}</tbody></table></div>`}
function render(x){let b=document.getElementById('le3Body');if(!b)return;if(!x){b.innerHTML='<div style="padding:28px;text-align:center">暂无学习快照。登录后点击“重新学习”。</div>';return}let m=x.metrics||{},conf={low:'低',medium:'中',high:'高'}[x.confidence]||x.confidence;let recs=x.recommendations||[];b.innerHTML=`<div class="leTop"><div><h2 style="margin:0">Learning Engine 3.0</h2><div class="leMuted">基于真实 Leads、决策人、已发送邮件、回复与 RFQ 自动学习。当前规则只生成建议，不会自动修改价格或外发策略。</div></div><div><button class="leBtn" onclick="AI_LEARNING3.execute()">重新学习</button> <button class="leBtn leGhost" onclick="AI_LEARNING3.close()">关闭</button></div></div><div class="leGrid" style="margin-top:12px"><div class="leCard"><div class="leMuted">学习窗口</div><div class="leBig">${m.window_days||90}天</div></div><div class="leCard"><div class="leMuted">证据置信度</div><div class="leBig">${conf}</div></div><div class="leCard"><div class="leMuted">邮件回复率</div><div class="leBig">${m.reply_rate||0}%</div><div class="leMuted">${m.replied||0}/${m.sent||0}</div></div><div class="leCard"><div class="leMuted">RFQ</div><div class="leBig">${m.rfqs||0}</div></div><div class="leCard"><div class="leMuted">Leads</div><div class="leBig">${m.leads||0}</div></div><div class="leCard"><div class="leMuted">高ICP</div><div class="leBig">${m.high_icp||0}</div></div><div class="leCard"><div class="leMuted">决策人</div><div class="leBig">${m.decision_makers||0}</div></div><div class="leCard"><div class="leMuted">已验证联系人</div><div class="leBig">${m.verified_contacts||0}</div></div></div><div class="leSec"><h3 style="margin:0 0 8px">AI 学习建议</h3>${recs.length?recs.map(r=>`<div class="leRec"><span class="leTag">${esc(r.type)}</span> <b>${esc(r.title)}</b><div class="leMuted" style="margin-top:5px">${esc(r.reason)} · 置信度 ${esc(r.confidence)}</div></div>`).join(''):'<div class="leRec">当前样本不足。系统不会在小样本下强行得出结论。</div>'}</div>${table('市场学习',['市场','Leads','高ICP率','平均ICP'],x.market_learning||[],r=>`<tr><td><b>${esc(r.market)}</b></td><td>${r.lead_count}</td><td>${r.high_icp_rate}%</td><td>${r.avg_icp}</td></tr>`)}${table('决策人学习',['职位','样本','可验证率','Authority'],x.role_learning||[],r=>`<tr><td><b>${esc(r.role)}</b></td><td>${r.count}</td><td>${r.verification_rate}%</td><td>${r.avg_authority}</td></tr>`)}${table('产品需求学习',['产品','RFQ','需求数量','含目标价'],x.product_learning||[],r=>`<tr><td><b>${esc(r.product)}</b></td><td>${r.rfq_count}</td><td>${r.total_qty||0}</td><td>${r.priced_requests||0}</td></tr>`)}${table('开发信学习',['主题','发送','回复','回复率'],x.message_learning||[],r=>`<tr><td><b>${esc(r.theme)}</b></td><td>${r.sent}</td><td>${r.replied}</td><td>${r.reply_rate}%</td></tr>`)}<div class="leMuted" style="margin-top:12px">安全策略：Learning Engine 仅产生 Suggested Rules。样本量不足时降低置信度；不会自动降价、承诺账期、改变独家条款或绕过 Human Approval。</div>`}
async function execute(){let b=document.getElementById('le3Body');if(b)b.innerHTML='<div style="padding:30px;text-align:center">正在分析最近90天真实销售数据…</div>';try{render(await run())}catch(e){if(b)b.innerHTML=`<div style="padding:22px;color:#b42318"><b>Learning Engine 无法运行</b><br><br>${esc(e.message)}<br><br><button class="leBtn leGhost" onclick="AI_LEARNING3.close()">关闭</button></div>`}}
async function open(){document.getElementById('le3Modal').style.display='flex';try{let x=await load();x?render(x):execute()}catch(e){render(null)}}function close(){document.getElementById('le3Modal').style.display='none'}
function boot(){css();if(!document.getElementById('le3Btn')){let b=document.createElement('button');b.id='le3Btn';b.textContent='🧠 Learning';b.onclick=open;document.body.appendChild(b)}if(!document.getElementById('le3Modal')){let m=document.createElement('div');m.id='le3Modal';m.innerHTML='<div class="box" id="le3Body"></div>';m.onclick=e=>{if(e.target===m)close()};document.body.appendChild(m)}}
window.AI_LEARNING3={open,close,execute,run,load};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();