/* AI TRADE — Production Acceptance Test 1.0 */
(()=>{
const CFG=()=>window.AITRADE_CLOUD_CONFIG||{};
async function client(){if(!window.supabase){await new Promise((res,rej)=>{let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=res;s.onerror=rej;document.head.appendChild(s)})}let c=CFG();return window.supabase.createClient(c.url,c.anonKey,{auth:{persistSession:true,autoRefreshToken:true}})}
async function run(){let sb=await client(),{data:{session}}=await sb.auth.getSession();if(!session)throw new Error('请先登录 AI TRADE 云同步');let c=CFG(),r=await fetch(`${c.url}/functions/v1/production-acceptance-runner`,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${session.access_token}`,'apikey':c.anonKey},body:'{}'});let x=await r.json();if(!r.ok||!x.ok)throw new Error(x.detail||x.error||'验收测试失败');return x}
function css(){if(document.getElementById('patStyle'))return;let s=document.createElement('style');s.id='patStyle';s.textContent=`#patBtn{position:fixed;right:14px;bottom:294px;z-index:9995;border:0;border-radius:999px;padding:10px 13px;background:#2563eb;color:#fff;font:700 12px Arial;box-shadow:0 8px 25px #0002}#patModal{position:fixed;inset:0;z-index:10060;background:#0f172a80;display:none;align-items:center;justify-content:center;padding:14px}#patModal .box{width:min(920px,96vw);max-height:90vh;overflow:auto;background:#f8fafc;border-radius:18px;padding:16px}.patTop{display:flex;justify-content:space-between;align-items:center;gap:8px}.patSummary{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:12px 0}.patCard{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:12px}.patRow{display:grid;grid-template-columns:1.4fr .6fr 2fr;gap:8px;align-items:center;background:#fff;border:1px solid #e5e7eb;border-radius:11px;padding:10px;margin:7px 0;font-size:12px}.patStatus{font-weight:800}.pat-pass{color:#087a53}.pat-blocked{color:#b45309}.pat-fail{color:#b42318}.patAction{border:0;border-radius:9px;padding:9px 11px;background:#2563eb;color:#fff;font-weight:700}.patClose{border:0;border-radius:9px;padding:9px 11px;background:#eef2ff;color:#3730a3}@media(max-width:720px){#patBtn{bottom:258px}.patSummary{grid-template-columns:1fr 1fr}.patRow{grid-template-columns:1fr}.patRow>div:nth-child(2){font-size:13px}}`;document.head.appendChild(s)}
function esc(x){return String(x??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function render(x){let b=document.getElementById('patBody');if(!b)return;let map={pass:'通过',blocked:'待外部配置',fail:'失败'};b.innerHTML=`<div class="patTop"><div><h2 style="margin:0">Production Acceptance Test 1.0</h2><div style="font-size:11px;color:#64748b;margin-top:4px">验证数据库、后台调度、Dispatcher、告警、Gmail OAuth 与 Gmail Watch 的真实生产状态。</div></div><button class="patClose" onclick="AI_PAT.close()">关闭</button></div><div class="patSummary"><div class="patCard"><small>总状态</small><div style="font-size:22px;font-weight:900" class="pat-${x.overall_status}">${map[x.overall_status]||x.overall_status}</div></div><div class="patCard"><small>通过</small><div style="font-size:22px;font-weight:900">${x.passed}</div></div><div class="patCard"><small>待配置</small><div style="font-size:22px;font-weight:900">${x.blocked}</div></div><div class="patCard"><small>失败</small><div style="font-size:22px;font-weight:900">${x.failed}</div></div></div>${(x.checks||[]).map(c=>`<div class="patRow"><b>${esc(c.name)}</b><div class="patStatus pat-${c.status}">${map[c.status]||c.status}</div><div style="color:#64748b;word-break:break-word">${esc(typeof c.detail==='string'?c.detail:JSON.stringify(c.detail))}</div></div>`).join('')}<div style="margin-top:12px"><button class="patAction" onclick="AI_PAT.execute()">重新运行验收</button></div>`}
async function execute(){let b=document.getElementById('patBody');if(b)b.innerHTML='<div style="padding:30px;text-align:center">正在执行 Production Acceptance Test…</div>';try{render(await run())}catch(e){if(b)b.innerHTML=`<div style="padding:20px;color:#b42318"><b>验收无法执行</b><br><br>${esc(e.message)}<br><br><button class="patClose" onclick="AI_PAT.close()">关闭</button></div>`}}
function open(){document.getElementById('patModal').style.display='flex';execute()}function close(){document.getElementById('patModal').style.display='none'}
function boot(){css();if(!document.getElementById('patBtn')){let b=document.createElement('button');b.id='patBtn';b.textContent='✓ 验收';b.onclick=open;document.body.appendChild(b)}if(!document.getElementById('patModal')){let m=document.createElement('div');m.id='patModal';m.innerHTML='<div class="box" id="patBody"></div>';m.onclick=e=>{if(e.target===m)close()};document.body.appendChild(m)}}
window.AI_PAT={open,close,execute,run};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();