/* AI TRADE — Revenue Intelligence 1.0 */
(()=>{
const DBK='aitrade_full59_v1', QK='ai_trade_quotes_v2', FBK='aitrade_feedback_brain_v2', KEY='aitrade_revenue_intelligence_v1';
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')||d}catch{return d}};const put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const n=v=>{v=parseFloat(v);return Number.isFinite(v)?v:0};
const stageProb={prospect:.08,contacted:.12,replied:.2,qualified:.35,rfq:.5,sample:.58,negotiation:.72,won:1,reorder:.82,lost:0};
const stageDays={prospect:90,contacted:75,replied:60,qualified:45,rfq:30,sample:35,negotiation:18,won:0,reorder:20,lost:999};
function db(){return get(DBK,{customers:[],signals:[],quotes:[],orders:[],leads:[]})}
function feedbackScores(){let fb=window.FeedbackBrain2?.score?.()||[];return Object.fromEntries(fb.map(x=>[String(x.id),x.learned]))}
function customerForecast(c,x,fb){let stage=String(c.stage||'prospect').toLowerCase(),base=stageProb[stage]??.1,learned=(fb[String(c.id)]??(+c.icp||50))/100;let sig=(x.signals||[]).filter(s=>String(s.customerId)===String(c.id));let bonus=Math.min(.18,sig.reduce((a,s)=>a+(+s.points||0),0)/500);let p=Math.max(0,Math.min(.98,base*.55+learned*.35+bonus));let qs=[...(x.quotes||[]),...(Array.isArray(get(QK,[]))?get(QK,[]):[])].filter(q=>String(q.customerId)===String(c.id));let quoteAmount=Math.max(0,...qs.map(q=>n(q.total)));let orderAmount=(x.orders||[]).filter(o=>String(o.customerId)===String(c.id)).reduce((a,o)=>a+n(o.total),0);let expectedBase=quoteAmount||n(c.pipelineValue)||n(c.expectedValue)||0;let weighted=stage==='won'?Math.max(orderAmount,expectedBase):expectedBase*p;return{id:c.id,company:c.company||c.name||'',stage,prob:Math.round(p*100),quoteAmount,orderAmount,weighted,days:stageDays[stage]??60,model:qs[0]?.model||qs[0]?.product||''}}
function productEconomics(x){let rows={};let orders=x.orders||[];for(let o of orders){let m=o.model||o.product||'未标型号',rev=n(o.total)||n(o.amount),qty=n(o.qty||o.quantity),p=(window.PRODUCTS||[]).find(z=>String(z.model)===String(m)),cost=n(o.cost)||n(p?.cost),gross=cost&&qty?rev-cost*qty:0;if(!rows[m])rows[m]={model:m,revenue:0,gross:0,orders:0,qty:0,margin:null};rows[m].revenue+=rev;rows[m].gross+=gross;rows[m].orders++;rows[m].qty+=qty}return Object.values(rows).map(r=>({...r,margin:r.revenue&&r.gross?r.gross/r.revenue:null})).sort((a,b)=>b.revenue-a.revenue)}
function snapshot(){let x=db(),fb=feedbackScores(),cf=(x.customers||[]).map(c=>customerForecast(c,x,fb)).sort((a,b)=>b.weighted-a.weighted);let horizons={d30:0,d60:0,d90:0};for(let r of cf){if(r.days<=30)horizons.d30+=r.weighted;if(r.days<=60)horizons.d60+=r.weighted;if(r.days<=90)horizons.d90+=r.weighted}let won=(x.orders||[]).reduce((a,o)=>a+n(o.total),0),pipeline=cf.reduce((a,r)=>a+r.quoteAmount,0),weighted=cf.reduce((a,r)=>a+r.weighted,0),out={updatedAt:new Date().toISOString(),won,pipeline,weighted,horizons,customers:cf,products:productEconomics(x)};put(KEY,out);window.AITRADE_CLOUD?.push?.();return out}
function fmt(v){return '$'+n(v).toLocaleString(undefined,{maximumFractionDigits:0})}
function style(){if(document.getElementById('revIntelStyle'))return;let s=document.createElement('style');s.id='revIntelStyle';s.textContent=`#revIntelBtn{position:fixed;right:112px;bottom:18px;z-index:9997;border:0;border-radius:999px;padding:10px 14px;background:#0f766e;color:white;font:700 12px Arial;box-shadow:0 8px 25px #0003;cursor:pointer}#revIntelModal{position:fixed;inset:0;z-index:10002;background:#0f172a80;display:none;align-items:center;justify-content:center;padding:14px}#revIntelModal .box{width:min(1080px,96vw);max-height:90vh;overflow:auto;background:#f7f9fc;border-radius:18px;padding:16px}.riTop{display:flex;justify-content:space-between;gap:10px;align-items:center}.riGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.riCard{background:#fff;border:1px solid #e3e8f0;border-radius:13px;padding:12px}.riCard b{display:block;font-size:22px;margin-top:5px}.riMuted{font-size:11px;color:#748096}.riTable{width:100%;border-collapse:collapse;font-size:11px;background:#fff;border-radius:12px;overflow:hidden}.riTable th,.riTable td{padding:9px;border-bottom:1px solid #edf0f5;text-align:left}.riBtn{border:0;border-radius:9px;padding:8px 10px;background:#0f766e;color:#fff;cursor:pointer}.riBtn.gray{background:#eef3fb;color:#0f766e}@media(max-width:720px){#revIntelBtn{right:110px;bottom:88px}.riGrid{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
function render(){let s=snapshot(),body=document.getElementById('revIntelBody');if(!body)return;let top=s.customers.slice(0,12),prod=s.products.slice(0,10);body.innerHTML=`<div class="riTop"><div><h2 style="margin:0">Revenue Intelligence 1.0</h2><div class="riMuted">成交概率、加权销售管道、30/60/90天预测和产品收入质量。</div></div><button class="riBtn gray" onclick="AITRADE_REVENUE.close()">关闭</button></div><div class="riGrid" style="margin-top:12px"><div class="riCard"><span class="riMuted">已成交/订单额</span><b>${fmt(s.won)}</b></div><div class="riCard"><span class="riMuted">报价管道</span><b>${fmt(s.pipeline)}</b></div><div class="riCard"><span class="riMuted">加权管道</span><b>${fmt(s.weighted)}</b></div><div class="riCard"><span class="riMuted">30天预测</span><b>${fmt(s.horizons.d30)}</b></div><div class="riCard"><span class="riMuted">60天预测</span><b>${fmt(s.horizons.d60)}</b></div><div class="riCard"><span class="riMuted">90天预测</span><b>${fmt(s.horizons.d90)}</b></div><div class="riCard"><span class="riMuted">有报价客户</span><b>${s.customers.filter(x=>x.quoteAmount>0).length}</b></div><div class="riCard"><span class="riMuted">高概率客户 ≥70%</span><b>${s.customers.filter(x=>x.prob>=70).length}</b></div></div><h3>最可能成交客户</h3><table class="riTable"><thead><tr><th>客户</th><th>阶段</th><th>成交概率</th><th>报价额</th><th>加权金额</th><th>预计窗口</th></tr></thead><tbody>${top.map(r=>`<tr><td><b>${esc(r.company||'-')}</b></td><td>${esc(r.stage)}</td><td>${r.prob}%</td><td>${fmt(r.quoteAmount)}</td><td>${fmt(r.weighted)}</td><td>${r.days>=999?'—':r.days+'天'}</td></tr>`).join('')||'<tr><td colspan="6">暂无客户管道数据</td></tr>'}</tbody></table><h3>产品收入质量</h3><table class="riTable"><thead><tr><th>产品</th><th>收入</th><th>订单</th><th>数量</th><th>估算毛利率</th></tr></thead><tbody>${prod.map(r=>`<tr><td><b>${esc(r.model)}</b></td><td>${fmt(r.revenue)}</td><td>${r.orders}</td><td>${r.qty||'-'}</td><td>${r.margin==null?'成本数据不足':(r.margin*100).toFixed(1)+'%'}</td></tr>`).join('')||'<tr><td colspan="5">暂无订单数据</td></tr>'}</tbody></table><div class="riMuted" style="margin-top:10px">说明：预测来自当前 CRM 阶段、ICP/Learned Score、购买信号和现有报价；没有报价金额的客户不会被虚构销售额。产品毛利仅在存在真实成本数据时计算。</div>`}
function open(){document.getElementById('revIntelModal').style.display='flex';render()}function close(){document.getElementById('revIntelModal').style.display='none'}
function boot(){style();if(!document.getElementById('revIntelBtn')){let b=document.createElement('button');b.id='revIntelBtn';b.textContent='Revenue';b.onclick=open;document.body.appendChild(b)}if(!document.getElementById('revIntelModal')){let m=document.createElement('div');m.id='revIntelModal';m.innerHTML='<div class="box" id="revIntelBody"></div>';m.onclick=e=>{if(e.target===m)close()};document.body.appendChild(m)}snapshot()}
window.AITRADE_REVENUE={open,close,render,snapshot};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();