/* AI TRADE Sales Action Center 2.0 — business-first Tasks, Calendar, Customer 360. Preserves stable UI. */
(()=>{
const K='aitrade_full59_v1';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function data(){try{return JSON.parse(localStorage.getItem(K)||'null')||{customers:[],signals:[],quotes:[],orders:[],leads:[]}}catch{return {customers:[],signals:[],quotes:[],orders:[],leads:[]}}}
function dt(v){let d=new Date(v);return isNaN(d)?null:d}
function daysSince(v){const d=dt(v);return d?Math.max(0,Math.floor((Date.now()-d.getTime())/86400000)):999}
function signalFor(db,id){return (db.signals||[]).filter(x=>x.customerId===id).sort((a,b)=>(dt(b.time)?.getTime()||0)-(dt(a.time)?.getTime()||0))[0]}
function prob(db,c){let s=(db.signals||[]).filter(x=>x.customerId===c.id).reduce((a,x)=>a+(+x.points||0),0);return Math.max(5,Math.min(95,Math.round((+c.icp||60)*.45+s*.55)))}
function nextAction(db,c){const sig=signalFor(db,c.id),age=sig?daysSince(sig.time):999,st=c.stage||'prospect';if(c.next)return c.next;if(st==='rfq')return '生成AI报价';if(st==='sample')return age>=7?'立即跟进样品反馈':'等待样品反馈';if(st==='quoted')return age>=5?'报价跟进':'等待报价反馈';if(st==='replied')return '2小时内回复客户';if(st==='contacted')return age>=3?'发送D3跟进':'等待客户回复';if(st==='won')return '检查交付与复购窗口';return 'AI首次开发'}
function taskList(){const db=data(),now=Date.now();let out=[];(db.customers||[]).filter(c=>c.stage!=='lost').forEach(c=>{const sig=signalFor(db,c.id),age=sig?daysSince(sig.time):999,st=c.stage||'prospect',p=prob(db,c);let due=now,priority='普通',reason='';if(st==='replied'){priority='紧急';reason='客户已回复，建议2小时内处理'}else if(st==='rfq'){priority='紧急';reason='客户已询价，立即准备报价'}else if(st==='quoted'&&age>=5){priority='高';reason=`报价已发 ${age} 天，建议跟进`}else if(st==='sample'&&age>=7){priority='高';reason=`样品阶段已 ${age} 天，建议索取反馈`}else if(st==='contacted'&&age>=3){priority='高';reason=`开发后 ${age} 天未推进，执行D3跟进`}else if(st==='prospect'){priority=p>=75?'高':'普通';reason='尚未触达，执行首次开发'}else if(st==='won'){reason='检查交付/复购状态'}else{reason='按Next Best Action推进'};out.push({id:c.id,company:c.company,country:c.country||'',stage:st,prob:p,action:nextAction(db,c),priority,reason,due});});
	return out.sort((a,b)=>({紧急:0,高:1,普通:2}[a.priority]-({紧急:0,高:1,普通:2}[b.priority])||b.prob-a.prob))}
function ensureSections(){const app=$('body>.app');if(!app)return false;const main=$('main',app);if(!main)return false;if(!$('#tasks2',app)){const s=document.createElement('section');s.id='tasks2';s.className='page';s.innerHTML='<div class="top"><div><h1>任务中心 2.0</h1><div class="sub">根据客户阶段、最近互动和成交概率自动生成销售动作。</div></div><div class="badge">● Auto Tasks</div></div><div class="grid4" id="taskKpi2"></div><div class="card" style="margin-top:10px"><div class="toolbar"><button class="btn" id="taskRefresh2">刷新任务</button><select class="input" id="taskFilter2"><option value="">全部优先级</option><option>紧急</option><option>高</option><option>普通</option></select></div><div id="taskRows2"></div></div>';main.appendChild(s)}
if(!$('#calendar2',app)){const s=document.createElement('section');s.id='calendar2';s.className='page';s.innerHTML='<div class="top"><div><h1>销售日历 2.0</h1><div class="sub">把跟进、报价、样品和复购动作按执行窗口排列。</div></div><div class="badge">● Sales Calendar</div></div><div class="card"><div class="toolbar"><button class="btn" id="calRefresh2">刷新日历</button></div><div id="calRows2"></div></div>';main.appendChild(s)}
if(!$('#customer360Modal')){const d=document.createElement('dialog');d.id='customer360Modal';d.innerHTML='<div class="modal"><div class="top"><div><h1 id="c360Title">Customer 360</h1><div class="sub">客户统一画像与下一步行动</div></div><button class="btn g" id="c360Close">关闭</button></div><div id="c360Body"></div></div>';document.body.appendChild(d);$('#c360Close').onclick=()=>d.close()}
return true}
function renderTasks(){if(!ensureSections())return;const all=taskList(),f=$('#taskFilter2')?.value||'',a=f?all.filter(x=>x.priority===f):all;const urgent=all.filter(x=>x.priority==='紧急').length,high=all.filter(x=>x.priority==='高').length;$('#taskKpi2').innerHTML=[['今日任务',all.length],['紧急',urgent],['高优先级',high],['高意向',all.filter(x=>x.prob>=75).length]].map(x=>`<div class="card kpi"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('');$('#taskRows2').innerHTML=a.map(t=>`<div class="item" style="display:grid;grid-template-columns:1.3fr .7fr .7fr 1.4fr auto;gap:10px;align-items:center"><div><b>${esc(t.company)}</b><br><small>${esc(t.country)} · ${esc(t.stage)}</small></div><div><span class="tag ${t.priority==='紧急'?'hot':t.priority==='高'?'warn':''}">${t.priority}</span></div><div><b>${t.prob}%</b><br><small>成交概率</small></div><div><b>${esc(t.action)}</b><br><small>${esc(t.reason)}</small></div><button class="btn g" data-c360="${esc(t.id)}">Customer 360</button></div>`).join('')||'<div class="item">暂无待办任务</div>'}
function renderCalendar(){if(!ensureSections())return;const a=taskList(),groups=[['今天',a.filter(x=>x.priority==='紧急'||x.priority==='高')],['未来3天',a.filter(x=>x.priority==='普通'&&x.stage!=='won')],['复购/长期',a.filter(x=>x.stage==='won')]];$('#calRows2').innerHTML=groups.map(([n,rows])=>`<div style="margin-bottom:14px"><b>${n}</b>${rows.map(t=>`<div class="item"><b>${esc(t.company)}</b> · ${esc(t.action)} <span class="tag">${t.prob}%</span><br><small>${esc(t.reason)}</small></div>`).join('')||'<div class="item"><small>暂无事项</small></div>'}</div>`).join('')}
function open360(id){const db=data(),c=(db.customers||[]).find(x=>x.id===id);if(!c)return;const signals=(db.signals||[]).filter(x=>x.customerId===id).slice().reverse(),quotes=(db.quotes||[]).filter(x=>x.customerId===id),orders=(db.orders||[]).filter(x=>x.customerId===id);let lead=(db.leads||[]).find(l=>(l.company||'').toLowerCase()===(c.company||'').toLowerCase());const latest=signals[0],p=prob(db,c);$('#c360Title').textContent=`${c.company} · Customer 360`;$('#c360Body').innerHTML=`<div class="grid4"><div class="card kpi"><small>成交概率</small><b>${p}%</b></div><div class="card kpi"><small>阶段</small><b style="font-size:18px">${esc(c.stage||'prospect')}</b></div><div class="card kpi"><small>购买信号</small><b>${signals.length}</b></div><div class="card kpi"><small>订单</small><b>${orders.length}</b></div></div><div class="two" style="margin-top:10px"><div class="card"><b>公司与决策人</b><p>国家：${esc(c.country||'-')}<br>渠道：${esc(c.channel||'-')}<br>联系人：${esc(c.contact||lead?.contact||'-')}<br>职位：${esc(c.role||lead?.role||'-')}<br>邮箱：${esc(lead?.email||'-')}<br>网站：${esc(lead?.domain||'-')}</p></div><div class="card"><b>AI 下一步</b><p><b>${esc(nextAction(db,c))}</b><br>产品需求：${esc(c.need||'-')}<br>产品缺口：${esc(c.gap||'-')}<br>最近信号：${esc(latest?.type||'-')} ${latest?.time?`· ${esc(latest.time)}`:''}</p></div></div><div class="two" style="margin-top:10px"><div class="card"><b>沟通 / 信号历史</b>${signals.slice(0,8).map(s=>`<div class="item"><span class="tag">${esc(s.type)}</span> ${esc(s.model||'')}<br><small>${esc(s.note||'')} · ${esc(s.time||'')}</small></div>`).join('')||'<div class="item">暂无互动</div>'}</div><div class="card"><b>报价 / 订单</b>${quotes.map(q=>`<div class="item">报价 ${esc(q.model)} · ${q.qty||0} pcs · ${q.total||0} · ${esc(q.status||'')}</div>`).join('')||'<div class="item">暂无报价</div>'}${orders.map(o=>`<div class="item">订单 ${esc(o.id)} · ${esc(o.model)} · ${o.qty||0} pcs · ${esc(o.status||'')}</div>`).join('')}</div></div><div class="card" style="margin-top:10px"><b>客户记忆</b><p>${esc(c.notes||'暂无客户记忆')}</p></div>`;$('#customer360Modal').showModal()}
function augmentCustomers(){const tbody=$('#cr');if(!tbody)return;$$('tr',tbody).forEach(tr=>{if(tr.querySelector('[data-c360]'))return;const name=tr.querySelector('td b')?.textContent?.trim();if(!name)return;const db=data(),c=(db.customers||[]).find(x=>x.company===name);const last=tr.lastElementChild;if(c&&last){const b=document.createElement('button');b.className='btn g';b.dataset.c360=c.id;b.textContent='360';b.style.marginLeft='5px';last.appendChild(b)}})}
function bind(){document.addEventListener('click',e=>{const b=e.target.closest('[data-c360]');if(b){e.preventDefault();open360(b.dataset.c360)}});document.addEventListener('change',e=>{if(e.target?.id==='taskFilter2')renderTasks()});document.addEventListener('click',e=>{if(e.target?.id==='taskRefresh2')renderTasks();if(e.target?.id==='calRefresh2')renderCalendar()});}
function boot(){let n=0,t=setInterval(()=>{n++;if(ensureSections()){clearInterval(t);renderTasks();renderCalendar();augmentCustomers();bind();const obs=new MutationObserver(ms=>{if(ms.some(m=>m.target?.id==='cr'||m.target?.closest?.('#cr')))augmentCustomers()});const cr=$('#cr');if(cr)obs.observe(cr,{childList:true,subtree:true})}else if(n>50)clearInterval(t)},200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
window.AI_SALES_ACTION_CENTER={renderTasks,renderCalendar,open360,taskList};
})();
