/* AI TRADE — Sales Execution Pack 1.0 */
(()=>{
const DBK='aitrade_full59_v1', OK='aitrade_automation_orchestrator_v1', GK='aitrade_goal_gap_v1', KEY='aitrade_sales_execution_pack_v1';
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')||d}catch{return d}}; const put=(k,v)=>localStorage.setItem(k,JSON.stringify(v)); const now=()=>new Date().toISOString();
function state(){return get(KEY,{leadAcquisition:{enabled:true,dailyCap:100,lastRun:null},negotiation:{enabled:true},sampleToOrder:{enabled:true},stats:{leadRequests:0,negotiationTasks:0,sampleTasks:0},updatedAt:null})}
function save(s){s.updatedAt=now();put(KEY,s);window.AITRADE_CLOUD?.push?.()}
function action(o,a){let fp=a.fingerprint;if(o.actions.some(x=>x.fingerprint===fp&&['open','ready','blocked'].includes(x.status)))return false;o.actions.push({id:'ACT-EXEC-'+Date.now()+Math.random().toString(36).slice(2,6),status:'open',requiresApproval:false,createdAt:now(),priority:'normal',...a});o.stats.actionsCreated=(o.stats.actionsCreated||0)+1;return true}
function run(){let s=state(),db=get(DBK,{customers:[],leads:[],signals:[],quotes:[],orders:[]}),o=get(OK,{enabled:true,events:[],actions:[],stats:{actionsCreated:0}}),g=get(GK,{}),date=new Date().toISOString().slice(0,10);
 // Autonomous Lead Acquisition: convert Goal gap into acquisition request; external discovery connector executes later.
 let gap=Math.min(+(g.gaps?.leads||0),s.leadAcquisition.dailyCap);if(s.leadAcquisition.enabled&&gap>0){if(action(o,{type:'autonomous_lead_acquisition',priority:'high',title:`自动获客任务：补充 ${gap} 个 Leads`,next:'Lead Intelligence：发现公司 → 官网验证 → ICP评分 → 去重 → 决策人增强 → Customer Brain',targetCount:gap,fingerprint:`auto-leads:${date}`}))s.stats.leadRequests++;s.leadAcquisition.lastRun=now();}
 // Negotiation Brain: infer objection and create exchange-condition strategy. Never auto-concede price.
 (db.signals||[]).forEach(sig=>{let t=String(sig.type||'')+' '+String(sig.text||sig.body||sig.note||'');let c=(db.customers||[]).find(x=>String(x.id)===String(sig.customerId));if(!c)return;let kind=null,strategy=null;if(/too high|expensive|降价|price high|precio alto/i.test(t)){kind='price';strategy='不要直接降价；先确认目标数量/目标价。可用数量、付款条件、包装或年度采购承诺交换价格空间。'}else if(/moq|minimum order|起订/i.test(t)){kind='moq';strategy='确认试单目的；优先用标准包装/现有颜色降低试单门槛，定制条件保持正常MOQ。'}else if(/payment|付款|credit|账期/i.test(t)){kind='payment';strategy='账期属于风险条件；保持 Human Approval，并以订单规模/历史付款记录换取条件。'}else if(/exclusive|exclusiv|独家|代理/i.test(t)){kind='exclusive';strategy='不直接承诺独家；先绑定区域、期限、年度采购目标和未达标自动失效条款。'}else if(/lead time|delivery|交期/i.test(t)){kind='leadtime';strategy='先确认数量、包装和认证要求，再给可兑现交期；不可为成交虚报交期。'}if(kind&&action(o,{type:'negotiation_strategy',customerId:c.id,company:c.company,priority:'high',title:`谈判策略：${kind}`,next:strategy,requiresApproval:true,status:'blocked',fingerprint:`nego:${sig.id||sig.createdAt||t.slice(0,30)}:${kind}`}))s.stats.negotiationTasks++;});
 // Sample-to-Order Engine: create milestone tasks after sample signals.
 (db.signals||[]).forEach(sig=>{let t=String(sig.type||'');if(!/sample|样品|muestra/i.test(t))return;let c=(db.customers||[]).find(x=>String(x.id)===String(sig.customerId));if(!c)return;let base=new Date(sig.createdAt||sig.date||Date.now());[['签收确认',3,'确认样品是否收到、包装/外观是否完好'],['测试反馈',7,'询问音质、佩戴、连接、续航及目标市场反馈'],['订单推进',14,'根据反馈生成修改项/正式报价/试单建议']].forEach(([name,days,next])=>{let due=new Date(base.getTime()+days*864e5).toISOString().slice(0,10);if(action(o,{type:'sample_to_order',customerId:c.id,company:c.company,priority:days===14?'high':'normal',title:`样品→订单：${name}`,due,next,fingerprint:`sample:${sig.id||sig.createdAt}:${days}`}))s.stats.sampleTasks++;});});
 o.actions=o.actions.slice(-1800);put(OK,o);save(s);return {state:s,actions:o.actions};}
 window.SalesExecutionPack={run,state};setTimeout(run,3200);setInterval(run,60000);
})();