(()=>{
const SK='aitrade_sdr2_v1';
let sdr=JSON.parse(localStorage.getItem(SK)||'null')||{campaigns:[],queue:[]};
const S=()=>localStorage.setItem(SK,JSON.stringify(sdr));
const E=s=>String(s??'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]));
function dmFor(company){try{let d=JSON.parse(localStorage.getItem('aitrade_decision_makers_v1')||'null');return d?.people?.filter(x=>(x.company||'').toLowerCase()===(company||'').toLowerCase()).sort((a,b)=>(b.confidence||0)-(a.confidence||0))[0]||null}catch{return null}}
function lang(c){let x=(c.lang||c.country||'').toLowerCase();return /spanish|mex|méx|墨西哥|spain|español/.test(x)?'es':'en'}
function productFor(c){try{return best(c,1)[0]?.p||PRODUCTS[0]}catch{return PRODUCTS[0]}}
function subject(c,p,L){if(L==='es')return `Propuesta OEM/ODM para ${p.model} — ${c.company}`;return `OEM/ODM proposal for ${p.model} — ${c.company}`}
function body(c,p,d,L,step){let name=d?.name||c.contact||'there',role=d?.role||c.role||'',pts=profile(p).points.join(', '),moq=p.moq||1000,price=p.price||'available on request';if(L==='es'){
 if(step==='D1')return `Hola ${name},\n\nSoy Mamba de Kinganda, fabricante OEM/ODM de auriculares en Shenzhen. Vi que ${c.company} trabaja en ${c.channel||'electrónica de consumo'} y creo que nuestro ${p.model} puede encajar bien con su portafolio.\n\nPuntos clave: ${pts}. MOQ desde ${moq} pcs y podemos personalizar logo, empaque y colores. Precio de referencia interno: ${price}.\n\n¿Le interesa que le envíe ficha técnica, fotos y una cotización para ${moq}/3000/5000 pcs?\n\nSaludos,\nMamba`;
 if(step==='D3')return `Hola ${name},\n\nSolo quería dar seguimiento a mi mensaje sobre ${p.model}. Para ${c.company}, puedo preparar una comparación rápida de precio, MOQ y opciones OEM/ODM para el mercado mexicano.\n\nSi me indica su volumen objetivo, le envío una propuesta concreta.\n\nSaludos,\nMamba`;
 if(step==='D7')return `Hola ${name},\n\nComparto otro enfoque: ${p.model} destaca por ${pts}. Podemos hacer una muestra con su logo y empaque antes de un pedido mayor.\n\n¿Quiere que le prepare una opción de muestra + precio para 1000/3000/5000 pcs?\n\nMamba`;
 return `Hola ${name},\n\nÚltimo seguimiento por ahora. Si ${p.model} no es la categoría correcta, puedo recomendar otros modelos de nuestro catálogo según su canal y rango de precio.\n\nSi me dice qué tipo de auricular busca, le envío 3 opciones seleccionadas.\n\nMamba`;
 }
 if(step==='D1')return `Hi ${name},\n\nThis is Mamba from Kinganda, an OEM/ODM earphone manufacturer in Shenzhen. I saw that ${c.company} is active in ${c.channel||'consumer electronics'}, and I believe our ${p.model} could fit your portfolio well.\n\nKey points: ${pts}. MOQ starts from ${moq} pcs, with custom logo, packaging and colors available. Internal reference price: ${price}.\n\nWould you like me to send the spec sheet, product photos and a quotation for ${moq}/3000/5000 pcs?\n\nBest regards,\nMamba`;
 if(step==='D3')return `Hi ${name},\n\nJust following up on my note about ${p.model}. For ${c.company}, I can prepare a quick comparison of pricing, MOQ and OEM/ODM options for your market.\n\nIf you share your target volume, I can send a concrete proposal.\n\nBest,\nMamba`;
 if(step==='D7')return `Hi ${name},\n\nOne more angle that may be relevant: ${p.model} stands out for ${pts}. We can also prepare a branded sample before a larger order.\n\nWould you like a sample option plus pricing for 1000/3000/5000 pcs?\n\nMamba`;
 return `Hi ${name},\n\nFinal follow-up for now. If ${p.model} is not the right category, I can recommend other models from our catalog based on your sales channel and price range.\n\nIf you tell me what type of earphone you are sourcing, I’ll shortlist 3 suitable options.\n\nMamba`;
}
function build(c){let p=productFor(c),d=dmFor(c.company),L=lang(c),id='SDR'+Date.now()+Math.random().toString(36).slice(2,5),steps=['D1','D3','D7','D14'].map((step,i)=>({step,offset:[0,3,7,14][i],subject:subject(c,p,L),body:body(c,p,d,L,step),status:'待审批'}));let camp={id,customerId:c.id,company:c.company,decisionMaker:d?.name||c.contact||'',role:d?.role||c.role||'',confidence:d?.confidence||0,language:L,model:p.model,created:new Date().toISOString(),status:'待审批',steps};sdr.campaigns.unshift(camp);S();render();return camp}
function approve(id){let x=sdr.campaigns.find(z=>z.id===id);if(!x)return;x.status='已审批';x.steps.forEach(s=>s.status='已排队');let now=Date.now();x.steps.forEach(s=>sdr.queue.push({campaignId:x.id,company:x.company,step:s.step,due:new Date(now+s.offset*86400000).toISOString(),status:'等待发送',subject:s.subject,body:s.body}));S();render()}
function cancel(id){let x=sdr.campaigns.find(z=>z.id===id);if(x){x.status='已暂停';x.steps.forEach(s=>{if(s.status!=='已发送')s.status='已暂停'});sdr.queue=sdr.queue.filter(q=>q.campaignId!==id||q.status==='已发送');S();render()}}
function render(){let host=document.getElementById('sdr2Host');if(!host)return;let cs=(typeof db!=='undefined'?db.customers:[]).slice().sort((a,b)=>(prob(b)-prob(a)));let options=cs.map(c=>`<option value="${E(c.id)}">${E(c.company)} · ${prob(c)}% · ${E(dmFor(c.company)?.name||c.contact||'未锁定决策人')}</option>`).join('');let camps=sdr.campaigns.slice(0,20);let queue=sdr.queue.slice().sort((a,b)=>new Date(a.due)-new Date(b.due)).slice(0,30);host.innerHTML=`<div class="card"><b>生成开发序列</b><div class="sub">Customer Brain + Decision Maker Engine + Product Brain → 自动选产品、语言和跟进节奏。所有外发消息默认必须人工审批。</div><div class="toolbar"><select id="sdr2Customer" class="input wide">${options}</select><button class="btn" id="sdr2Build">生成 D1/D3/D7/D14 序列</button></div></div><div class="two" style="margin-top:10px"><div class="card"><b>开发活动</b>${camps.map(x=>`<div class="item"><b>${E(x.company)}</b> · ${E(x.model)} <span class="tag">${x.language==='es'?'ES':'EN'}</span><br><small>决策人：${E(x.decisionMaker||'未锁定')} ${x.confidence?`· ${x.confidence}%`:''} · 状态：${E(x.status)}</small><div class="toolbar">${x.status==='待审批'?`<button class="btn" onclick="SDR2.approve('${x.id}')">人工审批并排队</button>`:''}<button class="btn g" onclick="SDR2.preview('${x.id}')">预览</button>${x.status!=='已暂停'?`<button class="btn r" onclick="SDR2.cancel('${x.id}')">暂停</button>`:''}</div></div>`).join('')||'<div class="item">暂无开发活动</div>'}</div><div class="card"><b>发送队列</b>${queue.map(q=>`<div class="item"><b>${E(q.company)} · ${q.step}</b><br><small>${new Date(q.due).toLocaleDateString()} · ${E(q.status)}</small></div>`).join('')||'<div class="item">暂无待发送任务</div>'}</div></div>`;document.getElementById('sdr2Build')?.addEventListener('click',()=>{let id=document.getElementById('sdr2Customer').value,c=(typeof db!=='undefined'?db.customers:[]).find(x=>x.id===id);if(c)build(c)})}
function preview(id){let x=sdr.campaigns.find(z=>z.id===id);if(!x)return;let txt=x.steps.map(s=>`${s.step}\nSubject: ${s.subject}\n\n${s.body}`).join('\n\n----------------\n\n');let w=window.open('','_blank');w.document.write(`<pre style="white-space:pre-wrap;font:14px/1.6 Arial;padding:24px">${E(txt)}</pre>`)}
function init(){let sec=document.getElementById('sdr');if(!sec)return;let old=sec.innerHTML;sec.innerHTML=`<div class="top"><div><h1>AI SDR 2.0</h1><div class="sub">决策人优先 · Product Brain 自动选品 · 西语/英语自动切换 · D1/D3/D7/D14 自动跟进序列 · Human Approval Gate</div></div><div class="badge">● Approval Required</div></div><div id="sdr2Host"></div><details style="margin-top:12px"><summary class="sub">查看旧版单封开发草稿工具</summary>${old}</details>`;render()}
window.SDR2={approve,cancel,preview,render,build};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();