(()=>{
const KEY='aitrade_full59_v1',MARK='aitrade_public_mexico_seed_v1';
if(localStorage.getItem(MARK))return;
const leads=[
{company:'Viastara',domain:'viastara.com',country:'墨西哥',channel:'Distributor',contact:'Eduardo Escalante',role:'CEO',source:'Public Web · LinkedIn',icp:95,industry:'Consumer Electronics Distribution',need:'消费电子、配件、品牌分销、Retail/B2B',gap:'TWS / Open Ear / OEM耳机产品线机会',evidence:'墨西哥及拉美消费电子与配件分销商，服务Retail和B2B渠道。',url:'https://www.linkedin.com/company/viastara'},
{company:'JLP TRADING',domain:'jlptrading.com',country:'墨西哥',channel:'Importer',contact:'',role:'Buyer / Purchasing',source:'Public Web · LinkedIn',icp:84,industry:'Consumer Electronics Importer',need:'音视频电子产品、亚洲供应链',gap:'蓝牙耳机/TWS补充产品线',evidence:'消费电子进口商和分销商，与中国、香港、台湾、韩国有长期进口业务。',url:'https://www.linkedin.com/company/jlp-trading'},
{company:'DICOM.MX',domain:'dicom.mx',country:'墨西哥',channel:'Marketplace Retailer',contact:'',role:'Buyer / Product Manager',source:'Public Web · LinkedIn',icp:93,industry:'Consumer Electronics / E-commerce',need:'Amazon、Mercado Libre、Sears、Sanborns等多平台销售',gap:'TWS / Open Ear / Clip Ear 高周转SKU',evidence:'墨西哥科技产品销售与分销企业，覆盖Amazon、Mercado Libre等主流Marketplace。',url:'https://mx.linkedin.com/company/dicomdgo'},
{company:'Select Sound',domain:'selectsound.com.mx',country:'墨西哥',channel:'Brand Owner',contact:'',role:'Purchasing / Product Manager',source:'Public Web · LinkedIn',icp:94,industry:'Consumer Electronics / Audio',need:'音频、手机配件、零售渠道',gap:'私模TWS / Open Ear / Clip Ear ODM',evidence:'墨西哥消费电子音频品牌，产品含Audio、手机配件，并参与Walmart战略活动。',url:'https://www.linkedin.com/company/select-sound-mx'},
{company:'Intéligos',domain:'inteligos.com',country:'墨西哥',channel:'Distributor',contact:'',role:'Purchasing / Business Development',source:'Public Web · LinkedIn',icp:80,industry:'Audio/Video Wholesale Distribution',need:'Audio/Video、Consumer/Retail渠道',gap:'消费级耳机作为渠道补充',evidence:'墨西哥专业技术批发分销商，覆盖Consumer/Retail市场和多品牌渠道开发。',url:'https://www.linkedin.com/company/inteligos'},
{company:'Stuffactory',domain:'stuffactory.mx',country:'墨西哥',channel:'Brand Owner',contact:'',role:'Buyer / Category Manager',source:'Public Web · LinkedIn',icp:98,industry:'Consumer Electronics',need:'Audífonos、品牌运营、Retail、Category Management',gap:'TWS / Open Ear / Clip Ear 私模OEM',evidence:'墨西哥消费电子品牌集团，运营自有品牌，明确销售Audífonos并覆盖多种零售业态。',url:'https://www.linkedin.com/company/stuffactory/'},
{company:'Aiwa Mexico',domain:'',country:'墨西哥',channel:'Brand Owner',contact:'',role:'Purchasing / Product Manager',source:'Public Web · LinkedIn',icp:83,industry:'Consumer Electronics / Audio / TV',need:'消费电子、音频、LATAM分销',gap:'耳机ODM/OEM合作机会',evidence:'Aiwa墨西哥团队，业务标签包含Consumer Electronics、LATAM、Distribution、Audio和TV。',url:'https://www.linkedin.com/company/aiwa-mexico'},
{company:'Distribuciones Compupaz',domain:'compupaz.com.mx',country:'墨西哥',channel:'Wholesaler',contact:'',role:'Buyer / Purchasing',source:'Public Web · LinkedIn',icp:89,industry:'Consumer Electronics Wholesale / E-commerce',need:'科技产品批发、电商、进口产品',gap:'TWS / Open Ear / 低MOQ耳机',evidence:'墨西哥电子消费品和科技产品批发、电商企业，同时销售进口产品。',url:'https://www.linkedin.com/company/distribuciones-compupaz'},
{company:'Icon Case',domain:'iconcase.com.mx',country:'墨西哥',channel:'Importer',contact:'',role:'Owner / Buyer',source:'Public Web · Website',icp:97,industry:'Mobile Accessories Wholesale',need:'Fundas、cargadores、cables、audífonos、bocinas、powerbanks',gap:'高周转TWS / Open Ear / Clip Ear',evidence:'墨西哥手机配件直接进口商和批发商，官网明确销售Audífonos和Bocinas。',url:'https://www.iconcase.com.mx/'},
{company:'Hi Tech Audio S.A. de C.V.',domain:'htaudio.mx',country:'墨西哥',channel:'Distributor',contact:'',role:'Purchasing / Director',source:'Public Web · LinkedIn',icp:78,industry:'Wholesale Import & Export / Professional Audio',need:'专业音频、B2B、Retail、电商',gap:'商务单耳/音频周边补充',evidence:'墨西哥专业音频重要分销商，覆盖B2B、Retail与电子商务。',url:'https://www.linkedin.com/company/hi-tech-audio-s-a'},
{company:'SHOP X',domain:'shopx.com.mx',country:'墨西哥',channel:'Wholesaler',contact:'',role:'Buyer / Purchasing',source:'Public Web · LinkedIn',icp:86,industry:'Consumer Electronics Retail / Wholesale',need:'消费电子批发和零售、线上销售',gap:'性价比TWS / Open Ear',evidence:'墨西哥消费科技供应商，提供电子产品批发和零售。',url:'https://mx.linkedin.com/company/shopx-mx'},
{company:'MITZU',domain:'mitzu.com',country:'墨西哥',channel:'Brand Owner',contact:'',role:'Purchasing / Product Manager',source:'Public Web · LinkedIn',icp:96,industry:'Electronics Wholesale / Audio',need:'电子产品、批发、Retail、Audífonos、Bocinas',gap:'TWS / Open Ear / Clip Ear OEM与新品线',evidence:'墨西哥大型电子品牌和批发企业，明确经营Audífonos、Bocinas、Audio/Video。',url:'https://mx.linkedin.com/company/mitzuoficial'},
{company:'Grupo Recse Internacional',domain:'gruporecse.com',country:'墨西哥',channel:'Distributor',contact:'',role:'Buyer / Business Development',source:'Public Web · Website',icp:76,industry:'Consumer / HiFi / Hi-End Distribution',need:'品牌分销、消费级音频、高保真',gap:'高端TWS或开放式耳机渠道测试',evidence:'墨西哥Consumer、HiFi和Hi-End音频科技分销商，拥有全国分销和品牌合作网络。',url:'https://gruporecse.com/'},
{company:'Electromart',domain:'electromart.com.mx',country:'墨西哥',channel:'Distributor',contact:'',role:'Ventas Mayoreo / Buyer',source:'Public Web · Website',icp:94,industry:'Consumer Electronics Distribution',need:'消费电子、家电、Car Audio、连锁和批发渠道',gap:'耳机/TWS新品类与线上渠道SKU',evidence:'墨西哥33年以上消费电子分销企业，覆盖传统渠道、大型连锁、批发商和互联网。',url:'https://www.electromart.com.mx/'},
{company:'LESSO MEXICO SA DE CV',domain:'',country:'墨西哥',channel:'Wholesaler',contact:'',role:'Buyer / Product Manager',source:'Public Web · LinkedIn',icp:79,industry:'Consumer Electronics / Audio Wholesale',need:'电视、音频、家居消费电子、Retail',gap:'TWS/开放式耳机产品线测试',evidence:'墨西哥本地音频设备和大型家电批发商，运营FOL Mexico消费电子品牌。',url:'https://mx.linkedin.com/company/lesso-mexico-sa-de-cv'}
];
let db;try{db=JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){}if(!db)db={customers:[],signals:[],quotes:[],orders:[],leads:[]};
db.customers=db.customers||[];db.leads=db.leads||[];
const same=(a,b)=>(a.domain&&b.domain&&a.domain.toLowerCase()===b.domain.toLowerCase())||((a.company||'').toLowerCase()===(b.company||'').toLowerCase());
for(const x of leads){if(!db.leads.some(y=>same(x,y)))db.leads.push({id:'PW'+Math.random().toString(36).slice(2,10),company:x.company,domain:x.domain,country:x.country,channel:x.channel,contact:x.contact,role:x.role,email:'',source:x.source,icp:x.icp,product:'',promoted:true,industry:x.industry,notes:x.evidence,url:x.url});if(x.icp>=70&&!db.customers.some(c=>same(x,c)))db.customers.push({id:'C'+Date.now()+Math.random().toString(36).slice(2,7),company:x.company,country:x.country,channel:x.channel,contact:x.contact,role:x.role,lang:'Spanish',need:x.need,gap:x.gap,icp:x.icp,stage:'prospect',domain:x.domain,email:'',leadSource:x.source,leadScore:x.icp,notes:`[Hybrid Lead Engine] 公开网络验证后自动进入 Customer Brain。\n证据：${x.evidence}\n来源：${x.url}\n待补：决策人Verified Email / Phone。`});}
localStorage.setItem(KEY,JSON.stringify(db));localStorage.setItem(MARK,new Date().toISOString());
})();
