/* AI TRADE — Self-Healing 1.0 */
(()=>{
const CFG=()=>window.AITRADE_CLOUD_CONFIG||{};
async function sb(){if(!window.supabase){await new Promise((res,rej)=>{let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=res;s.onerror=rej;document.head.appendChild(s)})}let c=CFG();return window.supabase.createClient(c.url,c.anonKey,{auth:{persistSession:true,autoRefreshToken:true}})}
async function call(action,payload={}){let c=await sb(),{data:{session}}=await c.auth.getSession();if(!session)throw new Error('请先登录 AI TRADE 云同步');let cfg=CFG(),r=await fetch(`${cfg.url}/functions/v1/self-healing-runner`,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${session.access_token}`,'apikey':cfg.anonKey},body:JSON.stringify({action,...payload})});let x=await r.json();if(!r.ok||!x.ok)throw new Error(x.detail||x.error||'Self-Healing执行失败');return x}
function esc(x){return String(x??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function css(){if(document.getElementById('shStyle'))return;let s=document.createElement('style');s.id='shStyle';s.textContent=`#shBtn{position:fixed;right:14px;bottom:338px;z-index:9994;border:0;border-radius:999px;padding:10px 13px;background:#0f766e;color:#fff;font:700 12px Arial;box-shadow:0 8px 25px #0002}#shModal{position:fixed;inset:0;z-index:10070;background:#0f172a80;display:none;align-items:center;justify-content:center;padding:14px}#shModal .box{width:min(980px,96vw);max-height:90vh;overflow:auto;background:#f8fafc;border-radius:18px;padding:16px}.shGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.shCard{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:12px}.shRow{background:#fff;border:1px solid #e5e7eb;border-radius:11px;padding:10px;margin:7px 0;font-size:12px}.shBtn{border:0;border-radius:9px;padding:9px 11px;background:#0f766e;color:#fff;font-weight:700}.shGhost{background:#ecfdf5;color:#047857}@media(max-width:720px){#shBtn{bottom:302px}.shGrid{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
async function load(){let [s,e]=await Promise.all([call('settings_get'),call('events')]);return {settings:s.settings,events:e.events||[]}}
function render(d){let b=document.getElementById('shBody');if(!b)return;let ev=d.events||[],healed=ev.filter(x=>x.status==='healed').length,mail=ev.filter(x=>x.issue_type==='mail_transient_failure').length,stuck=ev.filter(x=>x.issue_type==='stuck_worker').length,dedup=ev.filter(x=>x.issue_type==='duplicate_alert').length,s=d.settings||{};b.innerHTML=`<div style="display:flex;justify-content:space-between;gap:8px;align-items:center"><div><h2 style="margin:0">Self-Healing 1.0</h2><div style="font-size:11px;color:#64748b;margin-top:4px">自动恢复瞬时邮件失败、卡死 Worker 与重复告警；不会绕过 Gmail OAuth、价格审批或人工授权。</div></div><button class="shBtn shGhost" onclick="AI_SELF_HEAL.close()">关闭</button></div><div class="shGrid" style="margin-top:12px"><div class="shCard"><small>累计修复</small><div style="font-size:24px;font-weight:900">${healed}</div></div><div class="shCard"><small>邮件重试</small><div style="font-size:24px;font-weight:900">${mail}</div></div><div class="shCard"><small>Worker恢复</small><div style="font-size:24px;font-weight:900">${stuck}</div></div><div class="shCard"><small>告警去重</small><div style="font-size:24px;font-weight:900">${dedup}</div></div></div><h3>自动修复设置</h3><div class="shCard"><label><input id="shEnabled" type="checkbox" ${s.enabled!==false?'checked':''}> 启用 Self-Healing</label><br><br><label><input id="shMail" type="checkbox" ${s.retry_failed_mail!==false?'checked':''}> 自动重试瞬时邮件失败</label><br><label><input id="shWake" type="checkbox" ${s.revive_stuck_wakeups!==false?'checked':''}> 自动恢复卡死 Worker</label><br><label><input id="shAlert" type="checkbox" ${s.resolve_stale_alerts!==false?'checked':''}> 自动合并重复告警</label><br><br>邮件自动重试上限 <input id="shRetries" type="number" min="0" max="5" value="${s.max_mail_retries??2}" style="width:62px"> 次　Worker卡死判定 <input id="shStuck" type="number" min="10" max="180" value="${s.stuck_minutes??20}" style="width:70px"> 分钟<br><br><button class="shBtn" onclick="AI_SELF_HEAL.save()">保存设置</button> <button class="shBtn shGhost" onclick="AI_SELF_HEAL.runNow()">立即自检并修复</button></div><h3>最近修复记录</h3>${ev.slice(0,60).map(x=>`<div class="shRow"><b>${esc(x.issue_type)}</b> → ${esc(x.action)} <span style="float:right;color:#047857;font-weight:800">${esc(x.status)}</span><div style="color:#64748b;margin-top:4px">${esc(x.target_type||'')} ${esc(x.target_id||'')} · ${esc(x.created_at||'')}</div></div>`).join('')||'<div class="shRow">暂无修复记录。系统会每5分钟自动检查一次。</div>'}`}
async function refresh(){let b=document.getElementById('shBody');if(b)b.innerHTML='<div style="padding:30px;text-align:center">加载 Self-Healing 状态...</div>';try{render(await load())}catch(e){b.innerHTML=`<div style="padding:20px;color:#b42318">${esc(e.message)}</div>`}}
async function save(){try{await call('settings_save',{enabled:shEnabled.checked,retry_failed_mail:shMail.checked,revive_stuck_wakeups:shWake.checked,resolve_stale_alerts:shAlert.checked,max_mail_retries:+shRetries.value,stuck_minutes:+shStuck.value});await refresh()}catch(e){alert(e.message)}}
async function runNow(){try{await call('run');await refresh()}catch(e){alert(e.message)}}
function open(){document.getElementById('shModal').style.display='flex';refresh()}function close(){document.getElementById('shModal').style.display='none'}
function boot(){css();if(!document.getElementById('shBtn')){let b=document.createElement('button');b.id='shBtn';b.textContent='↻ Self-Heal';b.onclick=open;document.body.appendChild(b)}if(!document.getElementById('shModal')){let m=document.createElement('div');m.id='shModal';m.innerHTML='<div class="box" id="shBody"></div>';m.onclick=e=>{if(e.target===m)close()};document.body.appendChild(m)}}
window.AI_SELF_HEAL={open,close,refresh,save,runNow};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();