create table if not exists public.ai_trade_activities (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  source_id text not null,
  customer_source_id text,
  activity_type text not null,
  channel text,
  direction text,
  subject text,
  content text,
  points integer default 0 not null,
  occurred_at timestamp with time zone default now() not null,
  payload jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint ai_trade_activities_pkey PRIMARY KEY (id),
  constraint ai_trade_activities_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
  constraint ai_trade_activities_user_id_source_id_key UNIQUE (user_id, source_id)
);
alter table public.ai_trade_activities enable row level security;
grant select,insert,update,delete on public.ai_trade_activities to authenticated;
create policy ai_trade_activities_owner on public.ai_trade_activities for all to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) with check ((( SELECT auth.uid() AS uid) = user_id));

create table if not exists public.ai_trade_approvals (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  source_id text not null,
  entity_type text not null,
  entity_source_id text not null,
  customer_source_id text,
  approval_type text not null,
  status text default 'pending'::text not null,
  risk_flags jsonb default '[]'::jsonb not null,
  requested_at timestamp with time zone default now() not null,
  decided_at timestamp with time zone,
  payload jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint ai_trade_approvals_pkey PRIMARY KEY (id),
  constraint ai_trade_approvals_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
  constraint ai_trade_approvals_user_id_source_id_key UNIQUE (user_id, source_id)
);
alter table public.ai_trade_approvals enable row level security;
grant select,insert,update,delete on public.ai_trade_approvals to authenticated;
create policy ai_trade_approvals_owner on public.ai_trade_approvals for all to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) with check ((( SELECT auth.uid() AS uid) = user_id));

create table if not exists public.ai_trade_contacts (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  source_id text not null,
  customer_source_id text,
  company text,
  person_name text,
  role text,
  email text,
  phone text,
  whatsapp text,
  linkedin_url text,
  verification_status text default 'unverified'::text not null,
  confidence integer default 0 not null,
  payload jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint ai_trade_contacts_confidence_check CHECK (((confidence >= 0) AND (confidence <= 100))),
  constraint ai_trade_contacts_pkey PRIMARY KEY (id),
  constraint ai_trade_contacts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
  constraint ai_trade_contacts_user_id_source_id_key UNIQUE (user_id, source_id)
);
alter table public.ai_trade_contacts enable row level security;
grant select,insert,update,delete on public.ai_trade_contacts to authenticated;
create policy ai_trade_contacts_owner on public.ai_trade_contacts for all to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) with check ((( SELECT auth.uid() AS uid) = user_id));

create table if not exists public.ai_trade_customers (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  source_id text not null,
  company text not null,
  country text,
  channel text,
  domain text,
  website text,
  stage text default 'prospect'::text not null,
  icp_score integer default 0 not null,
  next_action text,
  notes text,
  payload jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint ai_trade_customers_icp_score_check CHECK (((icp_score >= 0) AND (icp_score <= 100))),
  constraint ai_trade_customers_pkey PRIMARY KEY (id),
  constraint ai_trade_customers_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
  constraint ai_trade_customers_user_id_source_id_key UNIQUE (user_id, source_id)
);
alter table public.ai_trade_customers enable row level security;
grant select,insert,update,delete on public.ai_trade_customers to authenticated;
create policy ai_trade_customers_owner on public.ai_trade_customers for all to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) with check ((( SELECT auth.uid() AS uid) = user_id));

create table if not exists public.ai_trade_products (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  source_id text not null,
  model text not null,
  category text,
  name text,
  price numeric,
  cost numeric,
  moq integer,
  status text default 'active'::text not null,
  payload jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint ai_trade_products_pkey PRIMARY KEY (id),
  constraint ai_trade_products_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
  constraint ai_trade_products_user_id_source_id_key UNIQUE (user_id, source_id)
);
alter table public.ai_trade_products enable row level security;
grant select,insert,update,delete on public.ai_trade_products to authenticated;
create policy ai_trade_products_owner on public.ai_trade_products for all to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) with check ((( SELECT auth.uid() AS uid) = user_id));

create table if not exists public.ai_trade_schema_versions (
  user_id uuid not null,
  version text not null,
  applied_at timestamp with time zone default now() not null,
  constraint ai_trade_schema_versions_pkey PRIMARY KEY (user_id, version),
  constraint ai_trade_schema_versions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);
alter table public.ai_trade_schema_versions enable row level security;
grant select,insert,update,delete on public.ai_trade_schema_versions to authenticated;
create policy ai_trade_schema_versions_owner on public.ai_trade_schema_versions for all to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) with check ((( SELECT auth.uid() AS uid) = user_id));

create table if not exists public.ai_trade_sync_runs (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  status text not null,
  entity_counts jsonb default '{}'::jsonb not null,
  error text,
  started_at timestamp with time zone default now() not null,
  finished_at timestamp with time zone,
  constraint ai_trade_sync_runs_pkey PRIMARY KEY (id),
  constraint ai_trade_sync_runs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);
alter table public.ai_trade_sync_runs enable row level security;
grant select,insert,update,delete on public.ai_trade_sync_runs to authenticated;
create policy ai_trade_sync_runs_owner on public.ai_trade_sync_runs for all to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) with check ((( SELECT auth.uid() AS uid) = user_id));

create table if not exists public.ai_trade_tasks (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  source_id text not null,
  customer_source_id text,
  title text not null,
  status text default 'open'::text not null,
  priority text default 'normal'::text not null,
  due_at timestamp with time zone,
  requires_approval boolean default false not null,
  payload jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint ai_trade_tasks_pkey PRIMARY KEY (id),
  constraint ai_trade_tasks_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
  constraint ai_trade_tasks_user_id_source_id_key UNIQUE (user_id, source_id)
);
alter table public.ai_trade_tasks enable row level security;
grant select,insert,update,delete on public.ai_trade_tasks to authenticated;
create policy ai_trade_tasks_owner on public.ai_trade_tasks for all to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) with check ((( SELECT auth.uid() AS uid) = user_id));
grant usage,select on sequence public.ai_trade_products_id_seq to authenticated;
grant usage,select on sequence public.ai_trade_customers_id_seq to authenticated;
grant usage,select on sequence public.ai_trade_contacts_id_seq to authenticated;
grant usage,select on sequence public.ai_trade_activities_id_seq to authenticated;
grant usage,select on sequence public.ai_trade_tasks_id_seq to authenticated;
grant usage,select on sequence public.ai_trade_approvals_id_seq to authenticated;
grant usage,select on sequence public.ai_trade_sync_runs_id_seq to authenticated;